INSERT INTO vocabulary (word, romaji, audio, type, kanji, kanji_reading, meaning, lesson) VALUES
('いきます', 'ikimasu', '/audio/minna/bai05/ikimasu.mp3', 'verb', '行きます', 'HÀNH', 'đi', 5),
('きます', 'kimasu', '/audio/minna/bai05/kimasu.mp3', 'verb', '来ます', 'LAI', 'đến', 5),
('かえります', 'kaerimasu', '/audio/minna/bai05/kaerimasu.mp3', 'verb', '帰ります', 'QUY', 'về', 5),
('がっこう', 'gakkou', '/audio/minna/bai05/gakkou.mp3', 'noun', '学校', 'HỌC HIỆU', 'trường học', 5),
('スーパー', 'suｰpaｰ', '/audio/minna/bai05/k_suupaa.mp3', 'noun', NULL, NULL, 'siêu thị', 5),
('えき', 'eki', '/audio/minna/bai05/eki.mp3', 'noun', '駅', 'DỊCH', 'ga, nhà ga', 5),
('ひこうき', 'hikouki', '/audio/minna/bai05/hikouki.mp3', 'noun', '飛行機', 'PHI HÀNH CƠ', 'máy bay', 5),
('ふね', 'fune', '/audio/minna/bai05/fune.mp3', 'noun', '船', 'THUYỀN', 'thuyền, tàu thủy', 5),
('でんしゃ', 'densha', '/audio/minna/bai05/densya.mp3', 'noun', '電車', 'ĐIỆN XA', 'tàu điện', 5),
('ちかてつ', 'chikatetsu', '/audio/minna/bai05/chikatetsu.mp3', 'noun', '地下鉄', 'ĐỊA HẠ THIẾT', 'tàu điện ngầm', 5),
('しんかんせん', 'shinkansen', '/audio/minna/bai05/shinkansen.mp3', 'noun', '新幹線', 'TÂN CÁN TUYẾN', 'tàu Shinkansen (tàu điện siêu tốc của Nhật)', 5),
('バス', 'basu', '/audio/minna/bai05/k_basu.mp3', 'noun', NULL, NULL, 'xe buýt', 5),
('タクシー', 'takushiｰ', '/audio/minna/bai05/k_takushii.mp3', 'noun', NULL, NULL, 'tắc-xi', 5),
('じてんしゃ', 'jitensha', '/audio/minna/bai05/jitensya.mp3', 'noun', '自転車', 'TỰ CHUYỂN XA', 'xe đạp', 5),
('あるいて', 'aruite', '/audio/minna/bai05/aruite.mp3', 'adverb', '歩いて', 'BỘ', 'đi bộ', 5),
('ひと', 'hito', '/audio/minna/bai05/hito.mp3', 'noun', '人', 'NHÂN', 'người', 5),
('ともだち', 'tomodachi', '/audio/minna/bai05/tomodachi.mp3', 'noun', '友達', 'HỮU ĐẠT', 'bạn, bạn bè', 5),
('かれ', 'kare', '/audio/minna/bai05/kare.mp3', 'pronoun', '彼', 'BỈ', 'anh ấy, bạn trai', 5),
('かのじょ', 'kanojo', '/audio/minna/bai05/kanojo.mp3', 'pronoun', '彼女', 'BỈ NỮ', 'chị ấy, bạn gái', 5),
('かぞく', 'kazoku', '/audio/minna/bai05/kazoku.mp3', 'noun', '家族', 'GIA TỘC', 'gia đình', 5),
('ひとりで', 'hitoride', '/audio/minna/bai05/hitoride.mp3', 'adverb', '一人で', 'NHẤT NHÂN', 'một mình', 5),
('せんしゅう', 'senshuu', '/audio/minna/bai05/sensyuu.mp3', 'noun', '先週', 'TIÊN CHU', 'tuần trước', 5),
('こんしゅう', 'konshuu', '/audio/minna/bai05/konsyuu.mp3', 'noun', '今週', 'KIM CHU', 'tuần này', 5),
('らいしゅう', 'raishuu', '/audio/minna/bai05/raisyuu.mp3', 'noun', '来週', 'LAI CHU', 'tuần sau', 5),
('こんげつ', 'kongetsu', '/audio/minna/bai05/kongetsu.mp3', 'noun', '今月', 'KIM NGUYỆT', 'tháng này', 5),
('らいげつ', 'raigetsu', '/audio/minna/bai05/raigetsu.mp3', 'noun', '来月', 'LAI NGUYỆT', 'tháng sau', 5),
('きょねん', 'kyonen', '/audio/minna/bai05/kyonen.mp3', 'noun', '去年', 'KHỨ NIÊN', 'năm ngoái', 5),
('ことし', 'kotoshi', '/audio/minna/bai05/kotoshi.mp3', 'noun', NULL, NULL, 'năm nay', 5),
('らいねん', 'rainen', '/audio/minna/bai05/rainen.mp3', 'noun', '来年', 'LAI NIÊN', 'năm sau', 5),
('―がつ', '～gatsu', '/audio/minna/bai05/gatsu.mp3', 'suffix', '―月', 'NGUYỆT', 'tháng -', 5),
('なんがつ', 'nangatsu', '/audio/minna/bai05/nangatsu.mp3', 'pronoun', '何月', 'HÀ NGUYỆT', 'tháng mấy', 5),
('ついたち', 'tsuitachi', '/audio/minna/bai05/tsuitachi.mp3', 'noun', '１日', 'NHẬT', 'ngày mồng 1', 5),
('ふつか', 'futsuka', '/audio/minna/bai05/futsuka.mp3', 'noun', '２日', 'NHẬT', 'ngày mồng 2, 2 ngày', 5),
('みっか', 'mikka', '/audio/minna/bai05/mikka.mp3', 'noun', '３日', 'NHẬT', 'ngày mồng 3, 3 ngày', 5),
('よっか', 'yokka', '/audio/minna/bai05/yokka.mp3', 'noun', '４日', 'NHẬT', 'ngày mồng 4, 4 ngày', 5),
('いつか', 'itsuka', '/audio/minna/bai05/itsuka.mp3', 'noun', '５日', 'NHẬT', 'ngày mồng 5, 5 ngày', 5),
('むいか', 'muika', '/audio/minna/bai05/muika.mp3', 'noun', '６日', 'NHẬT', 'ngày mồng 6, 6 ngày', 5),
('なのか', 'nanoka', '/audio/minna/bai05/nanoka.mp3', 'noun', '７日', 'NHẬT', 'ngày mồng 7, 7 ngày', 5),
('ようか', 'youka', '/audio/minna/bai05/youka.mp3', 'noun', '８日', 'NHẬT', 'ngày mồng 8, 8 ngày', 5),
('ここのか', 'kokonoka', '/audio/minna/bai05/kokonoka.mp3', 'noun', '９日', 'NHẬT', 'ngày mồng 9, 9 ngày', 5),
('とおか', 'tooka', '/audio/minna/bai05/tooka.mp3', 'noun', '１０日', 'NHẬT', 'ngày mồng 10, 10 ngày', 5),
('じゅうよっか', 'juuyokka', '/audio/minna/bai05/juuyokka.mp3', 'noun', '１４日', 'NHẬT', 'ngày 14, 14 ngày', 5),
('はつか', 'hatsuka', '/audio/minna/bai05/hatsuka.mp3', 'noun', '２０日', 'NHẬT', 'ngày 20, 20 ngày', 5),
('にじゅうよっか', 'nijuuyokka', '/audio/minna/bai05/nijuuyokka.mp3', 'noun', '２４日', 'NHẬT', 'ngày 24, 24 ngày', 5),
('―にち', '～nichi', '/audio/minna/bai05/nichi.mp3', 'suffix', '―日', 'NHẬT', 'ngày -, - ngày', 5),
('なんにち', 'nannichi', '/audio/minna/bai05/nannichi.mp3', 'pronoun', '何日', 'HÀ NHẬT', 'ngày mấy, ngày bao nhiêu, mấy ngày, bao nhiêu ngày', 5),
('いつ', 'itsu', '/audio/minna/bai05/itsu.mp3', 'pronoun', NULL, NULL, 'bao giờ, khi nào', 5),
('たんじょうび', 'tanjoubi', '/audio/minna/bai05/tanjoubi.mp3', 'noun', '誕生日', 'ĐẢN SINH NHẬT', 'sinh nhật', 5),
('ふつう', 'futsuu', '/audio/minna/bai05/futsuu.mp3', 'noun', '普通', 'PHỔ THÔNG', 'tàu thường (dừng cả ở các ga lẻ)', 5),
('きゅうこう', 'kyuukou', '/audio/minna/bai05/kyuukou.mp3', 'noun', '急行', 'CẤP HÀNH', 'tàu tốc hành', 5),
('とっきゅう', 'tokkyuu', '/audio/minna/bai05/tokkyuu.mp3', 'noun', '特急', 'ĐẶC CẤP', 'tàu tốc hành đặc biệt', 5),
('つぎの', 'tsugino', '/audio/minna/bai05/tsugino.mp3', 'adjective', '次の', 'THỨ', 'tiếp theo', 5),
('どういたしまして', 'douitashimashite', '/audio/minna/bai05/douitashimashite.mp3', 'phrase', NULL, NULL, 'Không có gì.', 5),
('―ばんせん', '～bansen', '/audio/minna/bai05/bansen.mp3', 'suffix', '―番線', 'PHIÊN TUYẾN', 'sân ga số -', 5),
('はかた', 'hakata', '/audio/minna/bai05/hakata.wav', 'noun', '博多', 'BÁC ĐA', 'tên một khu phố ở Kyushu', 5),
('ふしみ', 'fushimi', '/audio/minna/bai05/fushimi.wav', 'noun', '伏見', 'PHỤC KIẾN', 'tên một khu phố ở Kyoto', 5),
('こうしえん', 'koushien', '/audio/minna/bai05/koshien.wav', 'noun', '甲子園', 'GIÁP TỬ VIÊN', 'tên một khu phố ở Osaka', 5),
('おおさかじょう', 'oosakajou', '/audio/minna/bai05/osakajo.wav', 'noun', '大阪城', 'ĐẠI PHẢN THÀNH', 'Lâu đài Osaka, một lâu đài nổi tiếng ở Osaka', 5); 