-- Bài 18
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(18, 'できます', 'dekimasu', 'audio/minna/bai18/dekimasu.mp3', '', '', '', 'có thể'),
(18, 'あらいます', 'araimasu', 'audio/minna/bai18/araimasu.mp3', '', '洗います', 'TẨY', 'rửa'),
(18, 'ひきます', 'hikimasu', 'audio/minna/bai18/hikimasu.mp3', '', '弾きます', 'ĐÀN, ĐẠN', 'chơi (nhạc cụ)'),
(18, 'うたいます', 'utaimasu', 'audio/minna/bai18/utaimasu.mp3', '', '歌います', 'CA', 'hát'),
(18, 'あつめます', 'atsumemasu', 'audio/minna/bai18/atsumemasu.mp3', '', '集めます', 'TẬP', 'sưu tầm, thu thập'),
(18, 'すてます', 'sutemasu', 'audio/minna/bai18/sutemasu.mp3', '', '捨てます', 'XẢ', 'vứt, bỏ đi'),
(18, 'かえます', 'kaemasu', 'audio/minna/bai18/kaemasu.mp3', '', '換えます', 'HOÁN', 'đổi'),
(18, 'うんてんします', 'untenshimasu', 'audio/minna/bai18/untenshimasu.mp3', '', '運転します', 'VẬN CHUYỂN', 'lái'),
(18, 'よやくします', 'yoyakushimasu', 'audio/minna/bai18/yoyakushimasu.mp3', '', '予約します', 'DỰ ƯỚC', 'đặt chỗ, đặt trước'),
(18, 'けんがくします', 'kengakushimasu', 'audio/minna/bai18/kengakushimasu.mp3', '', '見学します', 'KIẾN HỌC', 'thăm quan với mục đích học tập'),
(18, 'ピアノ', 'piano', 'audio/minna/bai18/k_piano.mp3', '', '', '', 'đàn Piano'),
(18, '―メートル', '～meｰtoru', 'audio/minna/bai18/k_meetoru.mp3', '', '', '', '―　mét'),
(18, 'こくさい～', 'kokusai～', 'audio/minna/bai18/kokusai.mp3', '', '国際～', 'QUỐC TẾ ~', 'quốc tế'),
(18, 'げんきん', 'genkin', 'audio/minna/bai18/genkin.mp3', '', '現金', 'HIỆN KIM', 'tiền mặt'),
(18, 'しゅみ', 'shumi', 'audio/minna/bai18/syumi.mp3', '', '趣味', 'THÚ VỊ', 'sở thích, thú vui'),
(18, 'にっき', 'nikki', 'audio/minna/bai18/nikki.mp3', '', '日記', 'NHẬT KÝ', 'nhật ký'),
(18, '[お]いのり', '[o]inori', 'audio/minna/bai18/oinori.mp3', '', '[お]祈り', 'KỲ', 'việc cầu nguyện (～をします：cầu nguyện)'),
(18, 'かちょう', 'kachou', 'audio/minna/bai18/kachou.mp3', '', '課長', 'KHOA TRƯỞNG', 'tổ trưởng'),
(18, 'ぶちょう', 'buchou', 'audio/minna/bai18/buchou.mp3', '', '部長', 'BỘ TRƯỞNG', 'trưởng phòng'),
(18, 'しゃちょう', 'shachou', 'audio/minna/bai18/shachou.mp3', '', '社長', 'XÃ TRƯỞNG', 'giám đốc'),
(18, 'どうぶつ', 'doubutsu', 'audio/minna/bai18/doubutsu.mp3', '', '動物', 'ĐỘNG VẬT', 'động vật'),
(18, 'うま', 'uma', 'audio/minna/bai18/uma.mp3', '', '馬', 'MÃ���', 'ngựa'),
(18, 'へえ', 'hee', 'audio/minna/bai18/hee.mp3', '', '', '', 'thế à!'),
(18, 'それはおもしろいですね。', 'sorehaomoshiroidesune｡', 'audio/minna/bai18/sorehaomoshiroidesune.mp3', '', '', '', 'Hay thật nhỉ.'),
(18, 'なかなか', 'nakanaka', 'audio/minna/bai18/nakanaka.mp3', '', '', '', 'khó mà~, không dễ, mãi mà (dùng với thể phủ định)'),
(18, 'ぼくじょう', 'bokujou', 'audio/minna/bai18/bokujou.mp3', '', '牧場', 'MỤC TRƯỜNG', 'trang trại chăn nuôi'),
(18, 'ほんとうですか。', 'hontoudesuka｡', 'audio/minna/bai18/hontoudesuka.mp3', '', '', '', 'Thật không ạ?'),
(18, 'ぜひ', 'zehi', 'audio/minna/bai18/zehi.mp3', '', '', '', 'nhất định, rất'),
(18, 'ビートルズ', 'biｰtoruzu', 'audio/minna/bai18/bitoruzu.wav', '', '', '', 'Beatles, một băng nhạc nỗi tiếng nước Anh');