-- Bài 41
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(41, 'いただきます', 'itadakimasu', 'audio/minna/bai41/itadakimasu.mp3', '', '', '', 'nhận (khiêm nhường ngữ củaもらいます)'),
(41, 'くださいます', 'kudasaimasu', 'audio/minna/bai41/kudasaimasu.mp3', '', '', '', 'Cho, tặng (tôi) (tôn kính ngữ củaくれます)'),
(41, 'やります', 'yarimasu', 'audio/minna/bai41/yarimasu.mp3', '', '', '', 'cho, tặng (dùng với người dưới hoặc bằng vai)'),
(41, 'よびます', 'yobimasu', 'audio/minna/bai41/yobimasu.mp3', '', '呼びます', 'HÔ', 'mời'),
(41, 'とりかえます', 'torikaemasu', 'audio/minna/bai41/torikaemasu.mp3', '', '取り替えます', 'THỦ THẾ', 'đổi, thay'),
(41, 'しんせつにします', 'shinsetsunishimasu', 'audio/minna/bai41/shinsetsunishimasu.mp3', '', '親切にします', 'THÂN THIẾT', 'giúp đỡ, đối xử thân thiện'),
(41, 'かわいい', 'kawaii', 'audio/minna/bai41/kawaii.mp3', '', '', '', 'xinh, đáng yêu'),
(41, 'おいわい', 'oiwai', 'audio/minna/bai41/oiwai.mp3', '', 'お祝い', 'CHÚC', 'mừng, quà mừng (～をします：mừng)'),
(41, 'おとしだま', 'otoshidama', 'audio/minna/bai41/otoshidama.mp3', '', 'お年玉', 'NIÊN NGỌC', 'tiền mừng tuổi'),
(41, '[お]みまい', '［o］mimai', 'audio/minna/bai41/omimai.mp3', '', '[お]見舞い', 'KIẾN VŨ', 'thăm người ốm'),
(41, 'きょうみ', 'kyoumi', 'audio/minna/bai41/kyoumi.mp3', '', '興味', 'HƯNG VỊ', 'sở thích, quan tâm（[コンピューターに]　～が　あります：quan tâm đến [máy tính]）'),
(41, 'じょうほう', 'jouhou', 'audio/minna/bai41/jouhou.mp3', '', '情報', 'TÌNH BÁO', 'thông tin'),
(41, 'ぶんぽう', 'bunpou', 'audio/minna/bai41/bunpou.mp3', '', '文法', 'VĂN PHÁP', 'ngữ pháp'),
(41, 'はつおん', 'hatsuon', 'audio/minna/bai41/hatsuon.mp3', '', '発音', 'PHÁT ÂM', 'phát âm'),
(41, 'さる', 'saru', 'audio/minna/bai41/saru.mp3', '', '猿', 'VIÊN', 'con khỉ'),
(41, 'えさ', 'esa', 'audio/minna/bai41/esa.mp3', '', '', '', 'đồ ăn cho động vật, mồi'),
(41, 'おもちゃ', 'omocha', 'audio/minna/bai41/omocha.mp3', '', '', '', 'đồ chơi'),
(41, 'えほん', 'ehon', 'audio/minna/bai41/ehon.mp3', '', '', '', 'quyển truyện tranh'),
(41, 'えはがき', 'ehagaki', 'audio/minna/bai41/ehagaki.mp3', '', '絵はがき', 'HỘI', 'bưu ảnh'),
(41, 'ドライバー', 'doraiba-', 'audio/minna/bai41/k_doraibaa.mp3', '', '', '', 'cái tua-vít'),
(41, 'ハンカチ', 'hankachi', 'audio/minna/bai41/k_hankachi.mp3', '', '', '', 'khăn mùi xoa, khăn tay'),
(41, 'くつした', 'kutsushita', 'audio/minna/bai41/kutsushita.mp3', '', '靴下', 'NGOA HẠ', 'cái tất'),
(41, 'てぶくろ', 'tebukuro', 'audio/minna/bai41/tebukuro.mp3', '', '手袋', 'THỦ ĐẠI', 'cái găng tay'),
(41, 'ゆびわ', 'yubiwa', 'audio/minna/bai41/yubiwa.mp3', '', '指輪', 'CHỈ LUÂN', 'cái nhẫn'),
(41, 'バッグ', 'baggu', 'audio/minna/bai41/k_baggu.mp3', '', '', '', 'cái túi (bag)'),
(41, 'そふ', 'sofu', 'audio/minna/bai41/sofu.mp3', '', '祖父', 'TỔ PHỤ', 'ông (dùng với bản thân)'),
(41, 'そぼ', 'sobo', 'audio/minna/bai41/sobo.mp3', '', '祖母', 'TỔ MẪU', 'bà (dùng với bản thân)'),
(41, 'まご', 'mago', 'audio/minna/bai41/mago.mp3', '', '孫', 'TÔN', 'cháu'),
(41, 'おじ', 'oji', 'audio/minna/bai41/oji.mp3', '', '', '', 'chú, cậu, bác (dùng với bản thân)'),
(41, 'おじさん', 'ojisan', 'audio/minna/bai41/ojisan.mp3', '', '', '', 'Chú, cậu, bác (dùng với người khác)'),
(41, 'おば', 'oba', 'audio/minna/bai41/oba.mp3', '', '', '', 'cô, dì, bác (dùng với bản thân)'),
(41, 'おばさん', 'obasan', 'audio/minna/bai41/obasan.mp3', '', '', '', 'cô, dì, bác (dùng với người khác)'),
(41, 'おととし', 'ototoshi', 'audio/minna/bai41/ototoshi.mp3', '', '', '', 'năm kia'),
(41, 'はあ', 'haa', 'audio/minna/bai41/haa.mp3', '', '', '', 'à, ồ'),
(41, 'もうしわけありません', 'moushiwakearimasen', 'audio/minna/bai41/moushiwakearimasen.mp3', '', '申し訳ありません。', 'THÂN DỊCH', 'Xin lỗi.'),
(41, 'あずかります', 'azukarimasu', 'audio/minna/bai41/azukarimasu.mp3', '', '預かります', 'DỰ', 'giữ, giữ hộ, giữ cho'),
(41, 'せんじつ', 'senjitsu', 'audio/minna/bai41/senjitsu.mp3', '', '先日', 'TIÊN NHẬT', 'hôm trước, mấy hôm trước'),
(41, 'たすかります', 'tasukarimasu', 'audio/minna/bai41/tasukarimasu.mp3', '', '助かります', 'TRỢ', 'may có anh/ chị giúp'),
(41, 'むかしばなし', 'mukashibanashi', 'audio/minna/bai41/mukashibanashi.wav', '', '昔話', 'TÍCH THOẠI', 'chuyện cổ tích'),
(41, 'ある', 'aru', 'audio/minna/bai41/aru.wav', '', '', '', '～có ~, một ~'),
(41, 'おとこ', 'otoko', 'audio/minna/bai41/otoko.wav', '', '男', 'NAM', 'người đàn ông, nam giới'),
(41, 'こどもたち', 'kodomotachi', 'audio/minna/bai41/kodomotachi.wav', '', '子供たち', 'TỬ CUNG', 'trẻ em, trẻ con, bọn trẻ'),
(41, 'いじめます', 'ijimemasu', 'audio/minna/bai41/ijimemasu.wav', '', '', '', 'bắt nạt'),
(41, 'かめ', 'kame', 'audio/minna/bai41/kame.wav', '', '', '', 'con rùa'),
(41, 'たすけます', 'tasukemasu', 'audio/minna/bai41/tasukemasu.wav', '', '助けます', 'TRỢ', 'giúp, giúp đỡ'),
(41, '「お」しろ', '「o」shiro', 'audio/minna/bai41/oshiro.wav', '', '[お]城', 'THÀNH', 'lâu đài, thành'),
(41, 'おひめさま', 'ohimesama', 'audio/minna/bai41/ohimesama.wav', '', 'お姫様', 'CƠ DẠNG', 'công chúa'),
(41, 'たのしく', 'tanoshiku', 'audio/minna/bai41/tanoshiku.wav', '', '楽しく', 'LẠC/NHẠC', 'vui'),
(41, 'くらします', 'kurashimasu', 'audio/minna/bai41/kurashimasu.wav', '', '暮らします', 'MỘ', 'sống, sinh hoạt'),
(41, 'りく', 'riku', 'audio/minna/bai41/riku.wav', '', '陸', 'LỤC', 'đất liền, lục địa'),
(41, 'すると', 'suruto', 'audio/minna/bai41/suruto.wav', '', '', '', 'thế rồi, sau đó'),
(41, 'けむり', 'kemuri', 'audio/minna/bai41/kemuri.wav', '', '煙', 'YÊN', 'khói'),
(41, 'まっしろ「な」', 'masshiro「na」', 'audio/minna/bai41/masshiro.wav', '', '真っ白[な]', 'CHÂN BẠCH', 'trắng toát, trắng ngần'),
(41, 'なかみ', 'nakami', 'audio/minna/bai41/nakami.wav', '', '中身', 'TRUNG THÂN', 'nội dung, cái ở bên trong');