-- Bài 14
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(14, 'つけます', 'tsukemasu', '/audio/minna/bai14/tsukemasu.mp3', 'verb', NULL, NULL, 'bật (điện, máy điều hòa)'),
(14, 'けします', 'keshimasu', '/audio/minna/bai14/keshimasu.mp3', 'verb', '消します', 'TIÊU', 'tắt (điện, máy điều hòa)'),
(14, 'あけます', 'akemasu', '/audio/minna/bai14/akemasu.mp3', 'verb', '開けます', 'KHAI', 'mở (cửa, cửa sổ)'),
(14, 'しめます', 'shimemasu', '/audio/minna/bai14/shimemasu.mp3', 'verb', '閉めます', 'BẾ', 'đóng (cửa, cửa sổ)'),
(14, 'いそぎます', 'isogimasu', '/audio/minna/bai14/isogimasu.mp3', 'verb', '急ぎます', 'CẤP', 'vội, gấp'),
(14, 'まちます', 'machimasu', '/audio/minna/bai14/machimasu.mp3', 'verb', '待ちます', 'ĐÃI', 'đợi, chờ'),
(14, 'とめます', 'tomemasu', '/audio/minna/bai14/tomemasu.mp3', 'verb', '止めます', 'CHỈ', 'dừng (băng, ôt ô), đỗ (ôtô)'),
(14, '[みぎへ～] まがります', '[migihe～] magarimasu', '/audio/minna/bai14/magarimasu.mp3', 'verb', '[右へ～]曲がります', 'HỮU KHÚC', 'rẽ, quẹo [phải]'),
(14, 'もちます', 'mochimasu', '/audio/minna/bai14/mochimasu.mp3', 'verb', '持ちます', 'TRÌ', 'mang, cầm'),
(14, 'とります', 'torimasu', '/audio/minna/bai14/torimasu.mp3', 'verb', '取ります', 'THỦ', 'lấy (muối)'),
(14, 'てつだいます', 'tetsudaimasu', '/audio/minna/bai14/tetsudaimasu.mp3', 'verb', '手伝います', 'THỦ TRUYỀN', 'giúp (làm việc)'),
(14, 'よびます', 'yobimasu', '/audio/minna/bai14/yobimasu.mp3', 'verb', '呼びます', 'HÔ', 'gọi (taxi, tên)'),
(14, 'はなします', 'hanashimasu', '/audio/minna/bai14/hanashimasu.mp3', 'verb', '話します', 'THOẠI', 'nói, nói chuyện'),
(14, 'みせます', 'misemasu', '/audio/minna/bai14/misemasu.mp3', 'verb', '見せます', 'KIẾN', 'cho xem, trình'),
(14, '[じゅうしょを～]おしえます', '[juushowo～]oshiemasu', '/audio/minna/bai14/oshiemasu.mp3', 'verb', '[住所を～]教えます', 'TRÚ SỞ GIÁO', 'nói, cho biết [địa chỉ]'),
(14, 'はじめます', 'hajimemasu', '/audio/minna/bai14/hajimemasu.mp3', 'verb', '始めます', 'THỦY', 'bắt đầu'),
(14, '[あめが～] ふります', '[amega～] furimasu', '/audio/minna/bai14/furimasu.mp3', 'verb', '[雨が～]降ります', 'VŨ GIÁNG/ HÀNG', 'rơi [mưa, tuyết~]'),
(14, 'コピーします', 'kopiｰshimasu', '/audio/minna/bai14/k_kopyyshimasu.mp3', 'verb', NULL, NULL, 'copy'),
(14, 'エアコン', 'eakon', '/audio/minna/bai14/k_eakon.mp3', 'noun', NULL, NULL, 'máy điều hòa'),
(14, 'パスポート', 'pasupoｰto', '/audio/minna/bai14/k_pasupooto.mp3', 'noun', NULL, NULL, 'hộ chiếu'),
(14, 'なまえ', 'namae', '/audio/minna/bai14/namae.mp3', 'noun', '名前', 'DANH TIỀN', 'tên'),
(14, 'じゅうしょ', 'juusho', '/audio/minna/bai14/juusyo.mp3', 'noun', '住所', 'TRÚ SỞ', 'địa chỉ'),
(14, 'ちず', 'chizu', '/audio/minna/bai14/chizu.mp3', 'noun', '地図', 'ĐỊA ĐỒ', 'bản đồ'),
(14, 'しお', 'shio', '/audio/minna/bai14/shio.mp3', 'noun', '塩', 'DIÊM', 'muối'),
(14, 'さとう', 'satou', '/audio/minna/bai14/satou.mp3', 'noun', '砂糖', 'SA ĐƯỜNG', 'đường'),
(14, 'よみかた', 'yomikata', '/audio/minna/bai14/yomikata.mp3', 'noun', '読み方', 'ĐỘC PHƯƠNG', 'cách đọc'),
(14, '～かた', '～kata', '/audio/minna/bai14/kata.mp3', 'suffix', '～方', 'PHƯƠNG', 'cách ~'),
(14, 'ゆっくり', 'yukkuri', '/audio/minna/bai14/yukkuri.mp3', 'adverb', NULL, NULL, 'chậm, thong thả, thoải mái'),
(14, 'すぐ', 'sugu', '/audio/minna/bai14/sugu.mp3', 'adverb', NULL, NULL, 'ngay, lập tức'),
(14, 'また', 'mata', '/audio/minna/bai14/mata.mp3', 'adverb', NULL, NULL, 'lại (~đến)'),
(14, 'あとで', 'atode', '/audio/minna/bai14/atode.mp3', 'adverb', NULL, NULL, 'sau'),
(14, 'もう　すこし', 'mou sukoshi', '/audio/minna/bai14/mousukoshi.mp3', 'adverb', 'もう少し', 'THIẾU', 'thêm một chút nữa thôi'),
(14, 'もう～', 'mou～', '/audio/minna/bai14/mou.mp3', 'adverb', NULL, NULL, 'thêm~'),
(14, 'いいですよ。', 'iidesuyo｡', '/audio/minna/bai14/iidesuyo.mp3', 'phrase', NULL, NULL, 'Được chứ./được ạ.'),
(14, 'さあ', 'saa', '/audio/minna/bai14/saa.mp3', 'interjection', NULL, NULL, 'thôi,/nào'),
(14, 'あれ？', 'are?', '/audio/minna/bai14/are.mp3', 'interjection', NULL, NULL, 'Ô!'),
(14, 'しんごうをみぎへまがってください', 'shingouwomigihemagattekudasai', '/audio/minna/bai14/shingouwomigihemagattekudasai.mp3', 'phrase', '信号を右へ曲がってください', 'TÍN HIỆU HỮU KHÚC', 'Anh/ Chị rẽ phải ở chổ đèn tín hiệu.'),
(14, 'まっすぐ', 'massugu', '/audio/minna/bai14/massugu.mp3', 'adverb', NULL, NULL, 'thẳng'),
(14, 'これでおねがいします。', 'koredeonegaishimasu｡', '/audio/minna/bai14/koredeonegaishimasu.mp3', 'phrase', 'これでお願いします。', 'NGUYỆN', 'Gởi anh tiền này.'),
(14, 'おつり', 'otsuri', '/audio/minna/bai14/otsuri.mp3', 'noun', 'お釣り', 'ĐIẾU', 'tiền lẻ'),
(14, 'うめだ', 'umeda', '/audio/minna/bai14/umeda.wav', 'noun', '梅田', 'MAI ĐIỀN', 'tên một địa phương ở Osaka'); 