-- Bài 40
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(40, 'かぞえます', 'kazoemasu', 'audio/minna/bai40/kazoemasu.mp3', '', '数えます', 'SỐ', 'đếm'),
(40, 'はかります', 'hakarimasu', 'audio/minna/bai40/hakarimasu.mp3', '', '測ります、量ります', 'TRẮC LƯỢNG', 'đo, cân'),
(40, 'たしかめます', 'tashikamemasu', 'audio/minna/bai40/tashikamemasu.mp3', '', '確かめます', 'XÁC', 'xác nhận'),
(40, '[サイズが～]あいます', '［saizuga～］aimasu', 'audio/minna/bai40/aimasu.mp3', '', '[サイズが～]合います', 'HỢP', 'vừa, hợp [kích thước ~]'),
(40, 'しゅっぱつします', 'shuppatsushimasu', 'audio/minna/bai40/syuppatsushimasu.mp3', '', '出発します', 'XUẤT PHÁT', 'xuất phát, khởi hành, đi'),
(40, 'とうちゃくします', 'touchakushimasu', 'audio/minna/bai40/touchakushimasu.mp3', '', '到着します', 'ĐÁO TRƯỚC', 'đến, đến nơi'),
(40, 'よいます', 'yoimasu', 'audio/minna/bai40/yoimasu.mp3', '', '酔います', 'TÚY', 'say'),
(40, 'きけん[な]', 'kiken［na］', 'audio/minna/bai40/kiken.mp3', '', '危険[な]', 'NGUY HIỂM', 'nguy hiểm'),
(40, 'ひつよう[な]', 'hitsuyou［na］', 'audio/minna/bai40/hitstuyou.mp3', '', '必要[な]', 'TẤT YẾU', 'cần thiết'),
(40, 'うちゅう', 'uchuu', 'audio/minna/bai40/uchuu.mp3', '', '宇宙', 'VŨ TRỤ', 'vũ trụ'),
(40, 'ちきゅう', 'chikyuu', 'audio/minna/bai40/chikyuu.mp3', '', '地球', 'ĐỊA CẦU', 'trái đất'),
(40, 'ぼうねんかい', 'bounenkai', 'audio/minna/bai40/bounenkai.mp3', '', '忘年会', 'VONG NIÊN HỘI', 'tiệc tất niên'),
(40, 'しんねんかい', 'shinnenkai', 'audio/minna/bai40/shinnenkai.mp3', '', '新年会', 'TÂN NIÊN HỘI', 'tiệc tân niên'),
(40, 'にじかい', 'nijikai', 'audio/minna/bai40/nijikai.mp3', '', '二次会', 'NHỊ THỨ HỘI', 'bữa tiệc thứ hai, “tăng hai”'),
(40, 'たいかい', 'taikai', 'audio/minna/bai40/taikai.mp3', '', '大会', 'ĐẠI HỘI', 'đại hội, cuộc thi'),
(40, 'マラソン', 'marason', 'audio/minna/bai40/k_marason.mp3', '', '', '', 'ma ra tông'),
(40, 'コンテスト', 'kontesuto', 'audio/minna/bai40/k_kontesuto.mp3', '', '', '', 'cuộc thi'),
(40, 'おもて', 'omote', 'audio/minna/bai40/omote.mp3', '', '表', 'BIỂU', 'phía trước, mặt trước'),
(40, 'うら', 'ura', 'audio/minna/bai40/ura.mp3', '', '裏', 'LÝ', 'phía sau, mặt sau'),
(40, 'へんじ', 'henji', 'audio/minna/bai40/henji.mp3', '', '返事', 'PHẢN SỰ', 'hồi âm, trả lời'),
(40, 'もうしこみ', 'moushikomi', 'audio/minna/bai40/moushikomi.mp3', '', '申し込み', 'THÂN VÀO', 'đăng ký'),
(40, 'ほんとう', 'hontou', 'audio/minna/bai40/hontou.mp3', '', '', '', 'thật'),
(40, 'まちがい', 'machigai', 'audio/minna/bai40/machigai.mp3', '', '', '', 'sai, lỗi'),
(40, 'きず', 'kizu', 'audio/minna/bai40/kizu.mp3', '', '傷', 'THƯƠNG', 'vết thương'),
(40, 'ズボン', 'zubon', 'audio/minna/bai40/k_zubon.mp3', '', '', '', 'cái quần'),
(40, 'ながさ', 'nagasa', 'audio/minna/bai40/nagasa.mp3', '', '長さ', 'TRƯỜNG', 'chiều dài'),
(40, 'おもさ', 'omosa', 'audio/minna/bai40/omosa.mp3', '', '重さ', 'TRỌNG', 'cân nặng, trọng lượng'),
(40, 'たかさ', 'takasa', 'audio/minna/bai40/takasa.mp3', '', '高さ', 'CAO', 'chiều cao'),
(40, 'おおきさ', 'ookisa', 'audio/minna/bai40/ookisa.mp3', '', '大きさ', 'ĐẠI', 'cỡ, kích thước'),
(40, '[－]びん', '［－］bin', 'audio/minna/bai40/bin.mp3', '', '[－]便', 'TIỆN', 'chuyến bay [―]'),
(40, '―ごう', '-gou', 'audio/minna/bai40/gou.mp3', '', '―号', 'HIỆU', 'số [―] (số hiệu đoàn tàu, cơn bão v.v.)'),
(40, '―こ', '-ko', 'audio/minna/bai40/ko.mp3', '', '－個', 'CÁ', 'cái, cục, viên (đơn vị đếm vật nhỏ)'),
(40, '―ほん（―ぽん、―ぼん）', '-hon（-pon、-bon）', 'audio/minna/bai40/hon.mp3', '', '―本', 'BỔN', '― cái (đơn vị đếm vật dài)'),
(40, '―はい（―ぱい、―ばい）', '-hai（-pai、-bai）', 'audio/minna/bai40/hai.mp3', '', '―杯', 'BÔI', '―chén, ―cốc'),
(40, '―キロ', '-kiro', 'audio/minna/bai40/k_kiro.mp3', '', '', '', '―ki-lô, ―cân'),
(40, '―グラム', '-guramu', 'audio/minna/bai40/k_guramu.mp3', '', '', '', '―gam'),
(40, '―センチ', '-senchi', 'audio/minna/bai40/senchi.wav', '', '', '', '―xăng-ti-mét'),
(40, '―ミリ', '-miri', 'audio/minna/bai40/miri.wav', '', '', '', '―mi-li-mét'),
(40, '～いじょう', '～ijou', 'audio/minna/bai40/ijou.mp3', '', '～以上', 'DĨ THƯỢNG', '~ trở lên, trên'),
(40, '～いか', '～ika', 'audio/minna/bai40/ika.mp3', '', '～以下', 'DĨ HẠ ~', 'trở xuống, dưới'),
(40, 'さあ', 'saa', 'audio/minna/bai40/saa.mp3', '', '', '', 'À…,Ồ… (dùng khi không rõ về điều gì đó)'),
(40, 'ゴッホ', 'gohho', 'audio/minna/bai40/gohho.wav', '', '', '', 'Van-gốc (1853-1890), danh họa người Hà Lan'),
(40, 'ゆきまつり', 'yukimatsuri', 'audio/minna/bai40/yukimatsuri.wav', '', '雪祭り', 'TUYẾT TẾ', 'Lễ hội tuyết (ở Sapporo)'),
(40, 'のぞみ', 'nozomi', 'audio/minna/bai40/nozomi.wav', '', '', '', 'tên một loại tàu Shinkansen'),
(40, 'ＪＬ', 'ＪＬ', 'audio/minna/bai40/jl.wav', '', '', '', 'hãng hàng không Nhật Bản (Japan Airlines)'),
(40, 'どうでしょうか。', 'doudeshouka', 'audio/minna/bai40/doudesyouka.wav', '', '', '', 'Thế nào? (cách nói lịch sự của どうですか)'),
(40, 'クラス', 'kurasu', 'audio/minna/bai40/k_kurasu.mp3', '', '', '', 'lớp học'),
(40, 'テスト', 'tesuto', 'audio/minna/bai40/k_tesuto.mp3', '', '', '', 'Bài kiểm tra, bài thi'),
(40, 'せいせき', 'seiseki', 'audio/minna/bai40/seiseki.mp3', '', '成績', 'THÀNH TÍCH', 'kết quả, thành tích'),
(40, 'ところで', 'tokorode', 'audio/minna/bai40/tokorode.mp3', '', '', '', 'nhân tiện đây'),
(40, 'いらっしゃいます', 'irasshaimasu', 'audio/minna/bai40/irassyaimasu.mp3', '', '', '', 'đến (tôn kính ngữ của きます)'),
(40, 'ようす', 'yousu', 'audio/minna/bai40/yousu.mp3', '', '様子', 'DẠNG TỬ', 'vẻ, tình hình'),
(40, 'じけん', 'jiken', 'audio/minna/bai40/jiken.wav', '', '事件', 'SỰ KIỆN', 'vụ án'),
(40, 'オートバイ', 'o-tobai', 'audio/minna/bai40/otobai.wav', '', '', '', 'xe máy'),
(40, 'ばくだん', 'bakudan', 'audio/minna/bai40/bakudan.wav', '', '爆弾', 'BỘC ĐẠN', 'bom'),
(40, 'つみます', 'tsumimasu', 'audio/minna/bai40/tsumimasu.wav', '', '積みます', 'TÍCH', 'chuyển lên, xếp hàng lên'),
(40, 'うんてんしゅ', 'untenshu', 'audio/minna/bai40/untenshu.wav', '', '運転手', 'VẬN CHUYỂN THỦ', 'lái xe'),
(40, 'はなれた', 'hanareta', 'audio/minna/bai40/hanareta.wav', '', '離れた', 'LY', 'xa cách, xa'),
(40, 'が', 'ga', 'audio/minna/bai40/ga.wav', '', '', '', 'nhưng'),
(40, 'きゅうに', 'kyuuni', 'audio/minna/bai40/kyuni.wav', '', '急に', 'CẤP', 'gấp, đột nhiên'),
(40, 'うごかします', 'ugokashimasu', 'audio/minna/bai40/ugokashimasu.wav', '', '動かします', 'ĐỘNG', 'khởi động, chạy'),
(40, 'いっしょうけんめい', 'isshoukenmei', 'audio/minna/bai40/isshokenmei.wav', '', '一生懸命', 'NHẤT SINH HUYỀN MỆNH', 'hết sức, chăm chỉ'),
(40, 'はんにん', 'hannin', 'audio/minna/bai40/hannin.wav', '', '犯人', 'PHẠM NHÂN', 'thủ phạm'),
(40, 'てに　いれます', 'teni　iremasu', 'audio/minna/bai40/teniiremasu.wav', '', '手に入れます', 'THỦ NHẬP', 'có được, lấy được, đoạt được'),
(40, 'いまでも', 'imademo', 'audio/minna/bai40/imademo.wav', '', '今でも', 'KIM', 'ngay cả bây giờ'),
(40, 'うわさします', 'uwasashimasu', 'audio/minna/bai40/uwasashimasu.wav', '', '', '', 'đồn đại');