-- Bài 38
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(38, 'そだてます', 'sodatemasu', 'audio/minna/bai38/sodatemasu.mp3', '', '育てます', 'DỤC', 'nuôi, trồng'),
(38, 'はこびます', 'hakobimasu', 'audio/minna/bai38/hakobimasu.mp3', '', '運びます', 'VẬN', 'chở, vận chuyển'),
(38, 'なくなります', 'nakunarimasu', 'audio/minna/bai38/nakunarimasu.mp3', '', '亡くなります', 'VONG', 'mất, qua đời (cách nói gián tiếp của しにます(bài 39))'),
(38, 'にゅういんします', 'nyuuinshimasu', 'audio/minna/bai38/nyuuinshimasu.mp3', '', '入院します', 'NHẬP VIỆN', 'nhập viện'),
(38, 'たいいんします', 'taiinshimasu', 'audio/minna/bai38/taiinshimasu.mp3', '', '退院します', 'THOÁI VIỆN', 'xuất viện'),
(38, '[でんげんを～] いれます', '［dengenwo～］　iremasu', 'audio/minna/bai38/iremasu.mp3', '', '[電源を～]入れます', 'ĐIỆN NGUYÊN NHẬP', 'bật [công tác điện, nguồn điện]'),
(38, '[でんげんを～]きります', '［dengenwo～］kirimasu', 'audio/minna/bai38/kirimasu.mp3', '', '[電源を～]切ります', 'ĐIỆN NGUYÊN THIẾT', 'tắt [công tác điện, nguồn điện]'),
(38, '[かぎを～]かけます', '［kagiwo～］kakemasu', 'audio/minna/bai38/kakemasu.mp3', '', '[かぎを～]掛けます', 'QUẢI', 'khóa [chìa khóa]'),
(38, 'きもちがいい', 'kimochigaii', 'audio/minna/bai38/kimochigaii.mp3', '', '気持ちがいい', 'KHÍ TRÌ', 'dễ chịu, thư giãn'),
(38, 'きもちがわるい', 'kimochigawarui', 'audio/minna/bai38/kimochigawarui.mp3', '', '気持ちが悪い', 'KHÍ TRÌ ÁC', 'khó chịu'),
(38, 'おおきな～', 'ookina～', 'audio/minna/bai38/ookina.mp3', '', '大きな～', 'ĐẠI', '~ to, ~ lớn'),
(38, 'ちいさな～', 'chiisana～', 'audio/minna/bai38/chiisasana.mp3', '', '小さな～', 'NHỎ ~', 'nhỏ, ~ bé'),
(38, 'あかちゃん', 'akachan', 'audio/minna/bai38/akachan.mp3', '', '赤ちゃん', 'XÍCH', 'em bé'),
(38, 'しょうがっこう', 'shougakkou', 'audio/minna/bai38/syougakkou.mp3', '', '小学校', 'TIỂU HỌC HIỆU', 'trường tiểu học'),
(38, 'ちゅうがっこう', 'chuugakkou', 'audio/minna/bai38/chuugakkou.mp3', '', '中学校', 'TRUNG HỌC HIỆU', 'trường trung học cơ sở'),
(38, 'えきまえ', 'ekimae', 'audio/minna/bai38/ekimae.mp3', '', '駅前', 'DỊCH TIỀN', 'khu vực trước nhà ga'),
(38, 'かいがん', 'kaigan', 'audio/minna/bai38/kaigan.mp3', '', '海岸', 'HẢI NGẠN', 'bờ biển'),
(38, 'うそ', 'uso', 'audio/minna/bai38/uso.mp3', '', '', '', 'nói dối, lời nói dối'),
(38, 'しょるい', 'shorui', 'audio/minna/bai38/syorui.mp3', '', '書類', 'THƯ LOẠI', 'giấy tờ, tài liệu'),
(38, 'でんげん', 'dengen', 'audio/minna/bai38/dengen.mp3', '', '電源', 'ĐIỆN NGUYÊN', 'nguồn điện, công tắc điện'),
(38, '～せい', '～sei', 'audio/minna/bai38/sei.mp3', '', '～製', 'CHẾ', 'sản xuất tại ~'),
(38, '[あ、]いけない。', '［a、］ikenai', 'audio/minna/bai38/ikenai.mp3', '', '', '', 'Ôi, hỏng mất rồi./ ôi, trời ơi.'),
(38, 'おさきに [しつれいします]', 'osakini　［shitsureishimasu］', 'audio/minna/bai38/osakini.mp3', '', 'お先に[失礼します]。', 'TIÊN THẤT LỄ', 'tôi xin phép về trước'),
(38, 'げんばくドーム', 'genbakudo-mu', 'audio/minna/bai38/genbakudo-mu.wav', '', '原爆ドーム', 'NGUYÊN BỘC', 'nhà vòm Bom nguyên tử, một di tích'),
(38, 'かいらん', 'kairan', 'audio/minna/bai38/kairan.mp3', '', '回覧', 'HỒI LÃM', 'tập thông báo'),
(38, 'けんきゅうしつ', 'kenkyuushitsu', 'audio/minna/bai38/kenkyuushitsu.mp3', '', '研究室', 'NGHIÊN CỨU THẤT', 'phòng nghiên cứu'),
(38, 'きちんと', 'kichinto', 'audio/minna/bai38/kichinto.mp3', '', '', '', 'nghiêm chỉnh, hẳn hoi, đứng đắn'),
(38, 'せいりします', 'seirishimasu', 'audio/minna/bai38/seirishimasu.mp3', '', '', '', 'sắp xếp'),
(38, '～という本', '～toiu本', 'audio/minna/bai38/osakini.mp3', '', '', 'BẢN', 'quyển sách có tên là ~'),
(38, '―さつ', '-satsu', 'audio/minna/bai38/satsu.mp3', '', '－冊', 'SÁCH', '(đơn vị đếm sách, v.v.)'),
(38, 'はんこ', 'hanko', 'audio/minna/bai38/hanko.mp3', '', '', '', 'con dấu, dấu'),
(38, '[はんこを～]おします', '［hankowo～］oshimasu', 'audio/minna/bai38/oshimasu.wav', '', '[はんこを～] 押します', 'ÁP', 'đóng [dấu]'),
(38, 'ふたご', 'futago', 'audio/minna/bai38/futago.wav', '', '双子', 'SONG TỬ', 'cặp sinh đôi'),
(38, 'しまい', 'shimai', 'audio/minna/bai38/shimai.wav', '', '姉妹', 'TỶ MUỘI', 'chị em'),
(38, '5ねんせい', '５nensei', 'audio/minna/bai38/gonensei.wav', '', '５年生', 'NIÊN SINH', 'học sinh năm thứ 5'),
(38, 'にています', 'niteimasu', 'audio/minna/bai38/niteimasu.wav', '', '似ています', 'TỰ', 'giống'),
(38, 'せいかく', 'seikaku', 'audio/minna/bai38/seikaku.wav', '', '性格', 'TÍNH CÁCH', 'tính cách, tính tình'),
(38, 'おとなしい', 'otonashii', 'audio/minna/bai38/otonashii.wav', '', '', '', 'hiền lành, trầm'),
(38, 'せわをします', 'sewawoshimasu', 'audio/minna/bai38/sewawoshimasu.wav', '', '世話をします', 'THẾ THOẠI', 'chăm sóc, giúp đỡ'),
(38, 'じかんがたちます', 'jikangatachimasu', 'audio/minna/bai38/jikangatachimasu.wav', '', '時間がたちます', 'THỜI GIAN', 'thời gian trôi đi'),
(38, 'だいすき「な」', 'daisuki「na」', 'audio/minna/bai38/daisuki.wav', '', '大好き[な]', 'ĐẠI HẢO', 'rất thích'),
(38, 'てん', 'ten', 'audio/minna/bai38/ten.wav', '', '―点', 'ĐIỂM ―', '- điểm'),
(38, 'クラス', 'kurasu', 'audio/minna/bai38/kurasu.wav', '', '', '', 'lớp học, lớp'),
(38, 'けんかします', 'kenkashimasu', 'audio/minna/bai38/kenkashimasu.wav', '', '', '', 'cãi nhau');