-- Bài 21
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(21, 'おもいます', 'omoimasu', 'audio/minna/bai21/omoimasu.mp3', '', '思います', 'TƯ', 'nghĩ'),
(21, 'いいます', 'iimasu', 'audio/minna/bai21/iimasu.mp3', '', '言います', 'NGÔN', 'nói'),
(21, 'たります', 'tarimasu', 'audio/minna/bai21/tarimasu.mp3', '', '足ります', 'TÚC', 'đủ'),
(21, 'かちます', 'kachimasu', 'audio/minna/bai21/kachimasu.mp3', '', '勝ちます', 'THẮNG', 'thắng'),
(21, 'まけます', 'makemasu', 'audio/minna/bai21/makemasu.mp3', '', '負けます', 'PHỤ', 'thua'),
(21, '[おまつりが～] あります', '[omatsuriga～] arimasu', 'audio/minna/bai21/arimasu.mp3', '', '[お祭りが～]あります', 'TẾ', 'được tổ chức, diễn ra, có [lễ hội~]'),
(21, 'やくにたちます', 'yakunitachimasu', 'audio/minna/bai21/yakunitachimasu.mp3', '', '役に立ちます', 'DỊCH LẬP', 'giúp ích'),
(21, 'むだ[な]', 'muda[na]', 'audio/minna/bai21/muda.mp3', '', '', '', 'lãng phí, vô ích'),
(21, 'ふべん[な]', 'fuben[na]', 'audio/minna/bai21/fuben.mp3', '', '不便[な]', 'BẤT TIỆN', 'bất tiện'),
(21, 'おなじ', 'onaji', 'audio/minna/bai21/onaji.mp3', '', '', '', 'giống'),
(21, 'すごい', 'sugoi', 'audio/minna/bai21/sugoi.mp3', '', '', '', 'ghê quá, giỏi quá'),
(21, 'しゅしょう', 'shushou', 'audio/minna/bai21/syusyou.mp3', '', '首相', 'THỦ TƯỚNG', 'thủ tướng'),
(21, 'だいとうりょう', 'daitouryou', 'audio/minna/bai21/daitouryou.mp3', '', '大統領', 'ĐẠI THỐNG LÃNH', 'tổng thống'),
(21, 'せいじ', 'seiji', 'audio/minna/bai21/seiji.mp3', '', '政治', 'CHÍNH TRỊ', 'chính trị'),
(21, 'ニュース', 'nyuｰsu', 'audio/minna/bai21/k_nyuusu.mp3', '', '', '', 'tin tức, bản tin'),
(21, 'スピーチ', 'supiｰchi', 'audio/minna/bai21/k_supiichi.mp3', '', '', '', 'bài diễn thuyết, bài phát biểu (～をします: diễn thuyết)'),
(21, 'しあい', 'shiai', 'audio/minna/bai21/shiai.mp3', '', '試合', 'THÍ HỢP', 'trận đấu'),
(21, 'アルバイト', 'arubaito', 'audio/minna/bai21/k_arubaito.mp3', '', '', '', 'công việc làm thêm (～をします: làm thêm)'),
(21, 'いけん', 'iken', 'audio/minna/bai21/iken.mp3', '', '意見', 'Ý KIẾN', 'ý kiến'),
(21, '[お]はなし', '[o]hanashi', 'audio/minna/bai21/ohanashi.mp3', '', '[お]話', 'THOẠI', 'I câu chuyện, bài nói chuyện (～をします: Nói chuyện)'),
(21, 'ユーモア', 'yuｰmoa', 'audio/minna/bai21/k_yuumoa.mp3', '', '', '', 'hài hước'),
(21, 'むだ', 'muda', 'audio/minna/bai21/muda.mp3', '', '', '', 'sự lãng phí'),
(21, 'デザイン', 'dezain', 'audio/minna/bai21/dezain.mp3', '', '', '', 'thiết kế'),
(21, 'こうつう', 'koutsuu', 'audio/minna/bai21/kotsuu.mp3', '', '交通', 'GIAO THÔNG', 'giao thông, đi lại'),
(21, 'ラッシュ', 'rasshu', 'audio/minna/bai21/rasshu.mp3', '', '', '', 'giờ cao điểm'),
(21, 'さいきん', 'saikin', 'audio/minna/bai21/saikin.mp3', '', '最近', 'TỐI CẬN', 'gần đây'),
(21, 'たぶん', 'tabun', 'audio/minna/bai21/tabun.mp3', '', '', '', 'chắc, có thể'),
(21, 'きっと', 'kitto', 'audio/minna/bai21/kitto.mp3', '', '', '', 'chắc chắn, nhất định'),
(21, 'ほんとうに', 'hontouni', 'audio/minna/bai21/hontouni.mp3', '', '', '', 'thật sự'),
(21, 'そんなに', 'sonnani', 'audio/minna/bai21/sonnani.mp3', '', '', '', '(không)~ lắm'),
(21, '～について', '～nitsuite', 'audio/minna/bai21/nitsuite.mp3', '', '', '', 'về~'),
(21, 'しかたが　ありません。', 'shikataga arimasen｡', 'audio/minna/bai21/shikatagaarimasen.mp3', '', '', '', 'Không có cách nào khác./đành chịu vậy/ Chuyện đã rồi.'),
(21, 'しばらくですね。', 'shibarakudesune｡', 'audio/minna/bai21/shibarakudesune.mp3', '', '', '', 'Lâu không gặp nhỉ.'),
(21, '～でものみませんか。', '～demonomimasenka｡', 'audio/minna/bai21/demonomimasenka.wav', '', '～でも飲みませんか。', 'ẤM', 'Anh/chị uống~ (cà-phê, rựu hay cái gì đó) nhé.'),
(21, 'みないと…。', 'minaito～｡', 'audio/minna/bai21/minaito.wav', '', '見ないと…。', 'KIẾN', 'Tôi phải xem'),
(21, 'もちろん', 'mochiron', 'audio/minna/bai21/mochiron.mp3', '', '', '', 'tất nhiên'),
(21, 'カンガルー', 'kangaruｰ', 'audio/minna/bai21/kangaru.wav', '', '', '', 'con kăng-gu-ru, chuột túi'),
(21, 'キャプテン・クック', 'kyaputen～kukku', 'audio/minna/bai21/kyapputenkukku.wav', '', '', '', 'thuyền trưởng Cook (James Cook 1728 – 79)');