-- Bài 16
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(16, '[でんしゃに～] のります', '[denshani～] norimasu', 'audio/minna/bai16/norimasu.mp3', '', '[電車に～]乗ります', 'ĐIỆN XA THỪA', 'đi, lên [tàu]'),
(16, '[でんしゃを～]おります', '[denshawo～]orimasu', 'audio/minna/bai16/orimasu.mp3', '', '[電車を～]降ります', 'ĐIỆN XA GIÁNG/HÀNG', 'xuống [tàu]'),
(16, 'のりかえます', 'norikaemasu', 'audio/minna/bai16/norikaemasu.mp3', '', '乗り換えます', 'THỪA HOÁN', 'chuyển, đổi (tàu)'),
(16, '[シャワーを～]あびます', '[shawaｰwo～]abimasu', 'audio/minna/bai16/abimasu.mp3', '', '[シャワーを～]浴びます', 'DỤC', 'tắm [vòi hoa sen]'),
(16, 'いれます', 'iremasu', 'audio/minna/bai16/iremasu.mp3', '', '入れます', 'NHẬP', 'cho vào, bỏ vào'),
(16, 'だします', 'dashimasu', 'audio/minna/bai16/dashimasu.mp3', '', '出します', 'XUẤT', 'lấy ra, rút (tiền)'),
(16, '[だいがくに～] はいります', '[daigakuni～] hairimasu', 'audio/minna/bai16/hairimasu.mp3', '', '[大学に～]入ります', 'ĐẠI HỌC NHẬP', 'vào, nhập học [đại học]'),
(16, '[だいがくを～] でます', '[daigakuwo～] demasu', 'audio/minna/bai16/demasu.mp3', '', '[大学を～]出ます', 'ĐẠI HỌC XUẤT', 'ra, tốt nghiệp [đại học]'),
(16, '[かいしゃを～]やめます', '[kaishawo～]yamemasu', 'audio/minna/bai16/yamemasu.mp3', '', '[会社を～]やめます', 'HỘI XÃ', 'bỏ, thôi [việc công ty]'),
(16, 'おします', 'oshimasu', 'audio/minna/bai16/oshimasu.mp3', '', '押します', 'ÁP', 'bấm, ấn (nút)'),
(16, 'わかい', 'wakai', 'audio/minna/bai16/wakai.mp3', '', '若い', 'NHƯỢC', 'trẻ'),
(16, 'ながい', 'nagai', 'audio/minna/bai16/nagai.mp3', '', '長い', 'TRƯỜNG', 'dài'),
(16, 'みじかい', 'mijikai', 'audio/minna/bai16/mijikai.mp3', '', '短い', 'ĐOẢN', 'ngắn'),
(16, 'あかるい', 'akarui', 'audio/minna/bai16/akarui.mp3', '', '明るい', 'MINH', 'sáng'),
(16, 'くらい', 'kurai', 'audio/minna/bai16/kurai.mp3', '', '暗い', 'ÁM', 'tối'),
(16, 'せが　たかい', 'sega takai', 'audio/minna/bai16/segatakai.mp3', '', '背が　高い', 'BỐI CAO', 'cao (dùng cho người)'),
(16, 'あたまが　いい', 'atamaga ii', 'audio/minna/bai16/atamagaii.mp3', '', '頭が　いい', 'ĐẦU', 'thông minh'),
(16, 'からだ', 'karada', 'audio/minna/bai16/karada.mp3', '', '体', 'THỂ', 'người, cơ thể'),
(16, 'あたま', 'atama', 'audio/minna/bai16/atama.mp3', '', '頭', 'ĐẦU', 'đầu'),
(16, 'かみ', 'kami', 'audio/minna/bai16/kami.mp3', '', '髪', 'PHÁT', 'giấy'),
(16, 'かお', 'kao', 'audio/minna/bai16/kao.mp3', '', '顔', 'NHAN', 'mặt'),
(16, 'め', 'me', 'audio/minna/bai16/me.mp3', '', '目', 'MỤC', 'mắt'),
(16, 'みみ', 'mimi', 'audio/minna/bai16/mimi.mp3', '', '耳', 'NHĨ', 'tai'),
(16, 'くち', 'kuchi', 'audio/minna/bai16/kuchi.mp3', '', '口', 'KHẨU', 'miệng'),
(16, 'は', 'ha', 'audio/minna/bai16/ha.mp3', '', '歯', 'XỈ', 'răng'),
(16, 'おなか', 'onaka', 'audio/minna/bai16/onaka.mp3', '', '', '', 'bụng'),
(16, 'あし', 'ashi', 'audio/minna/bai16/ashi.mp3', '', '足', 'TÚC', 'chân'),
(16, 'サービス', 'saｰbisu', 'audio/minna/bai16/k_saabisu.mp3', '', '', '', 'dịch vụ'),
(16, 'ジョギング', 'jogingu', 'audio/minna/bai16/k_jogingu.mp3', '', '', '', 'việc chạy bộ (~をします: chạy bộ)'),
(16, 'シャワー', 'shawaｰ', 'audio/minna/bai16/k_syawaa.mp3', '', '', '', 'vòi hoa sen'),
(16, 'みどり', 'midori', 'audio/minna/bai16/midori.mp3', '', '緑', 'LỤC', 'màu xanh lá cây'),
(16, '[お]てら', '[o]tera', 'audio/minna/bai16/otera.mp3', '', '[お]寺', 'TỰ', 'chùa'),
(16, 'じんじゃ', 'jinja', 'audio/minna/bai16/jinja.mp3', '', '神社', 'THẦN XÃ', 'đền thờ đạo thần'),
(16, 'りゅうがくせい', 'ryuugakusei', 'audio/minna/bai16/ryuugakusei.mp3', '', '留学生', 'LƯU HỌC SINH', 'lưu học sinh, du học sinh'),
(16, '一ばん', '～ban', 'audio/minna/bai16/ban.mp3', '', '一番', 'PHIÊN', 'số ―'),
(16, 'どうやって', 'douyatte', 'audio/minna/bai16/douyatte.mp3', '', '', '', 'làm thế nào~'),
(16, 'どの～', 'dono～', 'audio/minna/bai16/dono.mp3', '', '', '', 'cái nào~ (dùng với trường hợp từ ba thứ trở lên)'),
(16, '[いいえ、]まだまだです。', '[iie､]madamadadesu｡', 'audio/minna/bai16/iiemadamadadesu.wav', '', '', '', '[không,] tôi còn kém lắm.'),
(16, 'おひきだしですか', 'ohikidashidesuka', 'audio/minna/bai16/ohikidashidesuka.mp3', '', 'お引き出しですか', 'DẪN XUẤT', 'Anh/ chị rút tiền ạ?'),
(16, 'まず', 'mazu', 'audio/minna/bai16/mazu.mp3', '', '', '', 'trước hết, đầu tiên'),
(16, 'キャッシュカード', 'kyasshukaｰdo', 'audio/minna/bai16/k_kyasshukaado.mp3', '', '', '', 'thẻ ngân hàng, thẻ ATM'),
(16, 'あんしょうばんごう', 'anshoubangou', 'audio/minna/bai16/ansyoubangou.mp3', '', '暗証番号', 'ÁM CHỨNG PHIÊN HIỆU', 'mã số bí mật (mật khẩu)'),
(16, 'つぎに', 'tsugini', 'audio/minna/bai16/tsugini.mp3', '', '次に', 'THỨ', 'tiếp theo'),
(16, 'きんがく', 'kingaku', 'audio/minna/bai16/kingaku.mp3', '', '金額', 'KIM NGẠCH', 'số tiền, khoản tiền'),
(16, 'かくにん', 'kakunin', 'audio/minna/bai16/kakunin.mp3', '', '確認', 'XÁC NHẬN', 'sự xác nhận, sự kiểm tra (~します：xác nhận)'),
(16, 'ボタン', 'botan', 'audio/minna/bai16/k_botan.mp3', '', '', '', 'nút'),
(16, 'ＪＲ', 'JR', 'audio/minna/bai16/ja.wav', '', '', '', 'công ty đường sắt Nhật Bản'),
(16, 'アジア', 'ajia', 'audio/minna/bai16/ajia.wav', '', '', '', 'châu Á'),
(16, 'バンドン', 'bandon', 'audio/minna/bai16/bandon.wav', '', '', '', 'Bandung (ở Indonesia)'),
(16, 'ベラクルス', 'berakurusu', 'audio/minna/bai16/berakurusu.wav', '', '', '', 'Veracruz (ở Mexico)'),
(16, 'フランケン', 'furanken', 'audio/minna/bai16/furanken.wav', '', '', '', 'Franken (ở Đức)'),
(16, 'ベトナム', 'betonamu', 'audio/minna/bai16/betonamu.wav', '', '', '', 'Việt Nam'),
(16, 'フェ', '～', 'audio/minna/bai16/fue.wav', '', '', '', 'Huế'),
(16, 'だいがくまえ', 'daigakumae', 'audio/minna/bai16/daigakumae.wav', '', '大学前', 'ĐẠI HỌC TIỀN', 'tên một điểm dừng xe buýt (giả tưởng)');