-- Bài 7
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(7, 'きります', 'kirimasu', '/audio/minna/bai07/kirimasu.mp3', 'verb', '切ります', 'THIẾT', 'cắt'),
(7, 'おくります', 'okurimasu', '/audio/minna/bai07/okurimasu.mp3', 'verb', '送ります', 'TỐNG', 'gửi'),
(7, 'あげます', 'agemasu', '/audio/minna/bai07/agemasu.mp3', 'verb', NULL, NULL, 'cho, tặng'),
(7, 'もらいます', 'moraimasu', '/audio/minna/bai07/moraimasu.mp3', 'verb', NULL, NULL, 'nhận'),
(7, 'かします', 'kashimasu', '/audio/minna/bai07/kashimasu.mp3', 'verb', '貸します', 'THẢI', 'cho mượn, cho vay'),
(7, 'かります', 'karimasu', '/audio/minna/bai07/karimasu.mp3', 'verb', '借ります', 'TÁ', 'mượn, vay'),
(7, 'おしえます', 'oshiemasu', '/audio/minna/bai07/oshiemasu.mp3', 'verb', '教えます', 'GIÁO', 'dạy'),
(7, 'ならいます', 'naraimasu', '/audio/minna/bai07/naraimasu.mp3', 'verb', '習います', 'TẬP', 'học, tập'),
(7, '[でんわを～]かけます', '[denwawo～]kakemasu', '/audio/minna/bai07/kakemasu.mp3', 'verb', '[電話を～]かけます', 'ĐIỆN THOẠI', 'gọi [điện thoại]'),
(7, 'て', 'te', '/audio/minna/bai07/te.mp3', 'noun', '手', 'THỦ', 'tay'),
(7, 'はし', 'hashi', '/audio/minna/bai07/hashi.mp3', 'noun', NULL, NULL, 'đũa'),
(7, 'スプーン', 'supuｰn', '/audio/minna/bai07/k_supuun.mp3', 'noun', NULL, NULL, 'thìa'),
(7, 'ナイフ', 'naifu', '/audio/minna/bai07/k_naifu.mp3', 'noun', NULL, NULL, 'dao'),
(7, 'フォーク', '～ｰku', '/audio/minna/bai07/k_fooku.mp3', 'noun', NULL, NULL, 'nĩa'),
(7, 'はさみ', 'hasami', '/audio/minna/bai07/hasami.mp3', 'noun', NULL, NULL, 'kéo'),
(7, 'ファクス', '～kusu', '/audio/minna/bai07/k_fakkusu.mp3', 'noun', NULL, NULL, 'fax'),
(7, 'ワープロ', 'waｰpuro', '/audio/minna/bai07/k_waapuro.mp3', 'noun', NULL, NULL, 'máy đánh chữ'),
(7, 'パソコン', 'pasokon', '/audio/minna/bai07/k_pasokon.mp3', 'noun', NULL, NULL, 'máy vi tính cá nhân'),
(7, 'パンチ', 'panchi', '/audio/minna/bai07/k-panchi.mp3', 'noun', NULL, NULL, 'cái đục lỗ'),
(7, 'ホッチキス', 'hotchikisu', '/audio/minna/bai07/k_hocchikisu.mp3', 'noun', NULL, NULL, 'cái dập ghim'),
(7, 'セロテープ', 'seroteｰpu', '/audio/minna/bai07/k_seroteepu.mp3', 'noun', NULL, NULL, 'băng dính'),
(7, 'けしゴム', 'keshigomu', '/audio/minna/bai07/keshigomu.mp3', 'noun', NULL, NULL, 'cái tẩy'),
(7, 'かみ', 'kami', '/audio/minna/bai07/kami.mp3', 'noun', '紙', 'CHỈ', 'giấy'),
(7, 'はな', 'hana', '/audio/minna/bai07/hana.mp3', 'noun', '花', 'HOA', 'hoa'),
(7, 'シャツ', 'shatsu', '/audio/minna/bai07/k_syatsu.mp3', 'noun', NULL, NULL, 'áo sơ mi'),
(7, 'プレゼント', 'purezento', '/audio/minna/bai07/k_purezento.mp3', 'noun', NULL, NULL, 'quà tặng, tặng phẩm'),
(7, 'にもつ', 'nimotsu', '/audio/minna/bai07/nimotsu.mp3', 'noun', '荷物', 'HÀ VẬT', 'đồ đạc, hành lý'),
(7, 'おかね', 'okane', '/audio/minna/bai07/okane.mp3', 'noun', 'お金', 'KIM', 'tiền'),
(7, 'きっぷ', 'kippu', '/audio/minna/bai07/kippu.mp3', 'noun', '切符', 'THIẾT PHÙ', 'vé'),
(7, 'クリスマス', 'kurisumasu', '/audio/minna/bai07/k_kurisumasu.mp3', 'noun', NULL, NULL, 'Giáng sinh'),
(7, 'ちち', 'chichi', '/audio/minna/bai07/chichi.mp3', 'noun', '父', 'PHỤ', 'bố (dùng khi nói về bố mình)'),
(7, 'はは', 'haha', '/audio/minna/bai07/haha.mp3', 'noun', '母', 'MẪU', 'mẹ (dùng khi nói về mẹ mình)'),
(7, 'おとうさん', 'otousan', '/audio/minna/bai07/otousan.mp3', 'noun', 'お父さん', 'PHỤ', 'bố (dùng khi nói về bố người khác và dùng khi xưng hô với bố mình)'),
(7, 'おかあさん', 'okaasan', '/audio/minna/bai07/okaasan.mp3', 'noun', 'お母さん', 'MẪU', 'mẹ (dùng khi nói về mẹ người khác và dùng khi xưng hô với mẹ mình)'),
(7, 'もう', 'mou', '/audio/minna/bai07/mou.mp3', 'adverb', NULL, NULL, 'đã, rồi'),
(7, 'まだ', 'mada', '/audio/minna/bai07/mada.mp3', 'adverb', NULL, NULL, 'chưa'),
(7, 'これから', 'korekara', '/audio/minna/bai07/korekara.mp3', 'adverb', NULL, NULL, 'từ bây giờ, sau đây'),
(7, '[～、]すてきですね。', '[～､]sutekidesune｡', '/audio/minna/bai07/sutekidesune.mp3', 'phrase', NULL, NULL, '[~] hay nhỉ./ đẹp nhỉ.'),
(7, 'ごめんください。', 'gomenkudasai｡', '/audio/minna/bai07/gomenkudasai.mp3', 'phrase', NULL, NULL, 'Xin lỗi, có ai ở nhà không?/ Tôi có thể vào được chứ?'),
(7, 'いらっしゃい。', 'irasshai｡', '/audio/minna/bai07/irasshai.wav', 'phrase', NULL, NULL, 'Chào mừng anh/chị đã đến chơi.'),
(7, 'どうぞ　おあがりください。', 'douzo oagarikudasai｡', '/audio/minna/bai07/dozooagarikudasai.wav', 'phrase', NULL, NULL, 'Mời anh/chị vào.'),
(7, 'しつれいします。', 'shitsureishimasu｡', '/audio/minna/bai07/shitsureishimasu.mp3', 'phrase', '失礼します。', 'THẤT LỄ', 'Xin thất lễ'),
(7, '[～は]いかがですか。', '[～ha]ikagadesuka｡', '/audio/minna/bai07/ikagadesuka.mp3', 'phrase', NULL, NULL, 'Anh/chị dùng [~] có được không?'),
(7, 'いただきます。', 'itadakimasu｡', '/audio/minna/bai07/itadakimasu.mp3', 'phrase', NULL, NULL, 'Xin nhận ~. (cách nói dùng trước khi ăn hoặc uống)'),
(7, 'りょこう', 'ryokou', '/audio/minna/bai07/ryokou.mp3', 'noun', '旅行', 'LỮ HÀNH', 'du lịch, chuyến du lịch (～をします: đi du lịch)'),
(7, 'おみやげ', 'omiyage', '/audio/minna/bai07/omiyage.mp3', 'noun', 'お土産', 'THỔ SẢN', 'quà'),
(7, 'ヨーロッパ', 'yoｰroppa', '/audio/minna/bai07/yoroppa.wav', 'noun', NULL, NULL, 'Châu Âu'),
(7, 'スペイン', 'supein', '/audio/minna/bai07/supein.wav', 'noun', NULL, NULL, 'Tây Ban Nha');