-- Bài 19
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(19, '[やまに～]のぼります', '[yamani～]noborimasu', 'audio/minna/bai19/noborimasu.mp3', '', '[山に～]登ります', 'SƠN ĐĂNG', 'leo [núi]'),
(19, '[ホテルに～]とまります', '[hoteruni～]tomarimasu', 'audio/minna/bai19/tomarimasu.mp3', '', '[ホテルに～]泊まります', 'BẠC', 'trọ [ở khách sạn]'),
(19, 'そうじします', 'soujishimasu', 'audio/minna/bai19/soujishimasu.mp3', '', '掃除します', 'TẢO TRỪ', 'dọn vệ sinh'),
(19, 'せんたくします', 'sentakushimasu', 'audio/minna/bai19/sentakushimasu.mp3', '', '洗濯します', 'TẨY TRẠC', 'giặt'),
(19, 'れんしゅうします', 'renshuushimasu', 'audio/minna/bai19/rensyushimasu.mp3', '', '練習します', 'LUYỆN TẬP', 'luyện tập, thực hành'),
(19, 'なります', 'narimasu', 'audio/minna/bai19/narimasu.mp3', '', '', '', 'trở thành, trở nên'),
(19, 'ねむい', 'nemui', 'audio/minna/bai19/nemui.mp3', '', '眠い', 'MIÊN', 'buồn ngủ'),
(19, 'つよい', 'tsuyoi', 'audio/minna/bai19/tsuyoi.mp3', '', '強い', 'CƯỜNG', 'mạnh'),
(19, 'よわい', 'yowai', 'audio/minna/bai19/yowai.mp3', '', '弱い', 'NHƯỢC', 'yếu'),
(19, 'ちょうしが　いい', 'choushiga ii', 'audio/minna/bai19/choushigaii.mp3', '', '調子が　いい', 'ĐIỀU TỬ', 'trong tình trạng tốt'),
(19, 'ちょうしが　わるい', 'choushiga warui', 'audio/minna/bai19/choushigawarui.mp3', '', '調子が　わるい', 'ĐIỀU TỬ', 'trong tình trạng xấu'),
(19, 'ちょうし', 'choushi', 'audio/minna/bai19/choushi.mp3', '', '調子', 'ĐIỀU TỬ', 'tình trạng, trạng thái'),
(19, 'ゴルフ', 'gorufu', 'audio/minna/bai19/k_gorufu.mp3', '', '', '', 'gôn (～をします:chơi gôn)'),
(19, 'すもう', 'sumou', 'audio/minna/bai19/sumou.mp3', '', '相撲', 'TƯƠNG PHÁC', 'vật Sumo'),
(19, 'パチンコ', 'pachinko', 'audio/minna/bai19/k_pachinko.mp3', '', '', '', 'trò chơi Pachinko (～をします: chơi trò chơi Pachinko)'),
(19, 'おちゃ', 'ocha', 'audio/minna/bai19/ocha.mp3', '', 'お茶', 'TRÀ', 'trà (nói chung)'),
(19, 'ひ', 'hi', 'audio/minna/bai19/hi.mp3', '', '日', 'NHẬT', 'ngày'),
(19, 'いちど', 'ichido', 'audio/minna/bai19/ichido.mp3', '', '一度', 'NHẤT ĐỘ', 'một lần'),
(19, 'いちども', 'ichidomo', 'audio/minna/bai19/ichidomo.mp3', '', '一度も', 'NHẤT ĐỘ', 'chưa lần nào'),
(19, 'だんだん', 'dandan', 'audio/minna/bai19/dandan.mp3', '', '', '', 'dần dần'),
(19, 'もうすぐ', 'mousugu', 'audio/minna/bai19/mousugu.mp3', '', '', '', 'sắp'),
(19, 'おかげさまで', 'okagesamade', 'audio/minna/bai19/okagesamade.mp3', '', '', '', 'cám ơn anh/ chị (dùng để bày tỏ sự cám ơn khi nhận được sự giúp đỡ của ai đó)'),
(19, 'かんぱい', 'kanpai', 'audio/minna/bai19/kanpai.mp3', '', '乾杯', 'CAN BỘI', 'nâng cốc!/cạn chén'),
(19, 'じつは', 'jitsuha', 'audio/minna/bai19/jitsuha.mp3', '', '実は', 'THỰC', 'thật ra là/sự tình là'),
(19, 'ダイエット', 'daietto', 'audio/minna/bai19/k_daietto.mp3', '', '', '', 'việc ăn kiêng, chế độ giảm cân (～をします:ăn kiêng)'),
(19, 'なんかいも', 'nankaimo', 'audio/minna/bai19/nankaimo.mp3', '', '何回も', 'HÀ HỒI', 'nhiều lần'),
(19, 'しかし', 'shikashi', 'audio/minna/bai19/shikashi.mp3', '', '', '', 'nhưng, tuy nhiên'),
(19, 'むり「な」', 'muri｢na｣', 'audio/minna/bai19/muri.mp3', '', '無理[な]', 'VÔ LÝ', 'không thể, quá sức'),
(19, 'からだにいい', 'karadaniii', 'audio/minna/bai19/karadaniii.mp3', '', '体にいい', 'THỂ', 'tốt cho sức khỏe'),
(19, 'ケーキ', 'keｰki', 'audio/minna/bai19/k_keeki.mp3', '', '', '', 'bánh ga-tô, bánh ngọt'),
(19, 'かつしかほくさい', 'katsushikahokusai', 'audio/minna/bai19/katsushikahokusai.wav', '', '葛飾北斎', 'CÁT SỨC BẮC TRAI', 'Katsushika Hokusai (1760-1849), một họa sĩ nổi tiếng thời Edo');