INSERT INTO vocabulary (word, romaji, audio, type, kanji, kanji_reading, meaning, lesson) VALUES
('わたし', 'watashi', '/audio/minna/bai01/watashi.mp3', NULL, NULL, NULL, 'tôi', 1),
('わたしたち', 'watashitachi', '/audio/minna/bai01/watashitachi.mp3', NULL, NULL, NULL, 'chúng tôi, chúng ta', 1),
('あなた', 'anata', '/audio/minna/bai01/anata.mp3', NULL, NULL, NULL, 'anh/ chị/ ông/ bà', 1),
('あのひと', 'anohito', '/audio/minna/bai01/anohito.mp3', NULL, 'あの人', 'NHÂN', 'người kia, người đó', 1),
('あのかた', 'anokata', '/audio/minna/bai01/anokata.mp3', NULL, 'あの方', 'PHƯƠNG', 'vị kia', 1),
('みなさん', 'minasan', '/audio/minna/bai01/minasan.mp3', NULL, '皆さん', 'GIAI', 'các anh chị, các ông bà, các bạn, quý vị', 1),
('～さん', '～san', '/audio/minna/bai01/san.mp3', NULL, NULL, NULL, 'anh, chị, ông, bà', 1),
('～ちゃん', '～chan', '/audio/minna/bai01/chan.mp3', NULL, NULL, NULL, '(hậu tố thêm vào sau tên của trẻ em thay cho ～さん)', 1),
('～くん', '～kun', '/audio/minna/bai01/kun.mp3', NULL, '～君', 'QUÂN', '(hậu tố thêm vào sau tên của em trai)', 1),
('～じん', '～jin', '/audio/minna/bai01/jin.mp3', NULL, '～人', 'NHÂN', 'người (nước)~', 1),
('せんせい', 'sensei', '/audio/minna/bai01/sensei.mp3', NULL, '先生', 'TIÊN SINH', 'thầy/ cô', 1),
('きょうし', 'kyoushi', '/audio/minna/bai01/kyoushi.mp3', NULL, '教師', 'GIÁO SƯ', 'giáo viên', 1),
('がくせい', 'gakusei', '/audio/minna/bai01/gakusei.mp3', NULL, '学生', 'HỌC SINH', 'học sinh, sinh viên', 1),
('かいしゃいん', 'kaishain', '/audio/minna/bai01/kaishain.mp3', NULL, '会社員', 'HỘI XÃ VIÊN', 'nhân viên công ty', 1),
('しゃいん', 'shain', '/audio/minna/bai01/syain.mp3', NULL, '社員', 'XÃ VIÊN', 'nhân viên công ty ~', 1),
('ぎんこういん', 'ginkouin', '/audio/minna/bai01/ginkouin.mp3', NULL, '銀行員', 'NGÂN HÀNH VIÊN', 'nhân viên ngân hàng', 1),
('いしゃ', 'isha', '/audio/minna/bai01/isya.mp3', NULL, '医者', 'Y GIẢ', 'bác sĩ', 1),
('けんきゅうしゃ', 'kenkyuusha', '/audio/minna/bai01/kenkyuusya.mp3', NULL, '研究者', 'NGHIÊN CỨU GIẢ', 'nhà nghiên cứu', 1),
('エンジニア', 'enjinia', '/audio/minna/bai01/enjinia.mp3', NULL, NULL, NULL, 'kỹ sư', 1),
('だいがく', 'daigaku', '/audio/minna/bai01/daigaku.mp3', NULL, '大学', 'ĐẠI HỌC', 'đại học, trường đại học', 1),
('びょういん', 'byouin', '/audio/minna/bai01/byouin.mp3', NULL, '病院', 'BỆNH VIỆN', 'bệnh viện', 1),
('でんき', 'denki', '/audio/minna/bai01/denki.mp3', NULL, '電気', 'ĐIỆN KHÍ', 'điện, đèn điện', 1),
('だれ（どなた）', 'dare(donata)', '/audio/minna/bai01/dare.mp3', NULL, NULL, NULL, 'ai (どなた là cách nói lịch sự của だれ, vị nào)', 1),
('―さい', '～sai', '/audio/minna/bai01/sai.mp3', NULL, '－歳', 'NHẤT TUẾ', '―tuổi', 1),
('なんさい', 'nansai', '/audio/minna/bai01/nansai.mp3', NULL, '何歳', 'HÀ TUẾ', 'mấy tuổi, bao nhiêu tuổi', 1),
('はい', 'hai', '/audio/minna/bai01/hai.mp3', NULL, NULL, NULL, 'vâng, dạ', 1),
('いいえ', 'iie', '/audio/minna/bai01/iie.mp3', NULL, NULL, NULL, 'không', 1),
('しつれいですが', 'shitsureidesuga', '/audio/minna/bai01/shitsureidesuga.wav', NULL, '失礼ですが', 'THẤT LỄ', 'xin lỗi,…', 1),
('おなまえは？', 'onamaeha?', '/audio/minna/bai01/onamaewa.wav', NULL, 'お名前は？', 'DANH TIỀN', 'Tên anh/chị là gì?', 1),
('はじめまして。', 'hajimemashite｡', '/audio/minna/bai01/hajimemashite.wav', NULL, '初めまして。', 'SƠ', 'Rất hân hạnh được gặp anh/chị', 1),
('どうぞよろしく[おねがいします]。', 'douzoyoroshiku[onegaishimasu]｡', '/audio/minna/bai01/dozoyoroshikuonegaishimasu.wav', NULL, NULL, NULL, 'Rất mong được sự giúp đỡ của anh/chị.', 1),
('こちらは～さんです。', 'kochiraha～sandesu｡', '/audio/minna/bai01/kochirawa.wav', NULL, NULL, NULL, 'Đây là anh/chị/ông/bà ~.', 1),
('～からきました。', '～karakimashita｡', '/audio/minna/bai01/karakimashita.wav', NULL, '～から来ました。', 'LAI', '(tôi) đến từ ~.', 1),
('アメリカ', 'amerika', '/audio/minna/bai01/amerika.wav', NULL, NULL, NULL, 'Mỹ', 1),
('イギリス', 'igirisu', '/audio/minna/bai01/igirisu.wav', NULL, NULL, NULL, 'Anh', 1),
('インド', 'indo～', '/audio/minna/bai01/indo.wav', NULL, NULL, NULL, 'Ấn Độ', 1),
('インドネシア', 'indoneshia', '/audio/minna/bai01/indoneshia.wav', NULL, NULL, NULL, 'Indonesia', 1),
('かんこく', 'kankoku', '/audio/minna/bai01/kankoku.wav', NULL, '韓国', 'HÀN QUỐC', 'Hàn Quốc', 1),
('タイ', 'tai', '/audio/minna/bai01/tai.wav', NULL, NULL, NULL, 'Thái Lan', 1),
('ちゅうごく', 'chuugoku', '/audio/minna/bai01/chuugoku.wav', NULL, '中国', 'TRUNG QUỐC', 'Trung Quốc', 1),
('ドイツ', 'doitsu', '/audio/minna/bai01/doitsu.wav', NULL, NULL, NULL, 'Đức', 1),
('にほん', 'nihon', '/audio/minna/bai01/nihon.wav', NULL, '日本', 'NHẬT BẢN', 'Nhật Bản', 1),
('フランス', 'furansu', '/audio/minna/bai01/furansu.wav', NULL, NULL, NULL, 'Pháp', 1),
('ブラジル', 'burajiru', '/audio/minna/bai01/burajiru.wav', NULL, NULL, NULL, 'Braxin', 1),
('さくらだいがく', 'sakuradaigaku', '/audio/minna/bai01/sakuradaigaku.wav', NULL, 'さくら大学', 'ĐẠI HỌC', 'Đại học Sakura(giả tưởng)', 1),
('ふじだいがく', 'fujidaigaku', '/audio/minna/bai01/fujidaigaku.wav', NULL, '富士大学', 'PHÚ SĨ ĐẠI HỌC', 'Đại học Phú Sĩ(giả tưởng)', 1),
('ＩＭＣ／パワーでんき／ブラジルエアー', 'IMC/pawaｰdenki/burajirueaｰ', '/audio/minna/bai01/imc.wav', NULL, NULL, NULL, 'tên các công ty (giả tưởng)', 1),
('ＡＫＣ', 'AKC', '/audio/minna/bai01/akc.wav', NULL, NULL, NULL, 'tên một tổ chức (giả tưởng)', 1),
('こうべびょういん', 'koubebyouin', '/audio/minna/bai01/koubebyouin.wav', NULL, '神戸病院', 'THẦN HỘ BỆNH VIỆN', 'tên một bệnh viện (giả tưởng)', 1);
