-- Bài 29
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(29, '[ドアが～]あきます', '［doaga～］akimasu', 'audio/minna/bai29/akimasu.mp3', '', '[ドアが～]開きます', 'KHAI', 'mở [cửa ~]'),
(29, '[ドアが～]しまります', '［doaga～］shimarimasu', 'audio/minna/bai29/shimarimasu.mp3', '', '[ドアが～]閉まります', 'BẾ', 'đóng [cửa ~]'),
(29, '[でんきが～] つきます', '［denkiga～］　tsukimasu', 'audio/minna/bai29/tsukimasu.mp3', '', '[電気が～]', 'ĐIỆN KHÍ', 'sáng [điện ~]'),
(29, '[でんきが～]きえます', '［denkiga～］kiemasu', 'audio/minna/bai29/kiemasu.mp3', '', '[電気が～]消えます', 'ĐIỆN KHÍ TIÊU', 'tắt [điện ~]'),
(29, '[みちが～]こみます', '［michiga～］komimasu', 'audio/minna/bai29/komimasu.mp3', '', '[道が～]込みます', 'ĐẠO VÀO', 'đông, tắc [đường ~]'),
(29, '[みちが～] すきます', '［michiga～］　sukimasu', 'audio/minna/bai29/sukimasu.mp3', '', '[道が～]', 'ĐẠO', 'vắng, thoáng [đường ~]'),
(29, '[いすが～]こわれます', '［isuga～］kowaremasu', 'audio/minna/bai29/kowaremasu.mp3', '', '[いすが～]壊れます', 'HOẠI', 'hỏng [cái ghế bị ~]'),
(29, '[コップが～]われます', '［koppuga～］waremasu', 'audio/minna/bai29/waremasu.mp3', '', '[コップが～]　割れます', 'CÁT', 'vỡ [cái cốc bị ~]'),
(29, '[きが～] おれます', '［kiga～］　oremasu', 'audio/minna/bai29/oremasu.mp3', '', '[木が～]折れます', 'MỘC TRIẾT', 'gãy [cái cây bị ~]'),
(29, '[かみが～]やぶれます', '［kamiga～］yaburemasu', 'audio/minna/bai29/yaburemasu.mp3', '', '[紙が～]破れます', 'CHỈ PHÁ', 'rách [tờ giấy bị ~]'),
(29, '[ふくが～]よごれます', '［fukuga～］yogoremasu', 'audio/minna/bai29/yogoremasu.mp3', '', '[服が～]汚れます', 'PHỤC Ô', 'bẩn [quần áo bị ~]'),
(29, '[ポケットが～]つきます', '［pokettoga～］tsukimasu', 'audio/minna/bai29/tsukimasu.mp3', '', '[ポケットが～]付きます', 'PHÓ', 'có, có gắn, có kèm theo [túi]'),
(29, '[ボタンが～]はずれます', '［botanga～］hazuremasu', 'audio/minna/bai29/hazuremasu.mp3', '', '[ボタンが～]外れます', 'NGOẠI', 'tuột, bung [cái cúc bị ~]'),
(29, '[エレベーターが～]とまります', '［erebe-ta-ga～］tomarimasu', 'audio/minna/bai29/tomarimasu.mp3', '', '[エレベーターが～]止まります', 'CHỈ', 'dừng [thang máy ~]'),
(29, 'まちがえます', 'machigaemasu', 'audio/minna/bai29/machigaemasu.mp3', '', '', '', 'nhầm, sai'),
(29, 'おとします', 'otoshimasu', 'audio/minna/bai29/otoshimasu.mp3', '', '落とします', 'LẠC', 'đánh rơi'),
(29, '[かぎが～]かかります', '［kagiga～］kakarimasu', 'audio/minna/bai29/kakarimasu.mp3', '', '[かぎが～]掛かります', 'QUẢI', 'khóa [chìa khóa ~]'),
(29, '[お]さら', '［o］sara', 'audio/minna/bai29/osara.mp3', '', '[お]皿', 'MÃNH', 'cái đĩa'),
(29, '[お]ちゃわん', '［o］chawan', 'audio/minna/bai29/ochawan.mp3', '', '', '', 'cái bát'),
(29, 'コップ', 'koppu', 'audio/minna/bai29/k_koppu.mp3', '', '', '', 'cái cốc'),
(29, 'ガラス', 'garasu', 'audio/minna/bai29/k_garasu.mp3', '', '', '', 'thủy tinh (glass)'),
(29, 'ふくろ', 'fukuro', 'audio/minna/bai29/fukuro.mp3', '', '袋', 'ĐẠI', 'cái túi'),
(29, 'さいふ', 'saifu', 'audio/minna/bai29/saifu.mp3', '', '財布', 'TÀI BỐ', 'cái ví'),
(29, 'えだ', 'eda', 'audio/minna/bai29/eda.mp3', '', '枝', 'CHI', 'cành cây'),
(29, 'えきいん', 'ekiin', 'audio/minna/bai29/ekiin.mp3', '', '駅員', 'DỊCH VIÊN', 'nhân viên nhà ga'),
(29, 'このへん', 'konohen', 'audio/minna/bai29/konohen.mp3', '', 'この辺', 'BIẾN', 'xung quanh đây, gần đây'),
(29, '～へん', '～hen', 'audio/minna/bai29/hen.mp3', '', '～辺', 'BIẾN', 'xung quanh ~, chỗ ~'),
(29, 'このぐらい', 'konogurai', 'audio/minna/bai29/konogurai.mp3', '', '', '', 'khoảng ngần này, cỡ khoảng như thế này'),
(29, 'おさきにどうぞ。', 'osakinidouzo', 'audio/minna/bai29/osakinidouzo.mp3', '', 'お先にどうぞ。', 'TIÊN', 'Xin mời anh/chị đi trước.'),
(29, '[ああ、]よかった。', '［aa、］yokatta', 'audio/minna/bai29/aayokatta.mp3', '', '', '', 'ồ, may quá.'),
(29, 'いまのでんしゃ', 'imanodensha', 'audio/minna/bai29/imanodensya.mp3', '', '今の電車', 'KIM ĐIỆN XA', 'đoàn tàu vừa rồi'),
(29, 'わすれもの', 'wasuremono', 'audio/minna/bai29/wasuremono.mp3', '', '忘れ物', 'VONG VẬT', 'vật để quên'),
(29, '～がわ', '～gawa', 'audio/minna/bai29/gawa.mp3', '', '～側', 'TRẮC', 'phía ~, bên ~'),
(29, 'ポケット', 'poketto', 'audio/minna/bai29/k_poketto.mp3', '', '', '', 'túi áo, túi quần (pocket)'),
(29, 'おぼえていません', 'oboeteimasen', 'audio/minna/bai29/oboeteimasen.mp3', '', '覚えていません。', 'GIÁC', 'Tôi không nhớ.'),
(29, 'あみだな', 'amidana', 'audio/minna/bai29/amidana.mp3', '', '網棚', 'VÕNG BẰNG', 'giá lưới, giá hành lý (trên tàu)'),
(29, 'たしか', 'tashika', 'audio/minna/bai29/tashika.mp3', '', '確か', 'XÁC', 'nếu không lầm thì'),
(29, 'よつや', 'yotsuya', 'audio/minna/bai29/yotuya.wav', '', '四ツ谷', 'TỨ CỐC', 'tên một nhà ga ở Tokyo'),
(29, 'じしん', 'jishin', 'audio/minna/bai29/jishin.wav', '', '地震', 'ĐỊA CHẤN', 'động đất'),
(29, 'かべ', 'kabe', 'audio/minna/bai29/kabe.wav', '', '壁', 'BÍCH', 'bức tường'),
(29, 'はり', 'hari', 'audio/minna/bai29/hari.wav', '', '針', 'CHÂM', 'kim đồng hồ'),
(29, 'さします', 'sashimasu', 'audio/minna/bai29/sashimasu.wav', '', '指します', 'CHỈ', 'chỉ'),
(29, 'えきまえ', 'ekimae', 'audio/minna/bai29/ekimae.wav', '', '駅前', 'DỊCH TIỀN', 'khu vực trước nhà ga'),
(29, 'たおれます', 'taoremasu', 'audio/minna/bai29/taoremasu.wav', '', '倒れます', 'ĐẢO', 'đổ'),
(29, 'にし', 'nishi', 'audio/minna/bai29/nishi.wav', '', '西', 'TÂY', 'tây, phía tây'),
(29, 'ほう', 'hou', 'audio/minna/bai29/hou.wav', '', '方', 'PHƯƠNG', 'hướng, phương hướng'),
(29, 'さんのみや', 'sannomiya', 'audio/minna/bai29/sannomiya.wav', '', '三宮', 'TAM CUNG', 'tên một địa điểm ở Kobe');