-- Bài 32
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(32, 'うんどうします', 'undoushimasu', 'audio/minna/bai32/undoushimasu.mp3', '', '運動します', 'VẬN ĐỘNG', 'vận động, tập thể thao'),
(32, 'せいこうします', 'seikoushimasu', 'audio/minna/bai32/seikoushimasu.mp3', '', '成功します', 'THÀNH CÔNG', 'thành công'),
(32, '[しけんに～]しっぱいします', '［shikenni～］shippaishimasu', 'audio/minna/bai32/shippaishimasu.mp3', '', '[試験に～]失敗します', 'THÍ NGHIỆM THẤT BẠI', 'thất bại, trượt [thi~]'),
(32, '[しけんに～]ごうかくします', '［shikenni～］goukakushimasu', 'audio/minna/bai32/gokakushimasu.mp3', '', '[試験に～]合格します', 'THÍ NGHIỆM HỢP CÁCH', 'đỗ [thi~]'),
(32, 'もどります', 'modorimasu', 'audio/minna/bai32/modorimasu.mp3', '', '戻ります', 'LỆ', 'quay lại, trở lại'),
(32, '[あめが～] やみます', '［amega～］　yamimasu', 'audio/minna/bai32/yamimasu.mp3', '', '[雨が～]', 'VŨ', 'tạnh, ngừng [mưa ~]'),
(32, 'はれます', 'haremasu', 'audio/minna/bai32/haremasu.mp3', '', '晴れます', 'TÌNH', 'nắng, quang đãng'),
(32, 'くもります', 'kumorimasu', 'audio/minna/bai32/kumorimasu.mp3', '', '曇ります', 'ĐÀM', 'có mây, mây mù'),
(32, '[かぜが～]ふきます', '［kazega～］fukimasu', 'audio/minna/bai32/fukimasu.mp3', '', '[風が～]吹きます', 'PHONG XÚY', 'thổi [gió ~]'),
(32, '[びょうきが～]なおります', '［byoukiga～］naorimasu', 'audio/minna/bai32/naorimasu.mp3', '', '[病気が～]治ります，直ります', 'BỆNH KHÍ TRỊ TRỰC', 'khỏi [bệnh]'),
(32, '[こしょうが～]なおります', '［koshouga～］naorimasu', 'audio/minna/bai32/naorimasu.mp3', '', '[故障が～]', 'CỐ CHƯỚNG', 'đã được sửa [chỗ hỏng ~]'),
(32, '[ねつが～]つづきます', '［netsuga～］tsudukimasu', 'audio/minna/bai32/tsuzukimasu.mp3', '', '[熱が～]続きます', 'NHIỆT TỤC', 'tiếp tục, tiếp diễn [sốt]'),
(32, '[かぜを～]ひきます', '［kazewo～］hikimasu', 'audio/minna/bai32/hikimasu.mp3', '', '', '', 'bị [cảm]'),
(32, 'ひやします', 'hiyashimasu', 'audio/minna/bai32/hiyashimasu.mp3', '', '冷やします', 'LÃNH', 'làm lạnh'),
(32, 'しんぱい[な]', 'shinpai［na］', 'audio/minna/bai32/shinpai.mp3', '', '心配[な]', 'TÂM PHỐI', 'lo lắng'),
(32, 'じゅうぶん[な]', 'juubun［na］', 'audio/minna/bai32/juubun.mp3', '', '十分[な]', 'THẬP PHÂN', 'đủ'),
(32, 'おかしい', 'okashii', 'audio/minna/bai32/okashii.mp3', '', '', '', 'có vấn đề, không bình thường, buồn cười'),
(32, 'うるさい', 'urusai', 'audio/minna/bai32/urusai.mp3', '', '', '', 'ồn ào, (âm thanh) to'),
(32, 'やけど', 'yakedo', 'audio/minna/bai32/yakedo.mp3', '', '', '', 'bỏng (～をします：bị bỏng)'),
(32, 'けが', 'kega', 'audio/minna/bai32/kega.mp3', '', '', '', 'vết thương (～をします：bị thương)'),
(32, 'せき', 'seki', 'audio/minna/bai32/seki.mp3', '', '', '', 'ho (～がでます：bị ho)'),
(32, 'インフルエンザ', 'infuruenza', 'audio/minna/bai32/k_infuruenza.mp3', '', '', '', 'cúm dịch'),
(32, 'そら', 'sora', 'audio/minna/bai32/sora.mp3', '', '空', 'KHÔNG', 'bầu trời'),
(32, 'たいよう', 'taiyou', 'audio/minna/bai32/taiyou.mp3', '', '太陽', 'THÁI DƯƠNG', 'mặt trời'),
(32, 'ほし', 'hoshi', 'audio/minna/bai32/hoshi.mp3', '', '星', 'TINH', 'sao, ngôi sao'),
(32, 'つき', 'tsuki', 'audio/minna/bai32/tsuki.mp3', '', '月', 'NGUYỆT', 'trăng, mặt trăng'),
(32, 'かぜ', 'kaze', 'audio/minna/bai32/kaze.mp3', '', '風', 'PHONG', 'gió'),
(32, 'きた', 'kita', 'audio/minna/bai32/kita.mp3', '', '北', 'BẮC', 'bắc'),
(32, 'みなみ', 'minami', 'audio/minna/bai32/minami.mp3', '', '南', 'NAM', 'nam'),
(32, 'にし', 'nishi', 'audio/minna/bai32/nishi.mp3', '', '西', 'TÂY', 'tây'),
(32, 'ひがし', 'higashi', 'audio/minna/bai32/higashi.mp3', '', '東', 'ĐÔNG', 'đông'),
(32, 'すいどう', 'suidou', 'audio/minna/bai32/suidou.mp3', '', '水道', 'THỦY ĐẠO', 'nước máy'),
(32, 'エンジン', 'enjin', 'audio/minna/bai32/k_enjin.mp3', '', '', '', 'động cơ'),
(32, 'チーム', 'chi-mu', 'audio/minna/bai32/k_chiimu.mp3', '', '', '', 'đội'),
(32, 'こんや', 'konya', 'audio/minna/bai32/konya.mp3', '', '今夜', 'KIM DẠ', 'tối nay, đêm nay'),
(32, 'ゆうがた', 'yuugata', 'audio/minna/bai32/yuugata.mp3', '', '夕方', 'TỊCH PHƯƠNG', 'chiều tối'),
(32, 'まえ', 'mae', 'audio/minna/bai32/mae.mp3', '', '', '', 'trước'),
(32, 'おそく', 'osoku', 'audio/minna/bai32/osoku.mp3', '', '遅く', 'TRÌ', 'muộn, khuya'),
(32, 'こんなに', 'konnani', 'audio/minna/bai32/konnani.mp3', '', '', '', 'như thế này'),
(32, 'そんなに', 'sonnani', 'audio/minna/bai32/sonnani.mp3', '', '', '', 'như thế đó (về vấn đề có quan hệ với người nghe)'),
(32, 'あんなに', 'annani', 'audio/minna/bai32/annani.mp3', '', '', '', 'như thế kia (về vấn đề không có quan hệ với người nói và người nghe)'),
(32, 'もしかしたら', 'moshikashitara', 'audio/minna/bai32/moshikashitara.mp3', '', '', '', 'có thể, biết đâu là, có khả năng'),
(32, 'それはいけませんね。', 'sorehaikemasenne', 'audio/minna/bai32/sorehaikemasenne.mp3', '', '', '', 'Thế thì thật không tốt.'),
(32, 'オリンピック', 'orinpikku', 'audio/minna/bai32/K_orinpikku.mp3', '', '', '', 'Olympic'),
(32, 'げんき', 'genki', 'audio/minna/bai32/genki.mp3', '', '元気', 'NGUYÊN KHÍ', 'khỏe, khỏe mạnh'),
(32, 'い', 'i', 'audio/minna/bai32/i.mp3', '', '胃', 'VỊ', 'dạ dày'),
(32, 'はたらきすぎ', 'hatarakisugi', 'audio/minna/bai32/hatarakisugi.mp3', '', '働きすぎ', 'ĐỘNG', 'làm việc quá sức, làm việc nhiều quá'),
(32, 'ストレス', 'sutoresu', 'audio/minna/bai32/k_sutoresu.mp3', '', '', '', 'Stress, căng thẳng tâm lý'),
(32, 'むりをします', 'muriwoshimasu', 'audio/minna/bai32/muriwoshimasu.mp3', '', '無理をします', 'VÔ LÝ', 'làm quá sức, làm quá khả năng'),
(32, 'ゆっくりします', 'yukkurishimasu', 'audio/minna/bai32/yukkurishimasu.mp3', '', '', '', 'nghỉ ngơi, thư thái, dưỡng sức'),
(32, 'ほしうらない', 'hoshiuranai', 'audio/minna/bai32/hoshiuranai.wav', '', '星占い', 'TINH CHIẾM', 'bói sao'),
(32, 'おうしざ', 'oushiza', 'audio/minna/bai32/oushiza.wav', '', '牡牛座', 'MẪU NGƯU TỌA', 'ch��m sao Kim Ngưu'),
(32, 'こまります', 'komarimasu', 'audio/minna/bai32/komarimasu.wav', '', '困ります', 'KHỐN', 'rắc rối, khó xử, có vấn đề'),
(32, 'たからくじ', 'takarakuji', 'audio/minna/bai32/takarakuji.wav', '', '宝くじ', 'BẢO', 'xổ số'),
(32, 'あたります', 'atarimasu', 'audio/minna/bai32/atarimasu.wav', '', '[宝くじが～]当たります', 'BẢO ĐƯƠNG', 'Trúng~ trúng [xổ số]'),
(32, 'けんこう', 'kenkou', 'audio/minna/bai32/kenkou.wav', '', '健康', 'KIỆN KHANG', 'sức khỏe, khỏe mạnh, an khang'),
(32, 'れんあい', 'renai', 'audio/minna/bai32/renai.wav', '', '恋愛', 'LUYẾN ÁI', 'tình yêu'),
(32, 'こいびと', 'koibito', 'audio/minna/bai32/koibito.wav', '', '恋人', 'LUYẾN NHÂN', 'người yêu'),
(32, '「お」かねもち', '「o」kanemochi', 'audio/minna/bai32/okanemochi.wav', '', '[お]金持ち', 'KIM TRÌ', 'người giàu có, người có nhiều tiền');