-- Bài 10
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(10, 'います', 'imasu', '/audio/minna/bai10/imasu.mp3', 'verb', NULL, NULL, 'có, ở (tồn tại, dùng cho người và động vật)'),
(10, 'あります', 'arimasu', '/audio/minna/bai10/arimasu.mp3', 'verb', NULL, NULL, 'có (tồn tại, dùng cho đồ vật)'),
(10, 'いろいろ[な]', 'iroiro[na]', '/audio/minna/bai10/iroiro.mp3', 'adj-na', NULL, NULL, 'nhiều, đa dạng'),
(10, 'おとこのひと', 'otokonohito', '/audio/minna/bai10/otokonohito.mp3', 'noun', '男の人', 'NAM NHÂN', 'người đàn ông'),
(10, 'おんなのひと', 'onnanohito', '/audio/minna/bai10/onnanohito.mp3', 'noun', '女の人', 'NỮ NHÂN', 'người đàn bà'),
(10, 'おとこのこ', 'otokonoko', '/audio/minna/bai10/otokonoko.mp3', 'noun', '男の子', 'NAM TỬ', 'cậu con trai'),
(10, 'おんなのこ', 'onnanoko', '/audio/minna/bai10/onnanoko.mp3', 'noun', '女の子', 'NỮ TỬ', 'cô con gái'),
(10, 'いぬ', 'inu', '/audio/minna/bai10/inu.mp3', 'noun', '犬', 'KHUYỂN', 'chó'),
(10, 'ねこ', 'neko', '/audio/minna/bai10/neko.mp3', 'noun', '猫', 'MIÊU', 'mèo'),
(10, 'き', 'ki', '/audio/minna/bai10/ki.mp3', 'noun', '木', 'MỘC', 'cây, gỗ'),
(10, 'もの', 'mono', '/audio/minna/bai10/mono.mp3', 'noun', '物', 'VẬT', 'vật, đồ vật'),
(10, 'フィルム', '～rumu', '/audio/minna/bai10/k_fijrumu.mp3', 'noun', NULL, NULL, 'phim'),
(10, 'でんち', 'denchi', '/audio/minna/bai10/denchi.mp3', 'noun', '電池', 'ĐIỆN TRÌ', 'Pin'),
(10, 'はこ', 'hako', '/audio/minna/bai10/hako.mp3', 'noun', '箱', 'TƯƠNG', 'hộp'),
(10, 'スイッチ', 'suitchi', '/audio/minna/bai10/k_suicchi.mp3', 'noun', NULL, NULL, 'công tắc'),
(10, 'れいぞうこ', 'reizouko', '/audio/minna/bai10/reizouko.mp3', 'noun', '冷蔵庫', 'LÃNH TÀN KHỐ', 'tủ lạnh'),
(10, 'テーブル', 'teｰburu', '/audio/minna/bai10/k-teeburu.mp3', 'noun', NULL, NULL, 'bàn'),
(10, 'ベッド', 'beddo', '/audio/minna/bai10/k_beddo.mp3', 'noun', NULL, NULL, 'giường'),
(10, 'たな', 'tana', '/audio/minna/bai10/tana.mp3', 'noun', '棚', 'BẰNG', 'giá sách'),
(10, 'ドア', 'doa', '/audio/minna/bai10/k-doa.mp3', 'noun', NULL, NULL, 'cửa'),
(10, 'まど', 'mado', '/audio/minna/bai10/mado.mp3', 'noun', '窓', 'SONG', 'cửa sổ'),
(10, 'ポスト', 'posuto', '/audio/minna/bai10/k_posuto.mp3', 'noun', NULL, NULL, 'hộp thư, hòm thư'),
(10, 'ビル', 'biru', '/audio/minna/bai10/k_biru.mp3', 'noun', NULL, NULL, 'toà nhà'),
(10, 'こうえん', 'kouen', '/audio/minna/bai10/kouen.mp3', 'noun', '公園', 'CÔNG VIÊN', 'công viên'),
(10, 'きっさてん', 'kissaten', '/audio/minna/bai10/kissaten.mp3', 'noun', '喫茶店', 'KHIẾT TRÀ ĐIẾM', 'quán giải khát, quán cà-phê'),
(10, 'ほんや', 'hon''ya', '/audio/minna/bai10/honya.mp3', 'noun', '本屋', 'BẢN ỐC', 'hiệu sách'),
(10, '～や', '～ya', '/audio/minna/bai10/ya.mp3', 'suffix', '～屋', 'ỐC', 'hiệu ~, cửa hàng ~'),
(10, 'のりば', 'noriba', '/audio/minna/bai10/noriba.mp3', 'noun', '乗り場', 'THỪA TRƯỜNG', 'bến xe, điểm lên xuống xe'),
(10, 'けん', 'ken', '/audio/minna/bai10/ken.mp3', 'noun', '県', 'HUYỆN', 'tỉnh'),
(10, 'うえ', 'ue', '/audio/minna/bai10/ue.mp3', 'noun', '上', 'THƯỢNG', 'trên'),
(10, 'した', 'shita', '/audio/minna/bai10/shita.mp3', 'noun', '下', 'HẠ', 'dưới'),
(10, 'まえ', 'mae', '/audio/minna/bai10/mae.mp3', 'noun', '前', 'TIỀN', 'trước'),
(10, 'うしろ', 'ushiro', '/audio/minna/bai10/ushiro.mp3', 'noun', NULL, NULL, 'sau'),
(10, 'みぎ', 'migi', '/audio/minna/bai10/migi.mp3', 'noun', '右', 'HUỮ', 'phải'),
(10, 'ひだり', 'hidari', '/audio/minna/bai10/hidari.mp3', 'noun', '左', 'TẢ', 'trái'),
(10, 'なか', 'naka', '/audio/minna/bai10/naka.mp3', 'noun', '中', 'TRUNG', 'trong, giữa'),
(10, 'そと', 'soto', '/audio/minna/bai10/soto.mp3', 'noun', '外', 'NGOẠI', 'ngoài'),
(10, 'となり', 'tonari', '/audio/minna/bai10/tonari.mp3', 'noun', '隣', 'LÂN', 'bên cạnh'),
(10, 'ちかく', 'chikaku', '/audio/minna/bai10/chikaku.mp3', 'noun', '近く', 'CẬN', 'gần'),
(10, 'あいだ', 'aida', '/audio/minna/bai10/aida.mp3', 'noun', '間', 'GIAN', 'giữa'),
(10, '～や～[など]', '～ya～[nado]', '/audio/minna/bai10/yanado.wav', 'particle', NULL, NULL, '~và ~, [v.v.]'),
(10, 'いちばん～', 'ichiban～', '/audio/minna/bai10/ichiban.mp3', 'adverb', NULL, NULL, '~ nhất (いちばん うえ：vị trí cao nhất)'),
(10, '―だんめ', '～danme', '/audio/minna/bai10/danme.mp3', 'suffix', '―段目', 'ĐOẠN MỤC', 'giá thứ -, tầng thứ'),
(10, '[どうも]すみません。', '[doumo]sumimasen｡', '/audio/minna/bai10/doumosumimasen.mp3', 'phrase', NULL, NULL, 'Cám ơn'),
(10, 'チリソース', 'chirisoｰsu', '/audio/minna/bai10/chirisosu.wav', 'noun', NULL, NULL, 'tương ớt (chili sauce)'),
(10, 'おく', 'oku', '/audio/minna/bai10/oku.mp3', 'noun', '奥', 'ÁO', 'bên trong cùng, phía sâu bên trong'),
(10, 'スパイス・コーナー', 'supaisu～koｰnaｰ', '/audio/minna/bai10/supaisukona.wav', 'noun', NULL, NULL, 'góc gia vị (sprice corner)'),
(10, '東京ディズニーランド', '～～～zuniｰrando', '/audio/minna/bai10/tokyodisneyland.wav', 'noun', NULL, 'ĐÔNG KINH', 'Công viên Tokyo Disneyland'),
(10, 'ユニューヤ・ストア', 'yunyuｰya～sutoa', '/audio/minna/bai10/yuunyuuyastore.wav', 'noun', NULL, NULL, 'tên một siêu thị (giả tưởng)'); 