-- Bài 31
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(31, '[しきが～]はじまります', '［shikiga～］hajimarimasu', 'audio/minna/bai31/hajimarimasu.mp3', '', '[式が～]始まります', 'THỨC THỦY', 'bắt đầu [buổi lễ ~]'),
(31, 'つづけます', 'tsudukemasu', 'audio/minna/bai31/tsudukemasu.mp3', '', '続けます', 'TỤC', 'tiếp tục'),
(31, 'みつけます', 'mitsukemasu', 'audio/minna/bai31/mitsukemasu.mp3', '', '見つけます', 'KIẾN', 'tìm, tìm thấy'),
(31, '[しけんを～]うけます', '［shikenwo～］ukemasu', 'audio/minna/bai31/ukemasu.mp3', '', '[試験を～]受けます', 'THÍ NGHIỆM THỤ/THỌ', 'thi [kỳ thi]'),
(31, '[だいがくに～] にゅうがくします', '［daigakuni～］　nyuugakushimasu', 'audio/minna/bai31/nyuugakushimasu.mp3', '', '[大学に～]入学します', 'ĐẠI HỌC NHẬP HỌC', 'nhập học, vào [(trường) đại học]'),
(31, '[だいがくを～]そつぎょうします', '［daigakuwo～］sotsugyoushimasu', 'audio/minna/bai31/sotsugyoushimasu.mp3', '', '[大学を～]卒業します', 'ĐẠI HỌC TỐT NGHIỆP', 'tốt nghiệp [(trường) đại học]'),
(31, '[かいぎに～] しゅっせきします', '［kaigini～］　shussekishimasu', 'audio/minna/bai31/syussekishimasu.mp3', '', '[会議に～]出席します', 'HỘI NGHỊ XUẤT TỊCH', 'tham dự, tham gia [cuộc họp]'),
(31, 'きゅうけいします', 'kyuukeishimasu', 'audio/minna/bai31/kyuukeishimasu.mp3', '', '休憩します', 'HƯU KHẾ', 'nghỉ, giải lao'),
(31, 'れんきゅう', 'renkyuu', 'audio/minna/bai31/renkyuu.mp3', '', '連休', 'LIÊN HƯU', 'ngày nghỉ liền nhau'),
(31, 'さくぶん', 'sakubun', 'audio/minna/bai31/sakubun.mp3', '', '作文', 'TÁC VĂN', 'bài văn'),
(31, 'てんらんかい', 'tenrankai', 'audio/minna/bai31/tenrankai.mp3', '', '展覧会', 'TRIỂN LÃM HỘI', 'triển lãm'),
(31, 'けっこんしき', 'kekkonshiki', 'audio/minna/bai31/kekkoshiki.mp3', '', '結婚式', 'KẾT HÔN THỨC', 'lễ cưới, đám cưới'),
(31, '[お]そうしき', '［o］soushiki', 'audio/minna/bai31/osoushiki.mp3', '', '[お]葬式', 'TÁNG THỨC', 'lễ tang, đám tang'),
(31, 'しき', 'shiki', 'audio/minna/bai31/shiki.mp3', '', '式', 'THỨC', 'lễ, đám'),
(31, 'ほんしゃ', 'honsha', 'audio/minna/bai31/honsya.mp3', '', '本社', 'BẢN XÃ', 'trụ sở chính'),
(31, 'してん', 'shiten', 'audio/minna/bai31/shiten.mp3', '', '支店', 'CHI ĐIẾM', 'chi nhánh'),
(31, 'きょうかい', 'kyoukai', 'audio/minna/bai31/kyoukai.mp3', '', '教会', 'GIÁO HỘI', 'nhà thờ'),
(31, 'だいがくいん', 'daigakuin', 'audio/minna/bai31/daigakuin.mp3', '', '大学院', 'ĐẠI HỌC VIỆN', 'cao học, sở giáo dục trên đại học'),
(31, 'どうぶつえん', 'doubutsuen', 'audio/minna/bai31/doubutsuen.mp3', '', '動物園', 'ĐỘNG VẬT VIÊN', 'vườn thú, vườn bách thú'),
(31, 'おんせん', 'onsen', 'audio/minna/bai31/onsen.mp3', '', '温泉', 'ÔN TUYỀN', 'suối nước nóng'),
(31, 'おきゃく[さん]', 'okyaku［san］', 'audio/minna/bai31/okyakusan.mp3', '', 'お客[さん]', 'KHÁCH', 'khách hàng'),
(31, 'だれか', 'dareka', 'audio/minna/bai31/dareka.mp3', '', '', '', 'ai đó'),
(31, '～のほう', '～nohou', 'audio/minna/bai31/nohou.mp3', '', '～の方', 'PHƯƠNG', 'phía ~, hướng ~'),
(31, 'ずっと', 'zutto', 'audio/minna/bai31/zutto.mp3', '', '', '', 'suốt, liền'),
(31, 'ピカソ', 'pikaso', 'audio/minna/bai31/K_pikaso.mp3', '', '', '', 'Pablo Picasso, danh họa người Tây Ban Nha (1881-1973)'),
(31, 'うえのこうえん', 'uenokouen', 'audio/minna/bai31/uenokouen.mp3', '', '上野公園', 'THƯỢNG DÃ CÔNG VIÊN', 'Công viên Ueno (ở Tokyo)'),
(31, 'のこります', 'nokorimasu', 'audio/minna/bai31/nokorimasu.mp3', '', '残ります', 'TÀN', 'ở lại'),
(31, 'つきに', 'tsukini', 'audio/minna/bai31/tsukini.mp3', '', '月に', 'NGUYỆT', 'một tháng'),
(31, 'ふつうの', 'futsuuno', 'audio/minna/bai31/futsuno.mp3', '', '普通の', 'PHỔ THÔNG', 'thường, thông thường'),
(31, 'インターネット', 'inta-netto', 'audio/minna/bai31/k_intaanetto.mp3', '', '', '', 'Internet'),
(31, 'むら', 'mura', 'audio/minna/bai31/mura.wav', '', '村', 'THÔN', 'làng'),
(31, 'えいがかん', 'eigakan', 'audio/minna/bai31/eigakan.wav', '', '映画館', 'ẢNH HỌA QUÁN', 'rạp chiếu phim'),
(31, 'いや「な」', 'iya「na」', 'audio/minna/bai31/iya.wav', '', '嫌[な]', 'HIỀM', 'chán, ghét, không chấp nhận được'),
(31, 'そら', 'sora', 'audio/minna/bai31/sora.wav', '', '空', 'KHÔNG', 'bầu trời'),
(31, 'とじます', 'tojimasu', 'audio/minna/bai31/tojimasu.wav', '', '閉じます', 'BẾ', 'đóng, nhắm'),
(31, 'とかい', 'tokai', 'audio/minna/bai31/tokai.wav', '', '都会', 'ĐÔ HỘI', 'thành phố, nơi đô hội'),
(31, 'こどもたち', 'kodomotachi', 'audio/minna/bai31/kodomotachi.wav', '', '子供たち', 'TỬ CUNG', 'trẻ em, trẻ con'),
(31, 'じゆうに', 'jiyuuni', 'audio/minna/bai31/jiyuuni.wav', '', '自由に', 'TỰ DO', 'tự do'),
(31, 'せかいじゅう', 'sekaijuu', 'audio/minna/bai31/sekaiju.wav', '', '世界中', 'THẾ GIỚI TRUNG', 'khắp thế giới'),
(31, 'あつまります', 'atsumarimasu', 'audio/minna/bai31/atsumarimasu.wav', '', '集まります', 'TẬP', 'tập trung'),
(31, 'うつくしい', 'utsukushii', 'audio/minna/bai31/utsukushi.wav', '', '美しい', 'MỸ', 'đẹp'),
(31, 'しぜん', 'shizen', 'audio/minna/bai31/shizen.wav', '', '自然', 'TỰ NHIÊN', 'tự nhiên, thiên nhiên'),
(31, 'すばらしさ', 'subarashisa', 'audio/minna/bai31/subarashisa.wav', '', '', '', 'tuyệt vời'),
(31, 'きがつきます', 'kigatsukimasu', 'audio/minna/bai31/kigatsukimasu.wav', '', '気がつきます', 'KHÍ', 'để ý, nhận ra');