-- Bài 42
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(42, 'つつみます', 'tsutsumimasu', 'audio/minna/bai42/tsutsumimasu.mp3', '', '包みます', 'BAO', 'bọc, gói'),
(42, 'わかします', 'wakashimasu', 'audio/minna/bai42/wakashimasu.mp3', '', '沸かします', 'PHẮT/PHI', 'đun sôi'),
(42, 'まぜます', 'mazemasu', 'audio/minna/bai42/mazemasu.mp3', '', '混ぜます', 'HỖN', 'trộn, khuấy'),
(42, 'けいさんします', 'keisanshimasu', 'audio/minna/bai42/keisanshimasu.mp3', '', '計算します', 'KẾ TOÁN', 'tính toán, làm tính'),
(42, 'あつい', 'atsui', 'audio/minna/bai42/atsui.mp3', '', '厚い', 'HẬU', 'dày'),
(42, 'うすい', 'usui', 'audio/minna/bai42/usui.mp3', '', '薄い', 'BẠC', 'mỏng'),
(42, 'べんごし', 'bengoshi', 'audio/minna/bai42/bengoshi.mp3', '', '弁護士', 'BIỆN HỘ SĨ', 'luật sư'),
(42, 'おんがくか', 'ongakuka', 'audio/minna/bai42/ongakuka.mp3', '', '音楽家', 'ÂM NHẠC GIA', 'nhạc sĩ'),
(42, 'こどもたち', 'kodomotachi', 'audio/minna/bai42/kodomotachi.mp3', '', '子どもたち', 'TỬ', 'trẻ em, trẻ con, bọn trẻ'),
(42, 'ふたり', 'futari', 'audio/minna/bai42/futari.mp3', '', '二人', 'NHỊ NHÂN', 'hai người, cặp, đôi'),
(42, 'きょういく', 'kyouiku', 'audio/minna/bai42/kyouiku.mp3', '', '教育', 'GIÁO DỤC', 'giáo dục, việc học hành'),
(42, 'れきし', 'rekishi', 'audio/minna/bai42/rekishi.mp3', '', '歴史', 'LỊCH SỬ', 'lịch sử'),
(42, 'ぶんか', 'bunka', 'audio/minna/bai42/bunka.mp3', '', '文化', 'VĂN HÓA', 'văn hóa'),
(42, 'しゃかい', 'shakai', 'audio/minna/bai42/syakai.mp3', '', '社会', 'XÃ HỘI', 'xã hội'),
(42, 'ほうりつ', 'houritsu', 'audio/minna/bai42/houritsu.mp3', '', '法律', 'PHÁP LUẬT', 'pháp luật'),
(42, 'せんそう', 'sensou', 'audio/minna/bai42/sensou.mp3', '', '戦争', 'CHIẾN TRANH', 'chiến tranh'),
(42, 'へいわ', 'heiwa', 'audio/minna/bai42/heiwa.mp3', '', '平和', 'BÌNH HÒA', 'hòa bình'),
(42, 'もくてき', 'mokuteki', 'audio/minna/bai42/mokuteki.mp3', '', '目的', 'MỤC ĐÍCH', 'mục đích'),
(42, 'あんぜん', 'anzen', 'audio/minna/bai42/anzen.mp3', '', '安全', 'AN TOÀN', 'an toàn'),
(42, 'ろんぶん', 'ronbun', 'audio/minna/bai42/ronbun.mp3', '', '論文', 'LUẬN VĂN', 'luận văn, bài báo học thuật'),
(42, 'かんけい', 'kankei', 'audio/minna/bai42/kankei.mp3', '', '関係', 'QUAN HỆ', 'quan hệ'),
(42, 'ミキサー', 'mikisa-', 'audio/minna/bai42/k_mikisaa.mp3', '', '', '', 'máy trộn (mixer)'),
(42, 'や���ん', 'yakan', 'audio/minna/bai42/yakan.mp3', '', '', '', 'cái ấm nước'),
(42, 'せんぬき', 'sennuki', 'audio/minna/bai42/sennuki.mp3', '', '栓抜き', 'XUYÊN BẠT', 'cái mở nắp chai'),
(42, 'かんきり', 'kankiri', 'audio/minna/bai42/kankiri.mp3', '', '缶切り', 'PHẪU THIẾT', 'cái mở đồ hộp'),
(42, 'かんづめ', 'kandume', 'audio/minna/bai42/kandume.mp3', '', '缶詰', 'PHẪU CẬT', 'đồ hộp'),
(42, 'ふろしき', 'furoshiki', 'audio/minna/bai42/furoshiki.mp3', '', '', '', 'tấm vải để gói đồ'),
(42, 'そろばん', 'soroban', 'audio/minna/bai42/soroban.mp3', '', '', '', 'bàn tính'),
(42, 'たいおんけい', 'taionkei', 'audio/minna/bai42/taionkei.mp3', '', '体温計', 'THỂ ÔN KẾ', 'máy đo nhiệt độ cơ thể'),
(42, 'ざいりょう', 'zairyou', 'audio/minna/bai42/zairyou.mp3', '', '材料', 'TÀI LIỆU', 'nguyên liệu'),
(42, 'いし', 'ishi', 'audio/minna/bai42/ishi.mp3', '', '石', 'THẠCH', 'hòn đá, đá'),
(42, 'ピラミッド', 'piramiddo', 'audio/minna/bai42/k_piramiddo.mp3', '', '', '', 'kim tự tháp'),
(42, 'データ', 'de-ta', 'audio/minna/bai42/k_deeta.mp3', '', '', '', 'số liệu, dữ liệu'),
(42, 'ファイル', 'fairu', 'audio/minna/bai42/k_fuxairu.mp3', '', '', '', 'cái kẹp tài liệu (file)'),
(42, 'ある～', 'aru～', 'audio/minna/bai42/aru.mp3', '', '', '', 'có ~, một ~'),
(42, 'いっしょうけんめい', 'isshoukenmei', 'audio/minna/bai42/issyoukenmei.mp3', '', '一生懸命', 'NHẤT SINH HUYỀN MỆNH', 'hết sức, chăm chỉ'),
(42, 'なぜ', 'naze', 'audio/minna/bai42/naze.mp3', '', '', '', 'tại sao'),
(42, 'こくれん', 'kokuren', 'audio/minna/bai42/kokuren.wav', '', '国連', 'QUỐC LIÊN', 'Liên hợp Quốc'),
(42, 'エリーゼのために', 'eri-zenotameni', 'audio/minna/bai42/erizenotameni.wav', '', '', '', 'Fur” Elize, tên một bản nhạc của Beethoven'),
(42, 'ベートーベン', 'be-to-ben', 'audio/minna/bai42/betoben.wav', '', '', '', 'Beethoven (1770-1827), nhà soạn nhạc người Đức'),
(42, 'ポーランド', 'po-rando', 'audio/minna/bai42/borando.wav', '', '', '', 'Ba Lan'),
(42, 'ローン', 'ro-n', 'audio/minna/bai42/ron.wav', '', '', '', 'khoản vay trả góp, tiền vay góp'),
(42, 'セット', 'setto', 'audio/minna/bai42/setto.wav', '', '', '', 'bộ'),
(42, 'あと', 'ato', 'audio/minna/bai42/ato.wav', '', '', '', 'còn lại'),
(42, 'カップラーメン', 'kappura-men', 'audio/minna/bai42/kappuramen.wav', '', '', '', 'mì ăn liền đựng trong cốc'),
(42, 'インスタントラーメン', 'insutantora-men', 'audio/minna/bai42/insutantoramen.wav', '', '', '', 'mì ăn liền'),
(42, 'なべ', 'nabe', 'audio/minna/bai42/nabe.wav', '', '', '', 'cái chảo, cái nồi'),
(42, 'どんぶり', 'donburi', 'audio/minna/bai42/donburi.wav', '', '', '', 'cái bát tô'),
(42, 'しょくひん', 'shokuhin', 'audio/minna/bai42/shokuhin.wav', '', '食品', 'THỰC PHẨM', 'thực phẩm, đồ ăn'),
(42, 'ちょうさ', 'chousa', 'audio/minna/bai42/chousa.wav', '', '調査', 'ĐIỀU TRA', 'việc điều tra, cuộc điều tra'),
(42, 'カップ', 'kappu', 'audio/minna/bai42/kappu.wav', '', '', '', 'cốc (dùng để đựng đồ ăn)'),
(42, 'また', 'mata', 'audio/minna/bai42/mata.wav', '', '', '', 'và, thêm nữa'),
(42, '～のかわりに', '～nokawarini', 'audio/minna/bai42/nokawarini.wav', '', '～の代わりに', 'ĐẠI', 'thay ~, thay thế ~'),
(42, 'どこででも', 'dokodedemo', 'audio/minna/bai42/dokodedemo.wav', '', '', '', 'ở đâu cũng'),
(42, 'いまでは', 'imadeha', 'audio/minna/bai42/imadeha.wav', '', '今では', 'KIM', 'bây giờ (thì)');