-- Bài 43
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(43, '[ゆしゅつが～]ふえます', '［yushutsuga～］fuemasu', 'audio/minna/bai43/fuemasu.mp3', '', '[輸出が～]増えます', 'THÂU XUẤT TĂNG', 'tăng, tăng lên [xuất khẩu ~]'),
(43, '[ゆしゅつが～] へります', '［yushutsuga～］　herimasu', 'audio/minna/bai43/herimasu.mp3', '', '[輸出が～]　減ります', 'THÂU XUẤT GIẢM', 'giảm, giảm xuống [xuất khẩu ~]'),
(43, '[ねだんが～]あがります', '［nedanga～］agarimasu', 'audio/minna/bai43/agarimasu.mp3', '', '[値段が～]上がります', 'TRỊ ĐOẠN THƯỢNG', 'tăng, tăng lên [giá ~]'),
(43, '[ねだんが～]さがります', '［nedanga～］sagarimasu', 'audio/minna/bai43/sagarimasu.mp3', '', '[値段が～]下がります', 'TRỊ ĐOẠN HẠ', 'giảm, giảm xuống [giá ~]'),
(43, '[ひもが～]きれます', '［himoga～］kiremasu', 'audio/minna/bai43/kiremasu.mp3', '', '[ひもが～]切れます', 'THIẾT', 'đứt [sợi dây bị ~]'),
(43, '[ボタンが～]とれます', '［botanga～］toremasu', 'audio/minna/bai43/toremasu.mp3', '', '', '', 'tuột [cái cúc bị ~]'),
(43, '[にもつが～] おちます', '［nimotsuga～］　ochimasu', 'audio/minna/bai43/ochimasu.mp3', '', '[荷物が～]落ちます', 'HÀ VẬT LẠC', 'rơi [hành lý bị ~]'),
(43, '[ガソリンが～]なくなります', '［gasoringa～］nakunarimasu', 'audio/minna/bai43/nakunarimasu.mp3', '', '', '', 'mất, hết [xăng bị ~]'),
(43, 'じょうぶ[な]', 'joubu［na］', 'audio/minna/bai43/joubu.mp3', '', '丈夫[な]', 'TRƯỢNG PHU', 'chắc, bền'),
(43, 'へん[な]', 'hen［na］', 'audio/minna/bai43/hen.mp3', '', '変[な]', 'BIẾN', 'lạ, kỳ quặc'),
(43, 'しあわせ[な]', 'shiawase［na］', 'audio/minna/bai43/shiawase.mp3', '', '幸せ[な]', 'HẠNH', 'hạnh phúc'),
(43, 'うまい', 'umai', 'audio/minna/bai43/umai.mp3', '', '', '', 'ngon'),
(43, 'まずい', 'mazui', 'audio/minna/bai43/mazui.mp3', '', '', '', 'dở'),
(43, 'つまらない', 'tsumaranai', 'audio/minna/bai43/tsumaranai.mp3', '', '', '', 'buồn tẻ, không hấp dẫn, không thú vị'),
(43, 'ガソリン', 'gasorin', 'audio/minna/bai43/k_gasorin.mp3', '', '', '', 'xăng'),
(43, 'ひ', 'hi', 'audio/minna/bai43/hi.mp3', '', '火', 'HỎA', 'lửa'),
(43, 'だんぼう', 'danbou', 'audio/minna/bai43/danbou.mp3', '', '暖房', 'NOÃN PHÒNG', 'thiết bị làm ấm, lò sưởi, máy điều hòa'),
(43, 'れいぼう', 'reibou', 'audio/minna/bai43/reibou.mp3', '', '冷房', 'LÃNH PHÒNG', 'thiết bị làm mát, máy điều hòa'),
(43, 'センス', 'sensu', 'audio/minna/bai43/k_sensu.mp3', '', '', '', 'có khiếu, có gu ([ふくの]～があります：có gu [ăn mặt])'),
(43, 'いまにも', 'imanimo', 'audio/minna/bai43/imanimo.mp3', '', '今にも', 'KIM', '(có vẻ, sắp) ~ đến nơi'),
(43, 'わあ', 'waa', 'audio/minna/bai43/waa.mp3', '', '', '', 'ôi! (câu nói dùng khi ngạc nhiên hoặc cảm thán điều gì)'),
(43, 'かいいん', 'kaiin', 'audio/minna/bai43/kaiin.mp3', '', '会員', 'HỘI VIÊN', 'thành viên'),
(43, 'てきとう「な」', 'tekitou「na」', 'audio/minna/bai43/tekitou.mp3', '', '適当[な]', 'THÍCH ĐƯƠNG', 'thích hợp, vừa phải'),
(43, 'ねんれい', 'nenrei', 'audio/minna/bai43/nenrei.mp3', '', '年齢', 'NIÊN LINH', 'tuổi'),
(43, 'しゅうにゅう', 'shuunyuu', 'audio/minna/bai43/syuunyuu.mp3', '', '収入', 'THÂU NHẬP/THU NHẬP', 'thu nhập'),
(43, 'ぴったり', 'pittari', 'audio/minna/bai43/pittari.mp3', '', '', '', 'vừa vặn, đúng'),
(43, 'そのうえ', 'sonoue', 'audio/minna/bai43/sonoue.mp3', '', '', '', 'thêm vào đó, hơn thế'),
(43, '～といいます', '～toiimasu', 'audio/minna/bai43/toiimasu.mp3', '', '', '', '(tên) là ~, gọi là ~'),
(43, 'ばら', 'bara', 'audio/minna/bai43/bara.wav', '', '', '', 'Hoa Hồng'),
(43, 'ドライブ', 'doraibu', 'audio/minna/bai43/doraibu.wav', '', '', '', 'lái xe (đi chơi)');