-- Bài 13
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(13, 'あそびます', 'asobimasu', '/audio/minna/bai13/asobimasu.mp3', 'verb', '遊びます', 'DU', 'chơi'),
(13, 'およぎます', 'oyogimasu', '/audio/minna/bai13/oyogimasu.mp3', 'verb', '泳ぎます', 'VỊNH', 'bơi'),
(13, 'むかえます', 'mukaemasu', '/audio/minna/bai13/mukaemasu.mp3', 'verb', '迎えます', 'NGHINH', 'đón'),
(13, 'つかれます', 'tsukaremasu', '/audio/minna/bai13/tsukaremasu.mp3', 'verb', '疲れます', 'BÌ', 'mệt'),
(13, '[てがみを～]だします', '[tegamiwo～]dashimasu', '/audio/minna/bai13/dashimasu.mp3', 'verb', '[手紙を～]出します', 'THỦ CHỈ XUẤT', 'gửi[thư]'),
(13, '[きっさてんに～]はいります', '[kissatenni～]hairimasu', '/audio/minna/bai13/hairimasu.mp3', 'verb', '[喫茶店に～]入ります', 'KHIẾT TRÀ ĐIẾM NHẬP', 'vào [quán giải khát]'),
(13, '[きっさてんを～]でます', '[kissatenwo～]demasu', '/audio/minna/bai13/demasu.mp3', 'verb', '[喫茶店を～]出ます', 'KHIẾT TRÀ ĐIẾM XUẤT', 'ra, ra khỏi [quán giải khát]'),
(13, 'けっこんします', 'kekkonshimasu', '/audio/minna/bai13/kekkonshimasu.mp3', 'verb', '結婚します', 'KẾT HÔN', 'kết hôn, lập gia đình, cưới'),
(13, 'かいものします', 'kaimonoshimasu', '/audio/minna/bai13/kaimonoshimasu.mp3', 'verb', '買い物します', 'MÃI VẬT', 'mua hàng'),
(13, 'しょくじします', 'shokujishimasu', '/audio/minna/bai13/syokujishimasu.mp3', 'verb', '食事します', 'THỰC SỰ', 'ăn cơm'),
(13, '[こうえんを～]さんぽします', '[kouenwo～]sanposhimasu', '/audio/minna/bai13/sanposhimasu.mp3', 'verb', '[公園を～]散歩します', 'CÔNG VIÊN TÁN BỘ', 'đi dạo [ở công viên]'),
(13, 'たいへん「な」', 'taihen｢na｣', '/audio/minna/bai13/taihen.mp3', 'adj-na', '大変「な」', 'ĐẠI BIẾN', 'vất vả, khó khăn, khổ'),
(13, 'ほしい', 'hoshii', '/audio/minna/bai13/hoshii.mp3', 'adj-i', '欲しい', 'DỤC', 'muốn có'),
(13, 'さびしい', 'sabishii', '/audio/minna/bai13/sabishii.mp3', 'adj-i', '寂しい', 'TỊCH', 'buồn, cô đơn'),
(13, 'ひろい', 'hiroi', '/audio/minna/bai13/hiroi.mp3', 'adj-i', '広い', 'QUẢNG', 'rộng'),
(13, 'せまい', 'semai', '/audio/minna/bai13/semai.mp3', 'adj-i', '狭い', 'HIỆP', 'chật, hẹp'),
(13, 'しやくしょ', 'shiyakusho', '/audio/minna/bai13/shiyakusyo.mp3', 'noun', '市役所', 'THỊ DỊCH SỞ', 'văn phòng hành chính quận, thành phố'),
(13, 'プール', 'puｰru', '/audio/minna/bai13/k_puuruu.mp3', 'noun', NULL, NULL, 'bể bơi'),
(13, 'かわ', 'kawa', '/audio/minna/bai13/kawa.mp3', 'noun', '川', 'XUYÊN', 'sông'),
(13, 'けいざい', 'keizai', '/audio/minna/bai13/keizai.mp3', 'noun', '経済', 'KINH TẾ', 'kinh tế'),
(13, 'びじゅつ', 'bijutsu', '/audio/minna/bai13/bijutsu.mp3', 'noun', '美術', 'MỸ THUẬT', 'mỹ thuật'),
(13, 'つり', 'tsuri', '/audio/minna/bai13/tsuri.mp3', 'noun', '釣り', 'ĐIẾU', 'việc câu cá (~をします：câu cá)'),
(13, 'スキー', 'sukiｰ', '/audio/minna/bai13/k_sukii.mp3', 'noun', NULL, NULL, 'việc trượt tuyết (~をします：trượt tuyết)'),
(13, 'かいぎ', 'kaigi', '/audio/minna/bai13/kaigi.mp3', 'noun', '会議', 'HỘI NGHỊ', 'họp, cuộc họp (~をします: họp, tổ chức cuộc họp)'),
(13, 'とうろく', 'touroku', '/audio/minna/bai13/touroku.mp3', 'noun', '登録', 'ĐĂNG LỤC', 'việc đăng ký (~をします：đăng ký)'),
(13, 'しゅうまつ', 'shuumatsu', '/audio/minna/bai13/syuumatsu.mp3', 'noun', '週末', 'CHU MẠT', 'cuối tuần'),
(13, '～ごろ', '～goro', '/audio/minna/bai13/goro.mp3', 'suffix', NULL, NULL, 'khoảng ~ (dùng cho thời gian)'),
(13, 'なにか', 'nanika', '/audio/minna/bai13/nanika.mp3', 'pronoun', '何か', 'HÀ', 'cái gì đó'),
(13, 'どこか', 'dokoka', '/audio/minna/bai13/dokoka.mp3', 'pronoun', NULL, NULL, 'đâu đó, chỗ nào đó'),
(13, 'おなかが　すきました。', 'onakaga sukimashita｡', '/audio/minna/bai13/onakagasukimashita.mp3', 'phrase', NULL, NULL, '(tôi) đói rồi.'),
(13, 'おなかが　いっぱいです。', 'onakaga ippaidesu｡', '/audio/minna/bai13/onakagaippaidesu.mp3', 'phrase', NULL, NULL, '(tôi) no rồi.'),
(13, 'のどが　かわきました。', 'nodoga kawakimashita｡', '/audio/minna/bai13/nodogakawakimashita.mp3', 'phrase', NULL, NULL, '(tôi) khát.'),
(13, 'そうですね。', 'soudesune｡', '/audio/minna/bai13/soudesune.mp3', 'phrase', NULL, NULL, 'Thế à. Như vậy nhỉ'),
(13, 'そうしましょう。', 'soushimashou｡', '/audio/minna/bai13/soushimasyou.mp3', 'phrase', NULL, NULL, 'Nhất trí./ Chúng ta thống nhất như thế.'),
(13, 'ごちゅうもん', 'gochuumon', '/audio/minna/bai13/gochuumonha.mp3', 'phrase', 'ご注文は？', 'CHÚ VĂN', 'Anh/Chị dùng món gì ạ'),
(13, 'ていしょく', 'teishoku', '/audio/minna/bai13/teisyoku.mp3', 'noun', NULL, NULL, 'cơm suất, cơm phần'),
(13, 'ぎゅうどん', 'gyuudon', '/audio/minna/bai13/gyuudon.mp3', 'noun', '牛どん', 'NGƯU', 'món cơm thịt bò'),
(13, '「しょうしょう」おまちください', '｢shoushou｣omachikudasai', '/audio/minna/bai13/syousyouomachikudasai.mp3', 'phrase', '[少々] お待ちください。', 'THIỂU ĐÃI', 'Xin anh/chị vui lòng đợi [một chút].'),
(13, 'べつべつに', 'betsubetsuni', '/audio/minna/bai13/betsubetsuni.mp3', 'adverb', '別々に', 'BIỆT', 'riêng ra/ để riêng'),
(13, 'ロシア', 'roshia', '/audio/minna/bai13/roshia.wav', 'noun', NULL, NULL, 'Nga'),
(13, 'つるや', 'tsuruya', '/audio/minna/bai13/tsuruya.wav', 'noun', NULL, NULL, 'tên một nhà hàng (giả tưởng)'),
(13, 'おはようテレビ', 'ohayouterebi', '/audio/minna/bai13/ohayouterebi.wav', 'noun', NULL, NULL, 'tên một chương trình truyền hình (giả tưởng)'); 