-- Bài 17
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(17, 'おぼえます', 'oboemasu', 'audio/minna/bai17/oboemasu.mp3', '', '覚えます', 'GIÁC', 'nhớ'),
(17, 'わすれます', 'wasuremasu', 'audio/minna/bai17/wasuremasu.mp3', '', '忘れます', 'VONG', 'quên'),
(17, 'なくします', 'nakushimasu', 'audio/minna/bai17/nakushimasu.mp3', '', '', '', 'mất, đánh mất'),
(17, '[レポートを～]だします', '[repoｰtowo～]dashimasu', 'audio/minna/bai17/dashimasu.mp3', '', '[レポートを～]出します', 'XUẤT', 'nộp[bản/bài báo cáo]'),
(17, 'はらいます', 'haraimasu', 'audio/minna/bai17/haraimasu.mp3', '', '払います', 'PHẤT', 'trả tiền'),
(17, 'かえします', 'kaeshimasu', 'audio/minna/bai17/kaeshimasu.mp3', '', '返します', 'PHẢN', 'trả lại'),
(17, 'でかけます', 'dekakemasu', 'audio/minna/bai17/dekakemasu.mp3', '', '出かけます', 'XUẤT', 'ra ngoài'),
(17, 'ぬぎます', 'nugimasu', 'audio/minna/bai17/nugimasu.mp3', '', '脱ぎます', 'THOÁT', 'cởi (quần áo, giầy)'),
(17, 'もっていきます', 'motteikimasu', 'audio/minna/bai17/motteikimasu.mp3', '', '持って行きます', 'TRÌ HÀNH', 'mang đi, mang theo'),
(17, 'もってきます', 'mottekimasu', 'audio/minna/bai17/mottekimasu.mp3', '', '持って来ます', 'TRÌ LAI', 'mang đến'),
(17, 'しんぱいします', 'shinpaishimasu', 'audio/minna/bai17/shinpaishimasu.mp3', '', '心配します', 'TÂM PHỐI', 'lo lắng'),
(17, 'ざんぎょうします', 'zangyoushimasu', 'audio/minna/bai17/zangyoushimasu.mp3', '', '残業します', 'TÀN NGHIỆP', 'làm thêm, làm quá giờ'),
(17, 'しゅっちょうします', 'shucchoushimasu', 'audio/minna/bai17/shucchoushimasu.mp3', '', '出張します', 'XUẤT TRƯƠNG', 'đi công tác'),
(17, '[くすりを～]のみます', '[kusuriwo～]nomimasu', 'audio/minna/bai17/nomimasu.mp3', '', '[薬を～]飲みます', 'DƯỢC ẨM', 'uống [thuốc]'),
(17, '[おふろに～]はいります', '[ofuroni～]hairimasu', 'audio/minna/bai17/haraimasu.mp3', '', '[おふろに～]入ります', 'NHẬP', 'tắm bồn [vào bồn tắm]'),
(17, 'たいせつ[な]', 'taisetsu[na]', 'audio/minna/bai17/taisetsu.mp3', '', '大切[な]', 'ĐẠI THIẾT', 'quan trọng, quý giá'),
(17, 'だいじょうぶ[な]', 'daijoubu[na]', 'audio/minna/bai17/daijobu.mp3', '', '大丈夫[な]', 'ĐẠI TRƯỢNG PHU', 'không sao, không có vấn đề gì'),
(17, 'あぶない', 'abunai', 'audio/minna/bai17/abunai.mp3', '', '危ない', 'NGUY', 'nguy hiểm'),
(17, 'もんだい', 'mondai', 'audio/minna/bai17/mondai.mp3', '', '問題', 'VẤN ĐỀ', 'vấn đề'),
(17, 'こたえ', 'kotae', 'audio/minna/bai17/kotae.mp3', '', '答え', 'ĐÁP', 'câu trả lời'),
(17, 'きんえん', 'kin''en', 'audio/minna/bai17/kinen.mp3', '', '禁煙', 'CẤM YÊN', 'cấm hút thuốc'),
(17, '[けんこう]ほけんしょう', '[kenkou]hokenshou', 'audio/minna/bai17/hokensyou.mp3', '', '[健康]保険証', 'KIỆN KHANG', 'thẻ bảo hiểm [y tế]'),
(17, 'かぜ', 'kaze', 'audio/minna/bai17/kaze.mp3', '', '', '', 'cảm, cúm'),
(17, 'ねつ', 'netsu', 'audio/minna/bai17/netsu.mp3', '', '熱', 'NHIỆT', 'sốt'),
(17, 'びょうき', 'byouki', 'audio/minna/bai17/byouki.mp3', '', '病気', 'BỆNH KHÍ', 'ốm, bệnh'),
(17, 'くすり', 'kusuri', 'audio/minna/bai17/kusuri.mp3', '', '薬', 'DƯỢC', 'thuốc'),
(17, '[お]ふろ', '[o]furo', 'audio/minna/bai17/ofuro.mp3', '', '', '', 'bồn tắm'),
(17, 'うわぎ', 'uwagi', 'audio/minna/bai17/uwagi.mp3', '', '上着', 'THƯỢNG TRƯỚC', 'áo khoác'),
(17, 'したぎ', 'shitagi', 'audio/minna/bai17/shitagi.mp3', '', '下着', 'HẠ TRƯỚC', 'quần áo lót'),
(17, 'せんせい', 'sensei', 'audio/minna/bai17/sensei.mp3', '', '先生', 'TIÊN SINH', 'thầy/ cô'),
(17, '２，３にち', '2,3nichi', 'audio/minna/bai17/23nichi.wav', '', '２，３日', 'NHẬT', 'vài ngày'),
(17, '２，３～', '2,3～', '', '', '', '', 'vài~ (“~” là hậu tố chỉ cách đếm)'),
(17, '～までに', '～madeni', 'audio/minna/bai17/madeni.mp3', '', '', '', 'trước ~ (chỉ thời hạn)'),
(17, 'ですから', 'desukara', 'audio/minna/bai17/desukara.mp3', '', '', '', 'vì thế, vì vậy, do đó'),
(17, 'どうしましたか。', 'doushimashitaka｡', 'audio/minna/bai17/doushimashitaka.mp3', '', '', '', 'Có vần đề gì?/Anh/chị bị làm sao?'),
(17, '「のどが」いたいです。', '｢nodoga｣itaidesu｡', 'audio/minna/bai17/nodogaitai.wav', '', '「のどが」痛いです。', 'THỐNG', 'Tôi bị đau [~họng].'),
(17, 'おだいじに', 'odaijini', 'audio/minna/bai17/odaijini.mp3', '', 'お大事に。', 'ĐẠI SỰ', 'Anh/chị nhớ giữ gìn sức khỏe.');