-- Bài 26
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(26, 'みます', 'mimasu', 'audio/minna/bai26/mimasu.mp3', '', '見ます, 診ます', 'KIẾN, CHẨN', 'xem, khám bệnh'),
(26, 'さがします', 'sagashimasu', 'audio/minna/bai26/sagashimasu.mp3', '', '探します,捜します', 'THÁM、SƯU', 'tìm, tìm kiếm'),
(26, '[じかんに～] おくれます', '［jikanni～］　okuremasu', 'audio/minna/bai26/okuremasu.mp3', '', '[時間に～]遅れます', 'THỜI GIAN TRÌ', 'chậm, muộn [cuộc hẹn,v.v.]'),
(26, 'やります', 'yarimasu', 'audio/minna/bai26/yarimasu.mp3', '', '', '', 'làm'),
(26, '[パーティーに～]さんかします', '［pa-ti-ni～］sankashimasu', 'audio/minna/bai26/sankashimasu.wav', '', '[パーティーに～]参加します', 'THAM GIA', 'tham gia, dự [buổi tiệc]'),
(26, 'もうしこみます', 'moushikomimasu', 'audio/minna/bai26/moushikomimasu.mp3', '', '申し込みます', 'THÂN VÀO', 'đăng ký'),
(26, 'つごうが　いい', 'tsugouga　ii', 'audio/minna/bai26/tsugougaii.mp3', '', '都合が　いい', 'ĐÔ HỢP', 'có thời gian, thuận tiện'),
(26, 'つごうが　わるい', 'tsugouga　warui', 'audio/minna/bai26/tsugougawarui.mp3', '', '都合が　悪い', 'ĐÔ HỢP ÁC', 'không có thời gian, bận, không thuận tiện'),
(26, 'きぶんがいい', 'kibungaii', 'audio/minna/bai26/kibungaii.mp3', '', '気分がいい', 'KHÍ PHÂN', 'cảm thấy tốt, cảm thấy khỏe'),
(26, 'きぶんがわるい', 'kibungawarui', 'audio/minna/bai26/kibungawarui.mp3', '', '気分が悪い', 'KHÍ PHÂN ÁC', 'cảm thấy không tốt, cảm thấy mệt'),
(26, 'しんぶんしゃ', 'shinbunsha', 'audio/minna/bai26/shinbunsha.mp3', '', '新聞社', 'TÂN VĂN XÃ', 'công ty phát hành báo, tòa soạn báo'),
(26, 'じゅうどう', 'juudou', 'audio/minna/bai26/juudou.mp3', '', '柔道', 'NHU ĐẠO', 'Judo (nhu đạo)'),
(26, 'うんどうかい', 'undoukai', 'audio/minna/bai26/undoukai.mp3', '', '運動会', 'VẬN ĐỘNG HỘI', 'hội thi thể thao'),
(26, 'ばしょ', 'basho', 'audio/minna/bai26/basyo.mp3', '', '場所', 'TRƯỜNG SỞ', 'địa điểm'),
(26, 'ボランティア', 'borantia', 'audio/minna/bai26/k_borantexia.mp3', '', '', '', 'tình nguyện viên'),
(26, '～べん', '～ben', 'audio/minna/bai26/ben.mp3', '', '～弁', 'BIỆN', 'tiếng ~, giọng ~'),
(26, 'こんど', 'kondo', 'audio/minna/bai26/kondo.mp3', '', '今度', 'KIM ĐỘ', 'lần tới'),
(26, 'ずいぶん', 'zuibun', 'audio/minna/bai26/zuibun.mp3', '', '', '', 'khá, tương đối'),
(26, 'ちょくせつ', 'chokusetsu', 'audio/minna/bai26/chokusetsu.mp3', '', '直接', 'TRỰC TIẾP', 'trực tiếp'),
(26, 'いつでも', 'itsudemo', 'audio/minna/bai26/itsudemo.mp3', '', '', '', 'lúc nào cũng'),
(26, 'どこでも', 'dokodemo', 'audio/minna/bai26/dokodemo.mp3', '', '', '', 'ở đâu cũng'),
(26, 'だれでも', 'daredemo', 'audio/minna/bai26/daredemo.mp3', '', '', '', 'ai cũng'),
(26, 'なんでも', 'nandemo', 'audio/minna/bai26/nandemo.mp3', '', '何でも', 'HÀ', 'cái gì cũng'),
(26, 'こんな～', 'konna～', 'audio/minna/bai26/konna.mp3', '', '', '', '~ như thế này'),
(26, 'そんな～', 'sonna～', 'audio/minna/bai26/sonna.mp3', '', '', '', '~ như thế đó (gần người nghe)'),
(26, 'あんな～', 'anna～', 'audio/minna/bai26/anna.mp3', '', '', '', '~ như thế kia (xa cả người nói và người nghe)'),
(26, 'ＮＨＫ', 'ＮＨＫ', 'audio/minna/bai26/NHK.mp3', '', '', '', 'Nippon Hoso Kyokai (hãng phát thanh truyền hình)'),
(26, 'こどものひ', 'kodomonohi', 'audio/minna/bai26/kodomonohi.mp3', '', 'こどもの日', 'NHẬT', 'ngày trẻ em'),
(26, 'エドヤストア', 'edoyasutoa', 'audio/minna/bai26/K_edoyasutoa.mp3', '', '', '', 'tên một cửa hàng (giả tưởng)'),
(26, '[にもつが～] かたづきます', '［nimotsuga～］　katadukimasu', 'audio/minna/bai26/katadukimasu.mp3', '', '[荷物が～] 片付きます', 'HÀ VẬT PHIẾN PHÓ', 'được dọn dẹp ngăn nắp, gọn gàng [đồ đạc ~]'),
(26, 'ごみ', 'gomi', 'audio/minna/bai26/gomi.mp3', '', '', '', 'rác'),
(26, 'だします', 'dashimasu', 'audio/minna/bai26/dashimasu.mp3', '', '[ごみを～] 出します', 'XUẤT', 'đổ, để [rác]'),
(26, 'もえます', 'moemasu', 'audio/minna/bai26/moemasu.mp3', '', '[ごみが～] 燃えます', 'NHIÊN', 'cháy được [rác ~]'),
(26, 'げっ・すい・きん', 'gessuikin', 'audio/minna/bai26/getsusuikin.mp3', '', '月・水・金', 'NGUYỆT THỦY KIM', 'thứ hai, thứ tư, thứ sáu'),
(26, 'おきば', 'okiba', 'audio/minna/bai26/okiba.mp3', '', '置き場', 'TRÍ TRƯỜNG', 'nơi để'),
(26, 'よこ', 'yoko', 'audio/minna/bai26/yoko.mp3', '', '横', 'HOÀNH', 'bên cạnh'),
(26, 'びん', 'bin', 'audio/minna/bai26/bin.mp3', '', '瓶', 'BÌNH', 'cái chai'),
(26, 'かん', 'kan', 'audio/minna/bai26/kan.mp3', '', '缶', 'PHẪU', 'cái lon, hộp kim loại'),
(26, '「お」ゆ', '「o」yu', 'audio/minna/bai26/oyu.mp3', '', '[お]湯', 'THANG', 'nước nóng'),
(26, 'ガス', 'gasu', 'audio/minna/bai26/k_gasu.mp3', '', '', '', 'ga'),
(26, '～がいしゃ', '～gaisha', 'audio/minna/bai26/gaisya.mp3', '', '～会社', 'HỘI XÃ', 'công ty ~'),
(26, 'れんらくします', 'renrakushimasu', 'audio/minna/bai26/renrakushimasu.mp3', '', '連絡します', 'LIÊN LẠC', 'liên lạc'),
(26, 'こまったなあ。', 'komattanaa', 'audio/minna/bai26/komattanaa.mp3', '', '困ったなあ。', 'KHỐN', 'Làm thế nào đây!/ căng quá nhỉ!/ gay quá!'),
(26, 'でんしメール', 'denshime-ru', 'audio/minna/bai26/denshimeru.wav', '', '電子メール', 'ĐIỆN TỬ', 'thư điện tử, e-mail'),
(26, 'うちゅう', 'uchuu', 'audio/minna/bai26/uchu.wav', '', '宇宙', 'VŨ TRỤ', 'vũ trụ'),
(26, 'こわい', 'kowai', 'audio/minna/bai26/kowai.wav', '', '怖い', 'BỐ', 'sợ'),
(26, 'うちゅうせん', 'uchuusen', 'audio/minna/bai26/uchusen.wav', '', '宇宙船', 'VŨ TRỤ THUYỀN', 'tàu vũ trụ'),
(26, 'べつの', 'betsuno', 'audio/minna/bai26/betsuno.wav', '', '別の', 'BIỆT', 'khác'),
(26, 'うちゅうひこうし', 'uchuuhikoushi', 'audio/minna/bai26/uchuhikoushi.wav', '', '宇宙飛行士', 'VŨ TRỤ PHI HÀNH SĨ', 'nhà du hành vũ trụ'),
(26, 'どいたかお', 'doitakao', 'audio/minna/bai26/doitakao.wav', '', '土井隆雄', 'THỔ TỈNH LONG HÙNG', 'nhà du hành vũ trụ người Nhật (1954- )');