-- Bài 37
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(37, 'ほめます', 'homemasu', 'audio/minna/bai37/homemasu.mp3', '', '褒めます', 'BAO', 'khen'),
(37, 'しかります', 'shikarimasu', 'audio/minna/bai37/shikarimasu.mp3', '', '', '', 'mắng'),
(37, 'さそいます', 'sasoimasu', 'audio/minna/bai37/sasoimasu.mp3', '', '誘います', 'DỤ', 'mời, rủ'),
(37, 'おこします', 'okoshimasu', 'audio/minna/bai37/okoshimasu.mp3', '', '起こします', 'KHỞI', 'đánh thức'),
(37, 'しょうたいします', 'shoutaishimasu', 'audio/minna/bai37/syoutaishimasu.mp3', '', '招待します', 'CHIÊU ĐÃI', 'mời'),
(37, 'たのみます', 'tanomimasu', 'audio/minna/bai37/tanomimasu.mp3', '', '頼みます', 'LẠI', 'nhờ'),
(37, 'ちゅういします', 'chuuishimasu', 'audio/minna/bai37/chuuishimasu.mp3', '', '注意します', 'CHÚ Ý', 'chú ý, nhắc nhở'),
(37, 'とります', 'torimasu', 'audio/minna/bai37/torimasu.mp3', '', '', '', 'ăn trộm, lấy cắp'),
(37, 'ふみます', 'fumimasu', 'audio/minna/bai37/fumimasu.mp3', '', '踏みます', 'ĐẠP', 'giẫm, giẫm lên, giẫm vào'),
(37, 'こわします', 'kowashimasu', 'audio/minna/bai37/kowashimasu.mp3', '', '壊します', 'HOẠI', 'phá, làm hỏng'),
(37, 'よごします', 'yogoshimasu', 'audio/minna/bai37/yogoshimasu.mp3', '', '汚します', 'Ô', 'làm bẩn'),
(37, 'おこないます', 'okonaimasu', 'audio/minna/bai37/okonaimasu.mp3', '', '行います', 'HÀNH', 'thực hiện, tiến hành'),
(37, 'ゆしゅつします', 'yushutsushimasu', 'audio/minna/bai37/yusyutsushimasu.mp3', '', '輸出します', 'THÂU XUẤT', 'xuất khẩu'),
(37, 'ゆにゅうします', 'yunyuushimasu', 'audio/minna/bai37/yunyuushimasu.mp3', '', '輸入します', 'THÂU NHẬP', 'nhập khẩu'),
(37, 'ほんやくします', 'honyakushimasu', 'audio/minna/bai37/honyakushimasu.mp3', '', '翻訳します', 'PHIÊN DỊCH', 'dịch (sách, tài liệu)'),
(37, 'はつめいします', 'hatsumeishimasu', 'audio/minna/bai37/hatsumeishimasu.mp3', '', '発明します', 'PHÁT MINH', 'phát minh'),
(37, 'はっけんします', 'hakkenshimasu', 'audio/minna/bai37/hakkenshimasu.mp3', '', '発見します', 'PHÁT KIẾN', 'phát kiến, tìm ra, tìm thấy'),
(37, 'せっけいします', 'sekkeishimasu', 'audio/minna/bai37/sekkeishimasu.mp3', '', '設計します', 'THIẾT KẾ', 'thiết kế'),
(37, 'こめ', 'kome', 'audio/minna/bai37/kome.mp3', '', '米', 'MỄ', 'gạo'),
(37, 'むぎ', 'mugi', 'audio/minna/bai37/mugi.mp3', '', '麦', 'MẠCH', 'lúa mạch'),
(37, 'せきゆ', 'sekiyu', 'audio/minna/bai37/sekiyu.mp3', '', '石油', 'THẠCH DU', 'dầu mỏ'),
(37, 'げんりょう', 'genryou', 'audio/minna/bai37/genryou.mp3', '', '原料', 'NGUYÊN LIỆU', 'nguyên liệu'),
(37, 'デート', 'de-to', 'audio/minna/bai37/k_deeto.mp3', '', '', '', 'cuộc hẹn hò (của nam nữ)'),
(37, 'どろぼう', 'dorobou', 'audio/minna/bai37/dorobou.mp3', '', '泥棒', 'NÊ BỔNG', 'kẻ trộm'),
(37, 'けいかん', 'keikan', 'audio/minna/bai37/keikan.mp3', '', '警官', 'CẢNH QUAN', 'cảnh sát'),
(37, 'けんちくか', 'kenchikuka', 'audio/minna/bai37/kenchikuka.mp3', '', '建築家', 'KIẾN TRÚC GIA', 'kiến trúc sư'),
(37, 'かがくしゃ', 'kagakusha', 'audio/minna/bai37/kagakusya.mp3', '', '科学者', 'KHOA HỌC GIẢ', 'nhà khoa học'),
(37, 'まんが', 'manga', 'audio/minna/bai37/manga.mp3', '', '漫画', 'MẠN HỌA', 'truyện tranh'),
(37, 'せかいじゅう', 'sekaijuu', 'audio/minna/bai37/sekaijuu.mp3', '', '世界中', 'THẾ GIỚI TRUNG', 'khắp thế giới, toàn thế giới'),
(37, '～じゅう', '～juu', 'audio/minna/bai37/juu.mp3', '', '～中', 'TRUNG', 'khắp ~, toàn ~'),
(37, '～によって', '～niyotte', 'audio/minna/bai37/niyotte.mp3', '', '', '', 'do ~'),
(37, 'よかったですね。', 'yokattadesune', 'audio/minna/bai37/yokattadesune.mp3', '', '', '', 'May nhỉ./ may cho anh/chị nhỉ.'),
(37, 'ドミニカ', 'dominika', 'audio/minna/bai37/dominika.wav', '', '', '', 'Dominica, tên một quốc gia ở Trung Mỹ'),
(37, 'ライトきょうだい', 'raitokyoudai', 'audio/minna/bai37/raitokyoudai.wav', '', 'ライト兄弟', 'HUYNH ĐỆ', 'anh em nhà Wright, hai anh em người Mỹ đi tiên phong trong ngành hàng không Wilbur Wright (1867-1912) và Orville Wright (1871-1948)'),
(37, 'げんじものがたり', 'genjimonogatari', 'audio/minna/bai37/genjimonogatari.wav', '', '源氏物語', 'NGUYÊN THỊ VẬT NGỮ', '“chuyện Genji”'),
(37, 'むらさきしきぶ', 'murasakishikibu', 'audio/minna/bai37/murashakishikibu.wav', '', '紫式部', 'TỬ THỨC BỘ', 'Nữ tác giả viết “chuyện Genji” sống trong thời Heian'),
(37, 'グラハム・ベル', 'gurahamu・beru', 'audio/minna/bai37/gurahamuberu.wav', '', '', '', 'Alexander Graham Bell (1847-1922), nhà phát minh người Mỹ'),
(37, 'とうしょうぐう', 'toushouguu', 'audio/minna/bai37/toushouguu.wav', '', '東照宮', 'ĐÔNG CHIẾU CUNG', 'tên đền thờ Tokugawa Ieyasu ở Nikko, tỉnh Tochigi'),
(37, 'えどじだい', 'edojidai', 'audio/minna/bai37/edojidai.wav', '', '江戸時代', 'GIANG HỘ THỜI ĐẠI', 'thời Edo (1603-1868)'),
(37, 'サウジアラビア', 'saujiarabia', 'audio/minna/bai37/saujiarabia.wav', '', '', '', 'Ả-rập Xê-út (Saudi Arabia)'),
(37, 'うめたてます', 'umetatemasu', 'audio/minna/bai37/umetatemasu.wav', '', '埋め立てます', 'MAI LẬP', 'lấp (biển)'),
(37, 'ぎじゅつ', 'gijutsu', 'audio/minna/bai37/gijutsu.wav', '', '技術', 'KỸ THUẬT', 'kỹ thuật'),
(37, 'とち', 'tochi', 'audio/minna/bai37/tochi.wav', '', '土地', 'THỔ ĐỊA', 'đất, diện tích đất'),
(37, 'そうおん', 'souon', 'audio/minna/bai37/souon.wav', '', '騒音', 'TAO ÂM', 'tiếng ồn'),
(37, 'りようします', 'riyoushimasu', 'audio/minna/bai37/riyoushimasu.wav', '', '利用します', 'LỢI DỤNG', 'lợi dụng, sử dụng'),
(37, 'アクセス', 'akusesu', 'audio/minna/bai37/akusesu.wav', '', '', '', 'nối, giao thông đi đến'),
(37, '―せいき', '-seiki', 'audio/minna/bai37/seiki.wav', '', '―世紀', 'THẾ KỶ', 'thế kỷ -'),
(37, 'ごうか「な」', 'gouka「na」', 'audio/minna/bai37/gouka.wav', '', '豪華[な]', 'HÀO HOA', 'hào hoa, sang trọng'),
(37, 'ちょうこく', 'choukoku', 'audio/minna/bai37/choukoku.wav', '', '彫刻', 'ĐIÊU KHẮC', 'điêu khắc'),
(37, 'ねむります', 'nemurimasu', 'audio/minna/bai37/nemurimasu.wav', '', '眠ります', 'MIÊN', 'ngủ'),
(37, 'ほります', 'horimasu', 'audio/minna/bai37/horimasu.wav', '', '彫ります', 'ĐIÊU', 'khắc'),
(37, 'なかま', 'nakama', 'audio/minna/bai37/nakama.wav', '', '仲間', 'TRỌNG GIAN', 'bạn bè, đồng nghiệp'),
(37, 'そのあと', 'sonoato', 'audio/minna/bai37/sonoato.wav', '', '', '', 'sau đó'),
(37, 'いっしょうけんめい', 'isshoukenmei', 'audio/minna/bai37/isshokenmei.wav', '', '一生懸命', 'NHẤT SINH HUYỀN MỆNH', '(cố gắng) hết sức, chăm chỉ, miệt mài'),
(37, 'ねずみ', 'nezumi', 'audio/minna/bai37/nezum.wav', '', '', '', 'con chuột'),
(37, 'いっぴきもいません。', 'ippikimoimasen', 'audio/minna/bai37/ippikimoimasen.wav', '', '一匹もいません。', '', 'Không có con nào cả.'),
(37, 'ねむりねこ', 'nemurineko', 'audio/minna/bai37/nemurineko.wav', '', '眠り猫', 'MIÊN MIÊU', '“con mèo ngủ”, tác phẩm điêu khắc của Jingoro ở Tosho-gu'),
(37, 'ひだりじんごろう', 'hidarijingorou', 'audio/minna/bai37/hidarijingorou.wav', '', '左甚五郎', 'TẢ THẬM NGŨ LANG', 'tên một nhà điêu khắc nỗi tiếng thời Edo (1594-1651)');