-- Bài 33
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(33, 'にげます', 'nigemasu', 'audio/minna/bai33/nigemasu.mp3', '', '逃げます', 'ĐÀO', 'chạy trốn, bỏ chạy'),
(33, 'さわぎます', 'sawagimasu', 'audio/minna/bai33/sawagimasu.mp3', '', '騒ぎます', 'TAO', 'làm ồn, làm rùm beng'),
(33, 'あきらめます', 'akiramemasu', 'audio/minna/bai33/akiramemasu.mp3', '', '', '', 'từ bỏ, đầu hàng'),
(33, 'なげます', 'nagemasu', 'audio/minna/bai33/nagemasu.mp3', '', '投げます', 'ĐẦU', 'ném'),
(33, 'まもります', 'mamorimasu', 'audio/minna/bai33/mamorimasu.mp3', '', '守ります', 'THỦ', 'bảo vệ, tuân thủ, giữ'),
(33, 'あげます', 'agemasu', 'audio/minna/bai33/agemasu.mp3', '', '上げます', 'THƯỢNG', 'nâng, nâng lên, tăng lên'),
(33, 'さげます', 'sagemasu', 'audio/minna/bai33/sagemasu.mp3', '', '下げます', 'HẠ', 'hạ, hạ xuống, giảm xuống'),
(33, 'つたえます', 'tsutaemasu', 'audio/minna/bai33/tsutaemasu.mp3', '', '伝えます', 'TRUYỀN', 'truyền, truyền đạt'),
(33, '[くるまに～]ちゅういします', '［kurumani～］chuuishimasu', 'audio/minna/bai33/chyuuishimasu.mp3', '', '[車に～]注意します', 'XA CHÚ Ý', 'chú ý [ô tô]'),
(33, '[せきを～] はずします', '［sekiwo～］　hazushimasu', 'audio/minna/bai33/hazushimasu.mp3', '', '[席を～]外します', 'TỊCH NGOẠI', 'rời, không có ở [chỗ ngồi]'),
(33, 'だめ[な]', 'dame［na］', 'audio/minna/bai33/dame.mp3', '', '', '', 'hỏng, không được, không thể'),
(33, 'せき', 'seki', 'audio/minna/bai33/seki.mp3', '', '席', 'TỊCH', 'chỗ ngồi, ghế'),
(33, 'ファイト', 'faito', 'audio/minna/bai33/k_fuxaito.mp3', '', '', '', '“quyết chiến”, “cố lên”'),
(33, 'マーク', 'ma-ku', 'audio/minna/bai33/k_maaku.mp3', '', '', '', 'ký hiệu (Mark)'),
(33, 'ボール', 'bo-ru', 'audio/minna/bai33/k_booru.mp3', '', '', '', 'quả bóng'),
(33, 'せんたくき', 'sentakuki', 'audio/minna/bai33/sentakuki.mp3', '', '洗濯機', 'TẨY TRẠC CƠ', 'máy giặt'),
(33, '～き', '～ki', 'audio/minna/bai33/ki.mp3', '', '～機', 'CƠ', 'máy ~'),
(33, 'きそく', 'kisoku', 'audio/minna/bai33/kisoku.mp3', '', '規則', 'QUY TẮC', 'quy tắc, kỷ luật'),
(33, 'しようきんし', 'shiyoukinshi', 'audio/minna/bai33/shiyoukinshi.mp3', '', '使用禁止', 'SỬ DỤNG CẤM CHỈ', 'cấm sử dụng'),
(33, 'たちいりきんし', 'tachiirikinshi', 'audio/minna/bai33/tachiirikinshi.mp3', '', '立入禁止', 'LẬP NHẬP CẤM CHỈ', 'cấm vào'),
(33, 'いりぐち', 'iriguchi', 'audio/minna/bai33/iriguchi.mp3', '', '入口', 'NHẬP KHẨU', 'cửa vào'),
(33, 'でぐち', 'deguchi', 'audio/minna/bai33/deguchi.mp3', '', '出口', 'XUẤT KHẨU', 'cửa ra'),
(33, 'ひじょうぐち', 'hijouguchi', 'audio/minna/bai33/hijouguchi.mp3', '', '非常口', 'PHI THƯỜNG KHẨU', 'cửa thoát hiểm'),
(33, 'むりょう', 'muryou', 'audio/minna/bai33/muryou.mp3', '', '無料', 'VÔ LIỆU', 'miễn phí'),
(33, 'ほんじつきゅうぎょう', 'honjitsukyuugyou', 'audio/minna/bai33/honjitsukyuugyou.mp3', '', '本日休業', 'BẢN NHẬT HƯU NGHIỆP', 'hôm nay đóng cửa, hôm nay nghỉ'),
(33, 'えいぎょうちゅう', 'eigyouchuu', 'audio/minna/bai33/eigyouchuu.mp3', '', '営業中', 'DOANH NGHIỆP TRUNG', 'đang mở cửa'),
(33, 'しようちゅう', 'shiyouchuu', 'audio/minna/bai33/shiyouchuu.mp3', '', '使用中', 'SỬ DỤNG TRUNG', 'đang sử dụng'),
(33, '～ちゅう', '～chuu', 'audio/minna/bai33/chyu.mp3', '', '～中', 'TRUNG', 'đang ~'),
(33, 'どういう～', 'douiu～', 'audio/minna/bai33/douiu.mp3', '', '', '', '~ gì, ~ thế nào'),
(33, 'もう', 'mou', 'audio/minna/bai33/mou.mp3', '', '', '', 'không ~ nữa'),
(33, 'あと～', 'ato～', 'audio/minna/bai33/ato.mp3', '', '', '', 'còn ~'),
(33, 'ちゅうしゃいはん', 'chuushaihan', 'audio/minna/bai33/chuusyaihan.mp3', '', '駐車違反', 'TRÚ XA VI PHẢN', 'đỗ xe trái phép'),
(33, 'そりゃあ', 'soryaa', 'audio/minna/bai33/soryaa.mp3', '', '', '', 'thế thì, ồ'),
(33, '～いない', '～inai', 'audio/minna/bai33/inai.mp3', '', '～以内', 'DĨ NỘI', 'trong khoảng ~, trong vòng ~'),
(33, 'けいさつ', 'keisatsu', 'audio/minna/bai33/keisatsu.mp3', '', '警察', 'CẢNH SÁT', 'cảnh sát'),
(33, 'ばっきん', 'bakkin', 'audio/minna/bai33/bakkin.mp3', '', '罰金', 'PHẠT KIM', 'tiền phạt'),
(33, 'でんぽう', 'denpou', 'audio/minna/bai33/denpou.wav', '', '電報', 'ĐIỆN BÁO', 'bức điện, điện báo'),
(33, 'ひとびと', 'hitobito', 'audio/minna/bai33/hitobito.wav', '', '人々', 'NHÂN(KÉP)', 'người, những người'),
(33, 'きゅうよう', 'kyuuyou', 'audio/minna/bai33/kyuyou.wav', '', '急用', 'CẤP DỤNG', 'việc gấp, việc khẩn'),
(33, 'うちます', 'uchimasu', 'audio/minna/bai33/uchimasu.wav', '', '[電報を～]打ちます', 'ĐIỆN BÁO ĐẢ', 'gửi [bức điện]'),
(33, 'でんぽうだい', 'denpoudai', 'audio/minna/bai33/denpoudai.wav', '', '電報代', 'ĐIỆN BÁO ĐẠI', 'tiền cước điện báo'),
(33, 'できるだけ', 'dekirudake', 'audio/minna/bai33/dekirudake.wav', '', '', '', 'cố gắng, trong khả năng có thể'),
(33, 'みじかく', 'mijikaku', 'audio/minna/bai33/mijikaku.wav', '', '短く', 'ĐOẢN', 'ngắn gọn, đơn giản'),
(33, 'また', 'mata', 'audio/minna/bai33/mata.wav', '', '', '', 'thêm nữa'),
(33, 'たとえば', 'tatoeba', 'audio/minna/bai33/tatoeba.wav', '', '例えば', 'LỆ', 'ví dụ'),
(33, 'キトク', 'kitoku', 'audio/minna/bai33/kitoku.wav', '', '（危篤）', 'NGUY ĐỐC', 'tình trạng hiểm nghèo'),
(33, 'おもいびょうき', 'omoibyouki', 'audio/minna/bai33/omoibyouki.wav', '', '重い病気', 'TRỌNG BỆNH KHÍ', 'bệnh nặng'),
(33, 'あす', 'asu', 'audio/minna/bai33/asu.wav', '', '明日', 'MINH NHẬT', 'ngày mai'),
(33, 'るす', 'rusu', 'audio/minna/bai33/rusu.wav', '', '留守', 'LƯU THỦ', 'vắng nhà'),
(33, 'るすばん', 'rusuban', 'audio/minna/bai33/rusuban.wav', '', '留守番', 'LƯU THỦ PHIÊN', 'trông nhà, giữ nhà'),
(33, '「お」いわい', '「o」iwai', 'audio/minna/bai33/oiwai.wav', '', '[お]祝い', 'CHÚC', 'việc mừng, vật mừng'),
(33, 'なくなります', 'nakunarimasu', 'audio/minna/bai33/nakunarimasu.wav', '', '亡くなります', 'VONG', 'chết, mất'),
(33, 'かなしみ', 'kanashimi', 'audio/minna/bai33/kanashimi.wav', '', '悲しみ', 'BI', 'buồn'),
(33, 'りようします', 'riyoushimasu', 'audio/minna/bai33/riyoushimasu.wav', '', '利用します', 'LỢI DỤNG', 'sử dụng, lợi dụng, tận dụng, dùng');