-- Bài 35
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(35, '[はなが～]さきます', '［hanaga～］sakimasu', 'audio/minna/bai35/sakimasu.mp3', '', '[花が～]咲きます', 'HOA TIẾU', 'nở [hoa ~]'),
(35, '[いろが～] かわります', '［iroga～］kawarimasu', 'audio/minna/bai35/kawarimasu.mp3', '', '[色が～] 変わります', 'SẮC BIẾN', 'thay đổi, đổi [màu]'),
(35, 'こまります', 'komarimasu', 'audio/minna/bai35/komarimasu.mp3', '', '困ります', 'KHỐN', 'rắc rối, khó xử, có vấn đề'),
(35, '[まるを～] つけます', '［maruwo～］tsukemasu', 'audio/minna/bai35/tsukemasu.mp3', '', '[丸を～]付けます', 'HOÀN PHÓ', 'vẽ, đánh dấu [tròn]'),
(35, 'ひろいます', 'hiroimasu', 'audio/minna/bai35/hiroimasu.mp3', '', '拾います', 'THẬP', 'nhặt, nhặt lên'),
(35, '[でんわが～]かかります', '［denwaga～］kakarimasu', 'audio/minna/bai35/kakarimasu.mp3', '', '[電話が～]', 'ĐIỆN THOẠI', 'có điện thoại'),
(35, 'らく[な]', 'raku［na］', 'audio/minna/bai35/raku.mp3', '', '楽[な]', 'LẠC/NHẠC', 'thoải mái, nhàn hạ, dễ dàng'),
(35, 'ただしい', 'tadashii', 'audio/minna/bai35/tadashii.mp3', '', '正しい', 'CHÍNH', 'đúng, chính xác'),
(35, 'めずらしい', 'mezurashii', 'audio/minna/bai35/mezurashii.mp3', '', '珍しい', 'TRÂN', 'hiếm, hiếm có'),
(35, 'かた', 'kata', 'audio/minna/bai35/kata.mp3', '', '方', 'PHƯƠNG', 'vị, người (cách nói kính trọng của ひと)'),
(35, 'むこう', 'mukou', 'audio/minna/bai35/mukou.mp3', '', '向こう', 'HƯỚNG', 'bên kia, bên đấy, phía đằng kia'),
(35, 'しま', 'shima', 'audio/minna/bai35/shima.mp3', '', '島', 'ĐẢO', 'đảo, hòn đảo'),
(35, 'むら', 'mura', 'audio/minna/bai35/mura.mp3', '', '村', 'THÔN', 'làng'),
(35, 'みなと', 'minato', 'audio/minna/bai35/minato.mp3', '', '港', 'CẢNG', 'cảng, bến cảng'),
(35, 'きんじょ', 'kinjo', 'audio/minna/bai35/kinjo.mp3', '', '近所', 'CẬN SỞ', 'hàng xóm, khu vực lân cận'),
(35, 'おくじょう', 'okujou', 'audio/minna/bai35/okujou.mp3', '', '屋上', 'ỐC THƯỢNG', 'mái nhà, nóc nhà'),
(35, 'かいがい', 'kaigai', 'audio/minna/bai35/kaigai.mp3', '', '海外', 'HẢI NGOẠI', 'nước ngoài hải ngoại'),
(35, 'やまのぼり', 'yamanobori', 'audio/minna/bai35/yamanobori.mp3', '', '山登り', 'SƠN ĐĂNG', 'leo núi'),
(35, 'ハイキング', 'haikingu', 'audio/minna/bai35/k_haikingu.mp3', '', '', '', 'leo núi, đi bộ trên núi'),
(35, 'きかい', 'kikai', 'audio/minna/bai35/kikai.mp3', '', '機会', 'CƠ HỘI', 'cơ hội'),
(35, 'きょか', 'kyoka', 'audio/minna/bai35/kyoka.mp3', '', '許可', 'HỨA KHẢ', 'phép, giấy phép'),
(35, 'まる', 'maru', 'audio/minna/bai35/maru.mp3', '', '丸', 'HOÀN', 'tròn, vòng tròn'),
(35, 'そうさ', 'sousa', 'audio/minna/bai35/sousa.mp3', '', '操作', 'THAO TÁC', 'thao tác'),
(35, 'ほうほう', 'houhou', 'audio/minna/bai35/houhou.mp3', '', '方法', 'PHƯƠNG PHÁP', 'phương pháp'),
(35, 'せつび', 'setsubi', 'audio/minna/bai35/setsubi.mp3', '', '設備', 'THIẾT BỊ', 'thiết bị'),
(35, 'カーテン', 'ka-ten', 'audio/minna/bai35/k_kaaten.mp3', '', '', '', 'cái rèm'),
(35, 'ひも', 'himo', 'audio/minna/bai35/himo.mp3', '', '', '', 'sợi dây'),
(35, 'ふた', 'futa', 'audio/minna/bai35/futa.mp3', '', '', '', 'cái nắp'),
(35, 'は', 'ha', 'audio/minna/bai35/ha.mp3', '', '葉', 'DIỆP', 'cái lá'),
(35, 'きょく', 'kyoku', 'audio/minna/bai35/kyoku.mp3', '', '曲', 'KHÚC', 'bài hát, bản nhạc'),
(35, 'たのしみ', 'tanoshimi', 'audio/minna/bai35/tanoshimi.mp3', '', '楽しみ', 'NHẠC', 'niềm vui, điều vui'),
(35, 'もっと', 'motto', 'audio/minna/bai35/motto.mp3', '', '', '', 'hơn, nữa'),
(35, 'はじめに', 'hajimeni', 'audio/minna/bai35/hajimeni.mp3', '', '初めに', 'SƠ', 'đầu tiên, trước hết'),
(35, 'これでおわります。', 'koredeowarimasu', 'audio/minna/bai35/koredeowarimasu.mp3', '', 'これで終わります。', 'CHUNG', 'Đến đây là hết./ Chúng ta dừng lại ở đây.'),
(35, 'はこね', 'hakone', 'audio/minna/bai35/hakone.wav', '', '箱根', 'TƯƠNG CĂN', 'một địa điểm nghỉ ngơi ở tỉnh Kanagawa'),
(35, 'にっこう', 'nikkou', 'audio/minna/bai35/nikkou.wav', '', '日光', 'NHẬT QUANG', 'một địa điểm du lịch ở Tochigi'),
(35, 'しろうま', 'shirouma', 'audio/minna/bai35/shirouma.wav', '', '白馬', 'BẠCH MÃ', 'một địa điểm du lịch ở tỉnh Nagano'),
(35, 'アフリカ', 'afurika', 'audio/minna/bai35/afurika.wav', '', '', '', 'châu Phi (Africa)'),
(35, 'それなら', 'sorenara', 'audio/minna/bai35/sorenara.mp3', '', '', '', 'nếu thế thì, vậy thì'),
(35, 'やこうバス', 'yakoubasu', 'audio/minna/bai35/yakoubasu.mp3', '', '夜行バス', 'DẠ HÀNH', '(chuyến) xe buýt chạy đêm'),
(35, 'りょこうしゃ', 'ryokousha', 'audio/minna/bai35/ryokousya.mp3', '', '旅行社', 'LỮ HÀNH XÃ', 'công ty du lịch'),
(35, 'くわしい', 'kuwashii', 'audio/minna/bai35/kuwashii.mp3', '', '詳しい', 'TƯỜNG', 'cụ thể, chi tiết'),
(35, 'スキーじょう', 'suki-jou', 'audio/minna/bai35/k_sukiijou.mp3', '', 'スキー場', 'TRƯỜNG', 'địa điểm trượt tuyết, bãi trượt tuyết'),
(35, 'くさつ', 'kusatsu', 'audio/minna/bai35/kusatsu.wav', '', '草津', 'THẢO TÂN', 'một địa điểm du lịch ở tỉnh Gunma'),
(35, 'しがこうげん', 'shigakougen', 'audio/minna/bai35/shigakogen.wav', '', '志賀高原', 'CHÍ HẠ CAO NGUYÊN', 'một công viên quốc gia ở tỉnh Nagano'),
(35, 'しゅ', 'shu', 'audio/minna/bai35/shu.wav', '', '朱', 'CHÂU/CHU', 'đỏ, màu đỏ'),
(35, 'まじわります', 'majiwarimasu', 'audio/minna/bai35/majiwarimasu.wav', '', '交わります', 'GIAO', 'giao lưu với, quan hệ với'),
(35, 'ことわざ', 'kotowaza', 'audio/minna/bai35/kotowaza.wav', '', '', '', 'ngạn ngữ, tục ngữ (proverb)'),
(35, 'なかよくします', 'nakayokushimasu', 'audio/minna/bai35/nakayokushimasu.wav', '', '仲よくします', 'TRỌNG', 'quan hệ tốt với, chơi thân với'),
(35, 'ひつよう「な」', 'hitsuyou「na」', 'audio/minna/bai35/hitsuyou.wav', '', '必要[な]', 'TẤT YẾU', 'cần thiết');