-- Bài 44
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(44, 'なきます', 'nakimasu', 'audio/minna/bai44/nakimasu.mp3', '', '泣きます', 'KHẤP', 'khóc'),
(44, 'わらいます', 'waraimasu', 'audio/minna/bai44/waraimasu.mp3', '', '笑います', 'TIẾU', 'cười'),
(44, 'かわきます', 'kawakimasu', 'audio/minna/bai44/kawakimasu.mp3', '', '乾きます', 'CAN', 'khô'),
(44, 'ぬれます', 'nuremasu', 'audio/minna/bai44/nuremasu.mp3', '', '', '', 'ướt'),
(44, 'すべります', 'suberimasu', 'audio/minna/bai44/suberimasu.mp3', '', '滑ります', 'HOẠT', 'trượt'),
(44, '[じこが～]おきます', '［jikoga～］okimasu', 'audio/minna/bai44/okimasu.mp3', '', '[事故が～]起きます', 'SỰ CỐ KHỞI', 'xảy ra [tai nạn ~]'),
(44, 'ちょうせつします', 'chousetsushimasu', 'audio/minna/bai44/chousetsushimasu.mp3', '', '調節します', 'ĐIỀU TIẾT', 'điều tiết, điều chỉnh'),
(44, 'あんぜん[な]', 'anzen［na］', 'audio/minna/bai44/anzen.mp3', '', '安全[な]', 'AN TOÀN', 'an toàn'),
(44, 'ていねい[な]', 'teinei［na］', 'audio/minna/bai44/teinei.mp3', '', '丁寧[な]', 'ĐINH NINH', 'lịch sự, cẩn thận'),
(44, 'こまかい', 'komakai', 'audio/minna/bai44/komakai.mp3', '', '細かい', 'TẾ', 'chi tiết, tỉ mỉ, nhỏ'),
(44, 'こい', 'koi', 'audio/minna/bai44/koi.mp3', '', '濃い', 'NỒNG', 'nồng, đậm'),
(44, 'うすい', 'usui', 'audio/minna/bai44/usui.mp3', '', '薄い', 'BẠC', 'nhạt'),
(44, 'くうき', 'kuuki', 'audio/minna/bai44/kuuki.mp3', '', '空気', 'KHÔNG KHÍ', 'không khí'),
(44, 'なみだ', 'namida', 'audio/minna/bai44/namida.mp3', '', '涙', 'LỆ', 'nước mắt'),
(44, 'わしょく', 'washoku', 'audio/minna/bai44/wasyoku.mp3', '', '和食', 'HÒA THỰC', 'món ăn Nhật'),
(44, 'ようしょく', 'youshoku', 'audio/minna/bai44/yousyoku.mp3', '', '洋食', 'DƯƠNG THỰC', 'món ăn Âu Mỹ'),
(44, 'おかず', 'okazu', 'audio/minna/bai44/okazu.wav', '', '', '', 'thức ăn'),
(44, 'りょう', 'ryou', 'audio/minna/bai44/ryou.mp3', '', '量', 'LƯỢNG', 'lượng'),
(44, '―ばい', '-bai', 'audio/minna/bai44/bai.mp3', '', '―倍', 'BỘI', '- lần'),
(44, 'はんぶん', 'hanbun', 'audio/minna/bai44/hanbun.mp3', '', '半分', 'BÁN PHÂN', 'một nửa'),
(44, 'シングル', 'shinguru', 'audio/minna/bai44/k_shiguru.mp3', '', '', '', 'phòng đơn (1 giường)'),
(44, 'ツイン', 'tsuin', 'audio/minna/bai44/k_tsuin.mp3', '', '', '', 'phòng đôi (2 giường)'),
(44, 'たんす', 'tansu', 'audio/minna/bai44/tansu.mp3', '', '', '', 'tủ đựng quần áo'),
(44, 'せんたくもの', 'sentakumono', 'audio/minna/bai44/sentakumono.mp3', '', '洗濯物', 'TẨY TRẠC VẬT', 'quần áo giặt'),
(44, 'りゆう', 'riyuu', 'audio/minna/bai44/riyuu.mp3', '', '理由', 'LÝ DO', 'lý do'),
(44, 'どうなさいますか。', 'dounasaimasuka', 'audio/minna/bai44/dounasaimasuka.mp3', '', '', '', 'Anh/chị định như thế nào?'),
(44, 'カット', 'katto', 'audio/minna/bai44/katto.wav', '', '', '', 'cắt tóc'),
(44, 'シャンプー', 'shanpu-', 'audio/minna/bai44/k_syanpuu.mp3', '', '', '', 'gội đầu'),
(44, 'どういうふうになさいますか。', 'douiufuuninasaimasuka', 'audio/minna/bai44/douiufuuninasaimasuka.mp3', '', '', '', 'Anh/chị định ~ như thế nào?'),
(44, 'ショート', 'sho-to', 'audio/minna/bai44/k_syouto.mp3', '', '', '', 'kiểu ngắn'),
(44, '～みたいに　して　ください。', '～mitaini　shite　kudasai', 'audio/minna/bai44/mitainishitekudasai.mp3', '', '', '', 'Hãy cắt như ~.'),
(44, 'これでよろしいでしょうか。', 'koredeyoroshiideshouka', 'audio/minna/bai44/koredeyoroshidesyouka.mp3', '', '', '', 'Thế này đã được chưa ạ?'),
(44, '「どうも」おつかれさまでした。', '「doumo」otsukaresamadeshita', 'audio/minna/bai44/otsukaresamadeshita.mp3', '', '[どうも]お疲れ様でした。', 'BÌ DẠNG', 'Cám ơn anh/chị.'),
(44, 'いやがります', 'iyagarimasu', 'audio/minna/bai44/iyagarimasu.wav', '', '嫌がります', 'HIỀM', 'không thích, tỏ thái độ không thích'),
(44, 'また', 'mata', 'audio/minna/bai44/mata.wav', '', '', '', 'thêm nữa'),
(44, 'じゅんじょ', 'junjo', 'audio/minna/bai44/junjo.wav', '', '順序', 'THUẬN TỰ', 'thứ tự'),
(44, 'ひょうげん', 'hyougen', 'audio/minna/bai44/hyougen.wav', '', '表現', 'BIỂU HIỆN', 'cách nói, cách diễn đạt'),
(44, 'たとえば', 'tatoeba', 'audio/minna/bai44/tatoeba.wav', '', '例えば', 'LỆ', 'ví dụ'),
(44, 'わかれます', 'wakaremasu', 'audio/minna/bai44/wakaremasu.wav', '', '別れます', 'BIỆT', 'chia tay, từ biệt'),
(44, 'これら', 'korera', 'audio/minna/bai44/korera.wav', '', '', '', 'những cái này'),
(44, 'えんぎが　わるい', 'engiga　warui', 'audio/minna/bai44/engigawarui.wav', '', '縁起が悪い', 'DUYÊN KHỞI ÁC', 'không may, không lành');