INSERT INTO vocabulary (word, romaji, audio, type, kanji, kanji_reading, meaning, lesson) VALUES
('たべます', 'tabemasu', '/audio/minna/bai06/tabemasu.mp3', 'verb', '食べます', 'THỰC', 'ăn', 6),
('のみます', 'nomimasu', '/audio/minna/bai06/nomimasu.mp3', 'verb', '飲みます', 'ẨM', 'uống', 6),
('すいます', 'suimasu', '/audio/minna/bai06/suimasu.mp3', 'verb', '吸います', 'HẤP', 'hút', 6),
('[たばこを～]', '[tabakowo～]', '', 'verb', '[たばこを～]', '', 'hút [thuốc lá]', 6),
('みます', 'mimasu', '/audio/minna/bai06/mimasu.mp3', 'verb', '見ます', 'KIẾN', 'xem, nhìn, trông', 6),
('ききます', 'kikimasu', '/audio/minna/bai06/kikimasu.mp3', 'verb', '聞きます', 'VĂN', 'nghe', 6),
('よみます', 'yomimasu', '/audio/minna/bai06/yomimasu.mp3', 'verb', '読みます', 'ĐỘC', 'đọc', 6),
('かきます', 'kakimasu', '/audio/minna/bai06/kakimasu.mp3', 'verb', '書きます', 'THƯ', 'viết, vẽ', 6),
('かいます', 'kaimasu', '/audio/minna/bai06/kaimasu.mp3', 'verb', '買います', 'MÃI', 'mua', 6),
('とります[しゃしんを～]', 'torimasu[shashinwo～]', '/audio/minna/bai06/torimasu.mp3', 'verb', '撮ります[写真を～]', 'TOÁT TẢ CHÂN', 'chụp [ảnh]', 6),
('します', 'shimasu', '/audio/minna/bai06/shimasu.mp3', 'verb', '', '', 'làm', 6),
('あいます[ともだちに～]', 'aimasu[tomodachini～]', '/audio/minna/bai06/aimasu.mp3', 'verb', '会います[友達に～]', 'HỘI HỮU ĐẠT', 'gặp [bạn]', 6),
('ごはん', 'gohan', '/audio/minna/bai06/gohan.mp3', 'noun', '', '', 'cơm, bữa ăn', 6),
('あさごはん', 'asagohan', '/audio/minna/bai06/asagohan.mp3', 'noun', '朝ごはん', 'TRIỀU', 'cơm sáng', 6),
('ひるごはん', 'hirugohan', '/audio/minna/bai06/hirugohan.mp3', 'noun', '昼ごはん', 'TRÚ', 'cơm trưa', 6),
('ばんごはん', 'bangohan', '/audio/minna/bai06/bangohan.mp3', 'noun', '晩ごはん', 'VÃN', 'cơm tối', 6),
('パン', 'pan', '/audio/minna/bai06/k_pan.mp3', 'noun', '', '', 'bánh mì', 6),
('たまご', 'tamago', '/audio/minna/bai06/tamago.mp3', 'noun', '卵', 'NOÃN', 'trứng', 6),
('にく', 'niku', '/audio/minna/bai06/niku.mp3', 'noun', '肉', 'NHỤC', 'thịt', 6),
('さかな', 'sakana', '/audio/minna/bai06/sakana.mp3', 'noun', '魚', 'NGƯ', 'cá', 6),
('やさい', 'yasai', '/audio/minna/bai06/yasai.mp3', 'noun', '野菜', 'DÃ THÁI', 'rau', 6),
('くだもの', 'kudamono', '/audio/minna/bai06/kudamono.mp3', 'noun', '果物', 'QUẢ VẬT', 'hoa quả, trái cây', 6),
('みず', 'mizu', '/audio/minna/bai06/mizu.mp3', 'noun', '水', 'THỦY', 'nước', 6),
('おちゃ', 'ocha', '/audio/minna/bai06/ocha.mp3', 'noun', 'お茶', 'TRÀ', 'trà (nói chung)', 6),
('こうちゃ', 'koucha', '/audio/minna/bai06/koucha.mp3', 'noun', '紅茶', 'HỒNG TRÀ', 'trà đen', 6),
('ぎゅうにゅう', 'gyuunyuu', '/audio/minna/bai06/gyuunyuu(k_miruku).mp3', 'noun', '牛乳', 'NGƯU NHŨ', 'sữa bò', 6),
('ジュース', 'juｰsu', '/audio/minna/bai06/k_juusu.mp3', 'noun', '', '', 'nước hoa quả', 6),
('ビール', 'biｰru', '/audio/minna/bai06/k_biiru.mp3', 'noun', '', '', 'bia', 6),
('[お]さけ', '[o]sake', '/audio/minna/bai06/osake.mp3', 'noun', '[お]酒', 'TỬU', 'rượu, rượu sake', 6),
('ビデオ', 'bideo', '/audio/minna/bai06/k_bideo.mp3', 'noun', '', '', 'video, băng video, đầu video', 6),
('えいが', 'eiga', '/audio/minna/bai06/eiga.mp3', 'noun', '映画', 'ẢNH HỌA', 'phim, điện ảnh', 6),
('ＣＤ', 'CD', '/audio/minna/bai06/CD.mp3', 'noun', '', '', 'đĩa CD', 6),
('てがみ', 'tegami', '/audio/minna/bai06/tegami.mp3', 'noun', '手紙', 'THỦ CHỈ', 'thư', 6),
('レポート', 'repoｰto', '/audio/minna/bai06/k_repooto.mp3', 'noun', '', '', 'báo cáo', 6),
('しゃしん', 'shashin', '/audio/minna/bai06/syashin.mp3', 'noun', '写真', 'TẢ CHÂN', 'ảnh', 6),
('みせ', 'mise', '/audio/minna/bai06/mise.mp3', 'noun', '店', 'ĐIẾM', 'cửa hàng, tiệm', 6),
('レストラン', 'resutoran', '/audio/minna/bai06/k_resutoran.mp3', 'noun', '', '', 'nhà hàng', 6),
('にわ', 'niwa', '/audio/minna/bai06/niwa.mp3', 'noun', '庭', 'ĐÌNH', 'vườn', 6),
('しゅくだい', 'shukudai', '/audio/minna/bai06/syukudai.mp3', 'noun', '宿題', 'TÚC ĐỀ', 'bài tập về nhà (～をします: làm bài tập)', 6),
('テニス', 'tenisu', '/audio/minna/bai06/k_tenisu.mp3', 'noun', '', '', 'quần vợt (～をします: đánh quần vợt)', 6),
('サッカー', 'sakkaｰ', '/audio/minna/bai06/k_sakkaa.mp3', 'noun', '', '', 'bóng đá (～をします: chơi bóng đá)', 6),
('[お]はなみ', '[o]hanami', '/audio/minna/bai06/ohanami.mp3', 'noun', '[お]花見', 'HOA KIẾN', 'việc ngắm hoa anh đào (～をします: ngắm hoa anh đào)', 6),
('なに', 'nani', '/audio/minna/bai06/nani.mp3', 'pronoun', '何', 'HÀ', 'cái gì', 6),
('いっしょに', 'isshoni', '/audio/minna/bai06/issyoni.mp3', 'adverb', '', '', 'cùng, cùng nhau', 6),
('ちょっと', 'chotto', '/audio/minna/bai06/chotto.mp3', 'adverb', '', '', 'một chút', 6),
('いつも', 'itsumo', '/audio/minna/bai06/itsumo.mp3', 'adverb', '', '', 'luôn luôn, lúc nào cũng', 6),
('ときどき', 'tokidoki', '/audio/minna/bai06/tokidoki.mp3', 'adverb', '時々', 'THÌ (KÉP)', 'thỉnh thoảng', 6),
('それから', 'sorekara', '/audio/minna/bai06/sorekara.mp3', 'adverb', '', '', 'sau đó, tiếp theo', 6),
('ええ', 'ee', '/audio/minna/bai06/ee.mp3', 'interjection', '', '', 'vâng, được (cách nói thân mật của "はい")', 6),
('いいですね。', 'iidesune｡', '/audio/minna/bai06/iidesune.mp3', 'phrase', '', '', 'Được đấy nhỉ./ hay quá.', 6),
('わかりました。', 'wakarimashita｡', '/audio/minna/bai06/wakarimashita.mp3', 'phrase', '', '', 'Tôi hiểu rồi/ vâng ạ.', 6),
('（なんですか）', '(nandesuka)', '/audio/minna/bai06/nandesuka.mp3', 'phrase', '何ですか。', 'HÀ', 'Có gì đấy ạ?/ cái gì vậy?', 6),
('じゃ、また[あした]。', 'ja､mata[ashita]｡', '/audio/minna/bai06/jamataashita.mp3', 'phrase', '', '', 'Hẹn gặp lại [ngày mai].', 6),
('メキシコ', 'mekishiko', '/audio/minna/bai06/mekishiko.wav', 'noun', '', '', 'Mexico', 6),
('おおさかじょうこうえん', 'oosakajoukouen', '/audio/minna/bai06/oosakajoukouen.wav', 'noun', '大阪城公園', 'ĐẠI PHẢN THÀNH CÔNG VIÊN', 'Công viên lâu đài Osaka', 6); 