-- Bài 47
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(47, '[ひとが～] あつまります', '［hitoga～］　atsumarimasu', 'audio/minna/bai47/atsumarimasu.mp3', '', '[人が～]集まります', 'NHÂN TẬP', 'tập trung, tập hợp [người ~]'),
(47, '[ひとが～]わかれます', '［hitoga～］wakaremasu', 'audio/minna/bai47/wakaremasu.mp3', '', '[人が～]別れます', 'NHÂN BIỆT', 'chia, chia nhỏ, chia ra [người ~]'),
(47, 'ながいきします', 'nagaikishimasu', 'audio/minna/bai47/nagaikishimasu.mp3', '', '長生きします', 'TRƯỜNG SINH', 'sống lâu'),
(47, '[おと／こえが～]します', '［oto／koega～］shimasu', 'audio/minna/bai47/otogashimasu.mp3', '', '[音／声が～]します', 'ÂM/THANH', 'nghe thấy, có [âm thanh/ tiếng]'),
(47, '[あじが～] します', '［ajiga～］　shimasu', 'audio/minna/bai47/ajigashimasu.mp3', '', '[味が～]します', 'VỊ', 'có [vị]'),
(47, '[においが～] します', '［nioiga～］　shimasu', 'audio/minna/bai47/nioigashimasu.mp3', '', '', '', 'có [mùi]'),
(47, '[かさを～] さします', '［kasawo～］　sashimasu', 'audio/minna/bai47/kasawosashimasu.mp3', '', '[傘を～]さします', 'TẢN', 'che [ô]'),
(47, 'ひどい', 'hidoi', 'audio/minna/bai47/hidoi.mp3', '', '', '', 'tồi tệ, xấu'),
(47, 'こわい', 'kowai', 'audio/minna/bai47/kowai.mp3', '', '怖い', 'BỐ', 'sợ, khiếp'),
(47, 'てんきよほう', 'tenkiyohou', 'audio/minna/bai47/tenkiyohou.mp3', '', '天気予報', 'THIÊN KHÍ DỰ BÁO', 'dự báo thời tiết'),
(47, 'はっぴょう', 'happyou', 'audio/minna/bai47/happyou.mp3', '', '発表', 'PHÁT BIỂU', 'phát biểu, báo cáo'),
(47, 'じっけん', 'jikken', 'audio/minna/bai47/jikken.mp3', '', '実験', 'THỰC NGHIỆM', 'thực nghiệm, thí nghiệm'),
(47, 'じんこう', 'jinkou', 'audio/minna/bai47/jinkou.mp3', '', '人口', 'NHÂN KHẨU', 'dân số'),
(47, 'におい', 'nioi', 'audio/minna/bai47/nioi.mp3', '', '', '', 'mùi'),
(47, 'かがく', 'kagaku', 'audio/minna/bai47/kagaku.mp3', '', '科学', 'KHOA HỌC', 'khoa học'),
(47, 'いがく', 'igaku', 'audio/minna/bai47/igaku.mp3', '', '医学', 'Y HỌC', 'y học'),
(47, 'ぶんがく', 'bungaku', 'audio/minna/bai47/bungaku.mp3', '', '文学', 'VĂN HỌC', 'văn học'),
(47, 'パトカー', 'patoka-', 'audio/minna/bai47/k_patokaa.mp3', '', '', '', 'xe ô-tô cảnh sát'),
(47, 'きゅうきゅうしゃ', 'kyuukyuusha', 'audio/minna/bai47/kyuukyuusya.mp3', '', '救急車', 'CỨU CẤP XA', 'xe cấp cứu'),
(47, 'さんせい', 'sansei', 'audio/minna/bai47/sansei.mp3', '', '賛成', 'TÁN THÀNH', 'tán thành, đồng ý'),
(47, 'はんたい', 'hantai', 'audio/minna/bai47/hatai.mp3', '', '反対', 'PHẢN ĐỐI', 'phản đối'),
(47, 'だんせい', 'dansei', 'audio/minna/bai47/dasei.mp3', '', '男性', 'NAM TÍNH', 'nam giới, Nam'),
(47, 'じょせい', 'josei', 'audio/minna/bai47/josei.mp3', '', '女性', 'NỮ TÍNH', 'nữ giới, nữ'),
(47, 'どうも', 'doumo', 'audio/minna/bai47/doumo.mp3', '', '', '', 'có vẽ như là, có lẽ là'),
(47, '～によると', '～niyoruto', 'audio/minna/bai47/niyoruto.mp3', '', '', '', 'theo ~ thì, căn cứ vào ~ thì'),
(47, 'バリ[とう]', 'bari［tou］', 'audio/minna/bai47/bari.wav', '', 'バリ[島]', 'ĐẢO', '[đảo] Bali (ở Indonesia)'),
(47, 'イラン', 'iran', 'audio/minna/bai47/iran.wav', '', '', '', 'Iran'),
(47, 'カリフォルニア', 'kariforunia', 'audio/minna/bai47/karifonia.wav', '', '', '', 'California (ở Mỹ)'),
(47, 'グアム', 'guamu', 'audio/minna/bai47/guam.wav', '', '', '', 'Guam'),
(47, 'こいびと', 'koibito', 'audio/minna/bai47/koibito.mp3', '', '恋人', 'LUYẾN NHÂN', 'người yêu'),
(47, 'こんやくします', 'konyakushimasu', 'audio/minna/bai47/konyakushimasu.wav', '', '婚約します', 'HÔN ƯỚC', 'đính hôn'),
(47, 'あいて', 'aite', 'audio/minna/bai47/aite.mp3', '', '相手', 'TƯỚNG THỦ', 'đối tác, đối phương, người kia, “nửa còn lại”'),
(47, 'しりあいます', 'shiriaimasu', 'audio/minna/bai47/shiriaimasu.mp3', '', '知り合います', 'TRI HỢP', 'gặp, gặp gỡ làm quen'),
(47, 'へいきんじゅみょう', 'heikinjumyou', 'audio/minna/bai47/heikinjumyou.wav', '', '平均寿命', 'BÌNH QUÂN THỌ MỆNH', 'tuổi thọ trung bình'),
(47, '[だんせいと～]くらべます', '［danseito～］kurabemasu', 'audio/minna/bai47/kurabemasu.wav', '', '[男性と～]比べます', '[NAM TÍNH]　TỶ', 'so sánh [với nam giới]'),
(47, 'はかせ', 'hakase', 'audio/minna/bai47/hakase.wav', '', '博士', 'BÁC SĨ', 'tiến sĩ'),
(47, 'のう', 'nou', 'audio/minna/bai47/nou.wav', '', '脳', 'NÃO', 'não'),
(47, 'ホルモン', 'horumon', 'audio/minna/bai47/horumon.wav', '', '', '', 'hoóc-môn'),
(47, 'けしょうひん', 'keshouhin', 'audio/minna/bai47/keshouhin.wav', '', '化粧品', 'HÓA TRANG PHẨM', 'mỹ phẩm'),
(47, 'しらべ', 'shirabe', 'audio/minna/bai47/shirabe.wav', '', '調べ', 'ĐIỀU', 'điều tra, tìm hiểu'),
(47, 'けしょう', 'keshou', 'audio/minna/bai47/kesho.wav', '', '化粧', 'HÓA TRANG', 'sự trang điểm (～をします：trang điểm)');