-- Bài 36
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(36, '[にもつが～] とどきます', '［nimotsuga～］　todokimasu', 'audio/minna/bai36/todokimasu.mp3', '', '[荷物が～]届きます', 'HÀ VẬT GIỚI', 'được gởi đến, được chuyển đến [hành lý ~]'),
(36, '[しあいに～]　でます', '［shiaini～］　demasu', 'audio/minna/bai36/demasu.mp3', '', '[試合に～]出ます', 'THÍ HỢP XUẤT', 'tham gia, tham dự [trận đấu]'),
(36, '[ワープロを～]うちます', '［wa-purowo～］uchimasu', 'audio/minna/bai36/uchimasu.mp3', '', '[ワープロを～]打ちます', 'ĐẢ', 'đánh [máy chữ]'),
(36, 'ちょきんします', 'chokinshimasu', 'audio/minna/bai36/chokinshimasu.mp3', '', '貯金します', 'TRỮ KIM', 'tiết kiệm tiền, để dành tiền'),
(36, 'ふとります', 'futorimasu', 'audio/minna/bai36/futorimasu.mp3', '', '太ります', 'THÁI', 'béo lên, tăng cân'),
(36, 'やせます', 'yasemasu', 'audio/minna/bai36/yasemasu.mp3', '', '', '', 'gầy đi, giảm cân'),
(36, '[７じを～] すぎます', '［７jiwo～］　sugimasu', 'audio/minna/bai36/sugimasu.mp3', '', '[７時を～]過ぎます', 'THÌ QUÁ', 'quá, qua [7 giờ]'),
(36, '[しゅうかんに～] なれます', '［shuukanni～］　naremasu', 'audio/minna/bai36/naremasu.mp3', '', '[習慣に～]慣れます', 'TẬP QUÁN QUÁN', 'làm quen với [tập quán]'),
(36, 'かたい', 'katai', 'audio/minna/bai36/katai.mp3', '', '硬い', 'NGẠNH', 'cứng'),
(36, 'やわらかい', 'yawarakai', 'audio/minna/bai36/yawarakai.mp3', '', '軟らかい', 'NHUYỄN', 'mềm'),
(36, 'でんし～', 'denshi～', 'audio/minna/bai36/denshi.mp3', '', '電子～', 'ĐIỆN TỬ', '~ điện tử'),
(36, 'けいたい～', 'keitai～', 'audio/minna/bai36/keitai.mp3', '', '携帯～', 'HUỀ ĐỚI ~', 'cầm tay'),
(36, 'こうじょう', 'koujou', 'audio/minna/bai36/koujou.mp3', '', '工場', 'CÔNG TRƯỜNG', 'nhà máy, phân xưởng'),
(36, 'けんこう', 'kenkou', 'audio/minna/bai36/kenkou.mp3', '', '健康', 'KIỆN KHANG', 'sức khỏe'),
(36, 'けんどう', 'kendou', 'audio/minna/bai36/kendou.mp3', '', '剣道', 'KIẾM ĐẠO', 'kiếm đạo'),
(36, 'まいしゅう', 'maishuu', 'audio/minna/bai36/maisyuu.mp3', '', '毎週', 'MỖI CHU', 'hàng tuần'),
(36, 'まいつき', 'maitsuki', 'audio/minna/bai36/maitsuki.mp3', '', '毎月', 'MỖI NGUYỆT', 'hàng tháng'),
(36, 'まいとし（まいねん）', 'maitoshi（mainen）', 'audio/minna/bai36/maitoshi.mp3', '', '毎年', 'MỖI NIÊN', 'hàng năm'),
(36, 'やっと', 'yatto', 'audio/minna/bai36/yatto.mp3', '', '', '', 'cuối cùng thì'),
(36, 'かなり', 'kanari', 'audio/minna/bai36/kanari.mp3', '', '', '', 'khá, tương đối'),
(36, 'かならず', 'kanarazu', 'audio/minna/bai36/kanarazu.mp3', '', '必ず', 'TẤT', 'nhất định'),
(36, 'ぜったいに', 'zettaini', 'audio/minna/bai36/zettaini.mp3', '', '絶対に', 'TUYỆT ĐỐI', 'nhất định, tuyệt đối'),
(36, 'じょうずに', 'jouzuni', 'audio/minna/bai36/jouzuni.mp3', '', '上手に', 'THƯỢNG THỦ', 'giỏi, khéo'),
(36, 'できるだけ', 'dekirudake', 'audio/minna/bai36/dekirudake.mp3', '', '', '', 'cố gắng'),
(36, 'このごろ', 'konogoro', 'audio/minna/bai36/konogoro.mp3', '', '', '', 'gần đây, dạo này'),
(36, '～ずつ', '～zutsu', 'audio/minna/bai36/zutsu.mp3', '', '', '', 'từng ~, ~ một'),
(36, 'そのほうが～', 'sonohouga～', 'audio/minna/bai36/sonohouga.mp3', '', '', '', 'cái đó ~ hơn, như thế ~ hơn'),
(36, 'ショパン', 'shopan', 'audio/minna/bai36/shopan.wav', '', '', '', 'Sô-panh, nhà soạn nhạc người Ba Lan (1810-1849)'),
(36, 'おきゃくさま', 'okyakusama', 'audio/minna/bai36/okyakusama.mp3', '', 'お客様', 'KHÁCH DẠNG', 'quý khách, khách hàng'),
(36, 'とくべつ「な」', 'tokubetsu「na」', 'audio/minna/bai36/tokubetsu.mp3', '', '特別[な]', 'ĐẶC BIỆT', 'đặc biệt'),
(36, 'していらっしゃいます', 'shiteirasshaimasu', 'audio/minna/bai36/shiteirassyaimasu.mp3', '', '', '', 'đang làm (tôn kính ngữ của しています)'),
(36, 'すいえい', 'suiei', 'audio/minna/bai36/suiei.mp3', '', '水泳', 'THỦY VĨNH', 'bơi, môn bơi'),
(36, '～とか、～とか', '～toka、～toka', 'audio/minna/bai36/toka.mp3', '', '', '', '~ v.v.'),
(36, 'タンゴ', 'tango', 'audio/minna/bai36/k_tango.mp3', '', '', '', 'tăng-gô'),
(36, 'チャレンジします', 'charenjishimasu', 'audio/minna/bai36/k_charenjishimasu.mp3', '', '', '', 'thử, thử thách, dám làm (challenge)'),
(36, 'きもち', 'kimochi', 'audio/minna/bai36/kimochi.mp3', '', '気持ち', 'KHÍ TRÌ', 'cảm giác, tâm trạng, tinh thần'),
(36, 'のりもの', 'norimono', 'audio/minna/bai36/norimono.wav', '', '乗り物', 'THỪA VẬT', 'phương tiện đi lại'),
(36, 'れきし', 'rekishi', 'audio/minna/bai36/rekishi.wav', '', '歴史', 'LỊCH SỬ', 'lịch sử'),
(36, '―せいき', '-seiki', 'audio/minna/bai36/seiki.wav', '', '―世紀', 'THẾ KỶ', 'thế kỷ -'),
(36, 'とおく', 'tooku', 'audio/minna/bai36/tooku.wav', '', '遠く', 'VIỄN', 'xa, ở xa'),
(36, 'きしゃ', 'kisha', 'audio/minna/bai36/kisha.wav', '', '汽車', 'KHÍ XA', 'tàu hỏa chạy bằng hơi nước'),
(36, 'きせん', 'kisen', 'audio/minna/bai36/kisen.wav', '', '汽船', 'KHÍ THUYỀN', 'thuyền chạy bằng hơi nước'),
(36, 'おおぜいの～', 'oozeino～', 'audio/minna/bai36/oozeino.wav', '', '大勢の～', 'ĐẠI THẾ', 'nhiều (người)'),
(36, 'はこびます', 'hakobimasu', 'audio/minna/bai36/hakobimasu.wav', '', '運びます', 'VẬN', 'mang, chở, vận chuyển'),
(36, 'とびます', 'tobimasu', 'audio/minna/bai36/tobimasu.wav', '', '飛びます', 'PHI', 'bay'),
(36, 'あんぜん', 'anzen', 'audio/minna/bai36/anzen.wav', '', '安全', 'AN TOÀN', 'an toàn'),
(36, 'うちゅう', 'uchuu', 'audio/minna/bai36/uchu.wav', '', '宇宙', 'VŨ TRỤ', 'vũ trụ'),
(36, 'ちきゅう', 'chikyuu', 'audio/minna/bai36/chikyu.wav', '', '地球', 'ĐỊA CẦU', 'địa cầu, trái đất'),
(36, 'ライトきょうだい', 'raitokyoudai', 'audio/minna/bai36/raitokyoudai.wav', '', 'ライト兄弟', 'HUYNH ĐỆ', 'anh em nhà Wright');