-- Bài 28
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(28, '[パンが～] うれます', '［panga～］　uremasu', 'audio/minna/bai28/uremasu.mp3', '', '[パンが～] 売れます', 'MẠI', 'bán chạy, được bán [bánh mì ~]'),
(28, 'おどります', 'odorimasu', 'audio/minna/bai28/odorimasu.mp3', '', '踊ります', 'DŨNG', 'nhảy, khiêu vũ'),
(28, 'かみます', 'kamimasu', 'audio/minna/bai28/kamimasu.mp3', '', '', '', 'nhai'),
(28, 'えらびます', 'erabimasu', 'audio/minna/bai28/erabimasu.mp3', '', '選びます', 'TUYỂN', 'chọn'),
(28, 'ちがいます', 'chigaimasu', 'audio/minna/bai28/chigaimasu.mp3', '', '違います', 'VI', 'khác'),
(28, '[だいがくに～] かよいます', '［daigakuni～］　kayoimasu', 'audio/minna/bai28/kayoimasu.mp3', '', '[大学に～]通います', 'ĐẠI HỌC THÔNG', 'đi đi về về [trường đại học]'),
(28, 'メモします', 'memoshimasu', 'audio/minna/bai28/k_memoshimasu.mp3', '', '', '', 'ghi chép'),
(28, 'まじめ[な]', 'majime［na］', 'audio/minna/bai28/majime.mp3', '', '', '', 'nghiêm túc, nghiêm chỉnh'),
(28, 'ねっしん[な]', 'nesshin［na］', 'audio/minna/bai28/nesshin.mp3', '', '熱心[な]', 'NHIỆT TÂM', 'nhiệt tâm, nhiệt tình, hết lòng'),
(28, 'やさしい', 'yasashii', 'audio/minna/bai28/yasashii.mp3', '', '優しい', 'ƯU', 'tình cảm, hiền lành'),
(28, 'えらい', 'erai', 'audio/minna/bai28/erai.mp3', '', '偉い', 'VĨ', 'vĩ đại, đáng kính, đáng khâm phục'),
(28, 'ちょうどいい', 'choudoii', 'audio/minna/bai28/choudoii.mp3', '', '', '', 'vừa đủ, vừa đúng'),
(28, 'しゅうかん', 'shuukan', 'audio/minna/bai28/shuukan.mp3', '', '習慣', 'TẬP QUÁN', 'tập quán'),
(28, 'けいけん', 'keiken', 'audio/minna/bai28/keiken.mp3', '', '経験', 'KINH NGHIỆM', 'kinh nghiệm'),
(28, 'ちから', 'chikara', 'audio/minna/bai28/chikara.mp3', '', '力', 'LỰC', 'sức lực, năng lực'),
(28, '[がくせいに]にんきがあります', '［gakuseini］ninkigaarimasu', 'audio/minna/bai28/ninkigaarimasu.mp3', '', '[がくせいに]人気があります', 'NHÂN KHÍ', 'sự hâm mộ, được [sinh viên] hâm mộ'),
(28, 'かたち', 'katachi', 'audio/minna/bai28/katachi.mp3', '', '形', 'HÌNH', 'hình, hình dáng'),
(28, 'いろ', 'iro', 'audio/minna/bai28/iro.mp3', '', '色', 'SẮC', 'màu'),
(28, 'あじ', 'aji', 'audio/minna/bai28/aji.mp3', '', '味', 'VỊ', 'vị'),
(28, 'ガム', 'gamu', 'audio/minna/bai28/k_gamu.mp3', '', '', '', 'kẹo cao su'),
(28, 'しなもの', 'shinamono', 'audio/minna/bai28/shinamono.mp3', '', '品物', 'PHẨM VẬT', 'hàng hóa, mặt hàng'),
(28, 'ねだん', 'nedan', 'audio/minna/bai28/nedan.mp3', '', '値段', 'TRỊ ĐOẠN', 'giá'),
(28, 'きゅうりょう', 'kyuuryou', 'audio/minna/bai28/kyuuryou.mp3', '', '給料', 'CẤP LIỆU', 'lương'),
(28, 'ボーナス', 'bo-nasu', 'audio/minna/bai28/k_boonasu.mp3', '', '', '', 'thưởng'),
(28, 'ばんぐみ', 'bangumi', 'audio/minna/bai28/bangumi.mp3', '', '番組', 'PHIÊN TỔ', 'chương trình (phát thanh, truyền hình)'),
(28, 'ドラマ', 'dorama', 'audio/minna/bai28/k_dorama.mp3', '', '', '', 'kịch, phim truyền hình'),
(28, 'しょうせつ', 'shousetsu', 'audio/minna/bai28/syousetsu.mp3', '', '小説', 'TIỂU THUYẾT', 'tiểu thuyết'),
(28, 'しょうせつか', 'shousetsuka', 'audio/minna/bai28/syousetsuka.mp3', '', '小説家', 'TIỂU THUYẾT GIA', 'tiểu thuyết gia, nhà văn'),
(28, 'かしゅ', 'kashu', 'audio/minna/bai28/kasyu.mp3', '', '歌手', 'CA THỦ', 'ca sĩ'),
(28, 'かんりにん', 'kanrinin', 'audio/minna/bai28/kanrinin.mp3', '', '管理人', 'QUẢN LÝ NHÂN', 'người quản lý'),
(28, 'むすこ', 'musuko', 'audio/minna/bai28/musuko.mp3', '', '息子', 'TỨC TỬ', 'con trai (dùng cho mình)'),
(28, 'むすこさん', 'musukosan', 'audio/minna/bai28/musukosan.mp3', '', '息子さん', 'TỨC TỬ', 'con trai (dùng cho người khác)'),
(28, 'むすめ', 'musume', 'audio/minna/bai28/musume.mp3', '', '娘', 'NƯƠNG', 'con gái (dùng cho mình)'),
(28, 'むすめさん', 'musumesan', 'audio/minna/bai28/musumesan.mp3', '', '娘さん', 'NƯƠNG', 'con gái (dùng cho người khác)'),
(28, 'じぶん', 'jibun', 'audio/minna/bai28/jibun.mp3', '', '自分', 'TỰ PHÂN', 'bản thân, mình'),
(28, 'しょうらい', 'shourai', 'audio/minna/bai28/syourai.mp3', '', '将来', 'TƯƠNG LAI', 'tương lai'),
(28, 'しばらく', 'shibaraku', 'audio/minna/bai28/shibaraku.mp3', '', '', '', 'một khoảng thời gian ngắn, một lúc, một lát'),
(28, 'たいてい', 'taitei', 'audio/minna/bai28/taitei.mp3', '', '', '', 'thường, thông thường'),
(28, 'それに', 'soreni', 'audio/minna/bai28/soreni.mp3', '', '', '', 'thêm nữa là, thêm vào đó là'),
(28, 'それで', 'sorede', 'audio/minna/bai28/sorede.mp3', '', '', '', 'thế thì, thế nên'),
(28, '[ちょっと]おねがいがあるんですが。', '［chotto］onegaigaarundesuga', 'audio/minna/bai28/chottoonegaigaarundesuga.mp3', '', '[ちょっと]お願いがあるんですが。', 'NGUYỆN', 'Tôi có (chút) việc muốn nhờ anh/ chị.'),
(28, 'ホームステイ', 'ho-musutei', 'audio/minna/bai28/k_hoomusutei.mp3', '', '', '', 'homestay'),
(28, 'おしゃべりします', 'oshaberishimasu', 'audio/minna/bai28/osyaberishimasu.mp3', '', '', '', 'nói chuyện, tán chuyện'),
(28, 'おしらせ', 'oshirase', 'audio/minna/bai28/oshirase.wav', '', 'お知らせ', 'TRI', 'thông báo'),
(28, 'ひにち', 'hinichi', 'audio/minna/bai28/hinichi.wav', '', '日にち', 'NHẬT', 'ngày'),
(28, 'ど', 'do', 'audio/minna/bai28/do.wav', '', '土', 'THỔ', 'thứ bảy'),
(28, 'たいいくかん', 'taiikukan', 'audio/minna/bai28/taiikukan.wav', '', '体育館', 'THỂ DỤC QUÁN', 'nhà tập, nhà thi đấu thể thao'),
(28, 'むりょう', 'muryou', 'audio/minna/bai28/muryou.wav', '', '無料', 'VÔ LIỆU', 'miễn phí');