INSERT INTO vocabulary (word, romaji, audio, type, kanji, kanji_reading, meaning, lesson) VALUES
('これ', 'kore', '/audio/minna/bai02/kore.mp3', NULL, NULL, NULL, 'cái này, đây (vật ở gần người nói)', 2),
('それ', 'sore', '/audio/minna/bai02/sore.mp3', NULL, NULL, NULL, 'cái đó, đó (vật ở gần người nghe)', 2),
('あれ', 'are', '/audio/minna/bai02/are.mp3', NULL, NULL, NULL, 'cái kia, kia (vật ở xa cả người nói và người nghe)', 2),
('この～', 'kono～', '/audio/minna/bai02/kono.mp3', NULL, NULL, NULL, '~ này', 2),
('その～', 'sono～', '/audio/minna/bai02/sono.mp3', NULL, NULL, NULL, '~ đó', 2),
('あの～', 'ano～', '/audio/minna/bai02/ano.mp3', NULL, NULL, NULL, '~ kia', 2),
('ほん', 'hon', '/audio/minna/bai02/hon.mp3', NULL, '本', 'BẢN/BỔN', 'sách', 2),
('じしょ', 'jisho', '/audio/minna/bai02/jisyo.mp3', NULL, '辞書', 'TỪ THƯ', 'từ điển', 2),
('ざっし', 'zasshi', '/audio/minna/bai02/zasshi.wav', NULL, '雑誌', 'TẠP CHÍ', 'tạp chí', 2),
('しんぶん', 'shinbun', '/audio/minna/bai02/shinbun.mp3', NULL, '新聞', 'TÂN VĂN', 'báo', 2),
('ノート', 'noｰto', '/audio/minna/bai02/k-nooto.mp3', NULL, NULL, NULL, 'vở', 2),
('てちょう', 'techou', '/audio/minna/bai02/techoo.mp3', NULL, '手帳', 'THỦ TRƯƠNG', 'sổ tay', 2),
('めいし', 'meishi', '/audio/minna/bai02/meishi.mp3', NULL, '名刺', 'DANH THÍCH', 'danh thiếp', 2),
('カード', 'kaｰdo', '/audio/minna/bai02/k-kaado.mp3', NULL, NULL, NULL, 'thẻ, cạc', 2),
('テレホンカード', 'terehonkaｰdo', '/audio/minna/bai02/k-terehonkaado.mp3', NULL, NULL, NULL, 'thẻ điện thoại', 2),
('えんぴつ', 'enpitsu', '/audio/minna/bai02/enpitsu.mp3', NULL, '鉛筆', 'DUYÊN BÚT', 'bút chì', 2),
('ボールペン', 'boｰrupen', '/audio/minna/bai02/borupen.wav', NULL, NULL, NULL, 'bút bi', 2),
('シャープペンシル', 'shaｰpupenshiru', '/audio/minna/bai02/k-shaapupenshiru.mp3', NULL, NULL, NULL, 'bút chì kim, bút chì bấm', 2),
('かぎ', 'kagi', '/audio/minna/bai02/kagi.mp3', NULL, NULL, NULL, 'chìa khóa', 2),
('とけい', 'tokei', '/audio/minna/bai02/tokei.mp3', NULL, '時計', 'THỜI KẾ', 'đồng hồ', 2),
('かさ', 'kasa', '/audio/minna/bai02/kasa.mp3', NULL, '傘', 'TẢN', 'ô, dù', 2),
('かばん', 'kaban', '/audio/minna/bai02/kaban.mp3', NULL, NULL, NULL, 'cặp sách, túi sách', 2),
('[カセット]テープ', '[kasetto]teｰpu', '/audio/minna/bai02/k-[kasetto]teepu.mp3', NULL, NULL, NULL, 'băng [cát-xét]', 2),
('テープレコーダー', 'teｰpurekoｰdaｰ', '/audio/minna/bai02/k-teepurekoodaa.mp3', NULL, NULL, NULL, 'máy ghi âm', 2),
('テレビ', 'terebi', '/audio/minna/bai02/k-terebi.mp3', NULL, NULL, NULL, 'tivi', 2),
('ラジオ', 'rajio', '/audio/minna/bai02/k-rajio.mp3', NULL, NULL, NULL, 'Radio', 2),
('カメラ', 'kamera', '/audio/minna/bai02/k-kamera.mp3', NULL, NULL, NULL, 'máy ảnh', 2),
('コンピューター', 'konpyuｰtaｰ', '/audio/minna/bai02/k-konpyuutaa.mp3', NULL, NULL, NULL, 'máy vi tính', 2),
('じどうしゃ', 'jidousha', '/audio/minna/bai02/jidousya.mp3', NULL, '自動車', 'TỰ ĐỘNG XA', 'ô tô, xe hơi', 2),
('つくえ', 'tsukue', '/audio/minna/bai02/tsukue.mp3', NULL, NULL, NULL, 'cái bàn', 2),
('いす', 'isu', '/audio/minna/bai02/isu.mp3', NULL, NULL, NULL, 'cái ghế', 2),
('チョコレート', 'chokoreｰto', '/audio/minna/bai02/k-chokoreeto.mp3', NULL, NULL, NULL, 'Socola', 2),
('コーヒー', 'koｰhiｰ', '/audio/minna/bai02/k-koohii.mp3', NULL, NULL, NULL, 'cà phê', 2),
('えいご', 'eigo', '/audio/minna/bai02/eigo.mp3', NULL, NULL, NULL, 'tiếng anh', 2),
('にほんご', 'nihongo', '/audio/minna/bai02/nihongo.mp3', NULL, NULL, NULL, 'tiếng nhật', 2),
('なに', 'nani', '/audio/minna/bai02/nani.wav', NULL, NULL, NULL, 'cái gì', 2),
('なん', 'nan', '/audio/minna/bai02/nan.mp3', NULL, NULL, NULL, 'cái gì', 2),
('そう', 'sou', '/audio/minna/bai02/sou.mp3', NULL, NULL, NULL, 'đúng rồi', 2),
('ちがいます', 'chigaimasu', '/audio/minna/bai02/chigaimasu.wav', NULL, '違います', 'VI', 'không phải, không đúng, sai rồi', 2),
('そうですか', 'soudesuka', '/audio/minna/bai02/sodesuka.wav', NULL, NULL, NULL, 'thế à, vậy à', 2),
('あのう', 'anou', '/audio/minna/bai02/ano.mp3', NULL, NULL, NULL, 'à, ờ', 2),
('ほんのきもち', 'honnokimochi', '/audio/minna/bai02/honnokimochi.wav', NULL, 'ほんの気持ち', 'KHÍ TRÌ', 'chỉ là chút lòng thành thôi', 2),
('どうぞ', 'douzo', '/audio/minna/bai02/dozo.wav', NULL, NULL, NULL, 'xin mời', 2),
('どうも', 'doumo', '/audio/minna/bai02/domo.wav', NULL, NULL, NULL, 'cám ơn', 2),
('どうもありがとうございます', 'doumoarigatougozaimasu', '/audio/minna/bai02/domoarigatogozaimasu.wav', NULL, NULL, NULL, 'xin chân thành cám ơn', 2),
('これからおせわになります', 'korekaraosewaninarimasu', '/audio/minna/bai02/korekaraosewaninarimasu.wav', NULL, NULL, NULL, 'từ nay tôi rất mong sự giúp đỡ của anh chị', 2),
('こちらこそ　よろしく', 'kochirakoso yoroshiku', '/audio/minna/bai02/kochirakosoyoroshiku.mp3', NULL, NULL, NULL, 'chính tôi mới phải xin ông giúp đỡ cho', 2);
