-- Bài 50
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(50, 'まいります', 'mairimasu', 'audio/minna/bai50/mairimasu.mp3', '', '参ります', 'THAM', 'đi, đến (khiêm nhường ngữ của いきます và きます)'),
(50, 'おります', 'orimasu', 'audio/minna/bai50/orimasu.mp3', '', '', '', 'ở, có (khiêm nhường ngữ của います)'),
(50, 'いただきます', 'itadakimasu', 'audio/minna/bai50/itadakimasu.mp3', '', '', '', 'ăn, uống, nhận (khiêm nhường ngữ của たべます、のみます　và もらいます)'),
(50, 'もうします', 'moushimasu', 'audio/minna/bai50/moushimasu.mp3', '', '申します', 'THÂN', 'nói (khiêm nhường ngữ của いいます)'),
(50, 'いたします', 'itashimasu', 'audio/minna/bai50/itashimasu.mp3', '', '', '', 'làm (khiêm nhường ngữ của します)'),
(50, 'はいけんします', 'haikenshimasu', 'audio/minna/bai50/haikenshimasu.mp3', '', '拝見します', 'BÁI KIẾN', 'xem, nhìn (khiêm nhường ngữ của みます)'),
(50, 'ぞんじます', 'zonjimasu', 'audio/minna/bai50/zonjimasu.mp3', '', '存じます', 'TỒN', 'biết (khiêm nhường ngữ của しります)'),
(50, 'うかがいます', 'ukagaimasu', 'audio/minna/bai50/ukagamasu.mp3', '', '伺います', 'TÝ/TỬ', 'hỏi, nghe, đến thăm(khiêm nhường ngữ của ききます và いきます)'),
(50, 'おめにかかります', 'omenikakarimasu', 'audio/minna/bai50/omenikakarimasu.mp3', '', 'お目にかかります', 'MỤC', 'gặp (khiêm nhường ngữ của あいます)'),
(50, 'ございます', 'gozaimasu', 'audio/minna/bai50/gozaimasu.mp3', '', '', '', 'có (thể lịch sự của あります)'),
(50, '～でございます', '～degozaimasu', 'audio/minna/bai50/degozaimasu.mp3', '', '', '', 'là (thể lịch sự của ～です)'),
(50, 'わたくし', 'watakushi', 'audio/minna/bai50/watakushi.mp3', '', '私', 'TƯ', 'tôi (khiêm nhường ngữ của わたし)'),
(50, 'ガイド', 'gaido', 'audio/minna/bai50/k_gaido.mp3', '', '', '', 'người hướng dẫn, hướng dẫn viên'),
(50, 'おたく', 'otaku', 'audio/minna/bai50/otaku.mp3', '', 'お宅', 'TRẠCH', 'nhà (dùng cho người khác)'),
(50, 'こうがい', 'kougai', 'audio/minna/bai50/kougai.mp3', '', '郊外', 'GIAO NGOẠI', 'ngoại ô'),
(50, 'アルバム', 'arubamu', 'audio/minna/bai50/k_arubamu.mp3', '', '', '', 'an-bum (ca nhạc)'),
(50, 'さらいしゅう', 'saraishuu', 'audio/minna/bai50/saraisyuu.mp3', '', '再来週', 'TÁI LAI CHU', 'tuần sau nữa'),
(50, 'さらいげつ', 'saraigetsu', 'audio/minna/bai50/saraigetsu.mp3', '', '再来月', 'TÁI LAI NGUYỆT', 'tháng sau nữa'),
(50, 'さらいねん', 'sarainen', 'audio/minna/bai50/sarainen.mp3', '', '再来年', 'TÁI LAI NIÊN', 'năm sau nữa'),
(50, 'はんとし', 'hantoshi', 'audio/minna/bai50/hantoshi.mp3', '', '半年', 'BÁN NIÊN', 'nửa năm'),
(50, 'さいしょに', 'saishoni', 'audio/minna/bai50/saisyoni.mp3', '', '最初に', 'TỐI SƠ', 'đầu tiên, trước hết'),
(50, 'さいごに', 'saigoni', 'audio/minna/bai50/saigoni.mp3', '', '最後に', 'TỐI HẬU', 'cuối cùng'),
(50, 'ただいま', 'tadaima', 'audio/minna/bai50/tadaima.mp3', '', 'ただ今', 'KIM', 'bây giờ (thể lịch sự củaいま)'),
(50, 'えどとうきょうはくぶつかん', 'edotoukyouhakubutsukan', 'audio/minna/bai50/edotoukyouhakubutukan.mp3', '', '江戸東京博物館', 'GIANG HỘ ĐÔNG KINH BÁC VẬT QUÁN', 'bảo tàng Edo-Tokyo'),
(50, 'きんちょうします', 'kinchoushimasu', 'audio/minna/bai50/kinnchoushimasu.mp3', '', '緊張します', 'KHẨN TRƯƠNG', 'căng thẳng, hồi hộp'),
(50, 'ほうそうします', 'housoushimasu', 'audio/minna/bai50/housoushimasu.mp3', '', '放送します', 'PHÓNG TỐNG', 'phát thanh, truyền hình'),
(50, '[ビデオに～]とります', '［bideoni～］torimasu', 'audio/minna/bai50/torimasu.mp3', '', '[ビデオに～]撮ります', 'TOÁT', 'thu [video], quay'),
(50, 'しょうきん', 'shoukin', 'audio/minna/bai50/syoukin.mp3', '', '賞金', 'THƯỞNG KIM', 'tiền thưởng'),
(50, 'しぜん', 'shizen', 'audio/minna/bai50/shizen.mp3', '', '自然', 'TỰ NHIÊN', 'tự nhiên, thiên nhiên'),
(50, 'きりん', 'kirin', 'audio/minna/bai50/kirin.mp3', '', '', '', 'con hươu cao cổ'),
(50, 'ぞう', 'zou', 'audio/minna/bai50/zou.mp3', '', '像', 'TƯỢNG', 'con voi'),
(50, 'ころ', 'koro', 'audio/minna/bai50/koro.mp3', '', '', '', 'hồi, thời'),
(50, '「ゆめが～」かないます', '「yumega～」kanaimasu', 'audio/minna/bai50/kanaimasu.mp3', '', '[夢が～]かないます', 'MỘNG', 'thành hiện thực, được thực hiện [mơ ước ~]'),
(50, 'ひとことよろしいでしょうか。', 'hitokotoyoroshiideshouka', 'audio/minna/bai50/hitokotoyoroshidesyouka.mp3', '', '', '', 'Tôi xin phép nói vài lời có được không ạ?'),
(50, 'きょうりょくします', 'kyouryokushimasu', 'audio/minna/bai50/kyouryokushimasu.mp3', '', '協力します', 'HIỆP LỰC', 'hợp tác'),
(50, 'こころから', 'kokorokara', 'audio/minna/bai50/kokorokara.mp3', '', '心から', 'TÂM', 'từ trái tim, từ đáy lòng'),
(50, 'かんしゃします', 'kanshashimasu', 'audio/minna/bai50/kansyashimasu.mp3', '', '感謝します', 'CẢM TẠ', 'cám ơn, cảm tạ'),
(50, '「お」れい', '「o」rei', 'audio/minna/bai50/orei.wav', '', '[お]礼', 'LỄ', 'lời cám ơn, sự cám ơn'),
(50, 'はいけい', 'haikei', 'audio/minna/bai50/haikei.wav', '', '拝啓', 'BÁI KHẢI', 'kính gửi'),
(50, 'うつくしい', 'utsukushii', 'audio/minna/bai50/utsukushii.wav', '', '美しい', 'MỸ', 'đẹp'),
(50, 'おげんきでいらっしゃいますか', 'ogenkideirasshaimasuka', 'audio/minna/bai50/ogenkideirasshaimasuka.wav', '', 'お元気でいらっしゃいますか。', 'NGUYÊN KHÍ', 'Anh/chị có khỏe không ạ? (tôn kính ngữ của おげんきですか)'),
(50, 'めいわくを　かけます', 'meiwakuwo　kakemasu', 'audio/minna/bai50/meiwakuwokakemasu.wav', '', '迷惑をかけます', '', 'làm phiền'),
(50, 'いかします', 'ikashimasu', 'audio/minna/bai50/ikashimasu.wav', '', '生かします', '', 'tận dụng, phát huy, dùng'),
(50, '「お」しろ', '「o」shiro', 'audio/minna/bai50/oshiro.wav', '', '[お]城', '', 'lâu đài'),
(50, 'けいぐ', 'keigu', 'audio/minna/bai50/keigu.wav', '', '敬具', '', 'kính thư'),
(50, 'ミュンヘン', 'myunhen', 'audio/minna/bai50/myunhen.wav', '', '', '', 'Munich (ở Đức)');