-- Bài 48
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(48, 'おろします', 'oroshimasu', 'audio/minna/bai48/oroshimasu.mp3', '', '降ろします,下ろします', 'GIÁNG, HẠ', 'cho xuống, hạ xuống'),
(48, 'とどけます', 'todokemasu', 'audio/minna/bai48/todokemasu.mp3', '', '届けます', 'GIỚI', 'gởi đến, chuyển đến'),
(48, 'せわをします', 'sewawoshimasu', 'audio/minna/bai48/sewawoshimasu.mp3', '', '世話をします', 'THẾ THOẠI', 'chăm sóc'),
(48, 'いや[な]', 'iya［na］', 'audio/minna/bai48/iya.mp3', '', '嫌[な]', 'HIỀM', 'ngán, không thích'),
(48, 'きびしい', 'kibishii', 'audio/minna/bai48/kibishii.mp3', '', '厳しい', 'NGHIÊM', 'nghiêm, nghiêm khắc, nghiêm ngặt'),
(48, 'じゅく', 'juku', 'audio/minna/bai48/juku.mp3', '', '塾', 'THỤC', 'cơ sở học thêm'),
(48, 'スケジュール', 'sukeju-ru', 'audio/minna/bai48/k_sukejuuru.mp3', '', '', '', 'thời khóa biểu, lịch làm việc'),
(48, 'せいと', 'seito', 'audio/minna/bai48/seito.mp3', '', '生徒', 'SINH ĐỒ', 'học sinh, học trò'),
(48, 'もの', 'mono', 'audio/minna/bai48/mono.mp3', '', '者', 'GIẢ', 'người (là người thân hoặc cấp dưới)'),
(48, 'にゅうかん', 'nyuukan', 'audio/minna/bai48/nyuukan.mp3', '', '入管', 'NHẬP QUẢN', 'Cục quản lý nhập cảnh'),
(48, 'さいにゅうこくビザ', 'sainyuukokubiza', 'audio/minna/bai48/sainyuukokubiza.mp3', '', '再入国ビザ', 'TÁI NHẬP QUỐC', 'Thị thực tái nhập cảnh'),
(48, 'じゆうに', 'jiyuuni', 'audio/minna/bai48/jiyuuni.mp3', '', '自由に', 'TỰ DO', 'tự do'),
(48, '～かん', '～kan', 'audio/minna/bai48/kan.mp3', '', '～間', 'GIAN', 'trong ~ (dùng để chỉ khoảng thời gian)'),
(48, 'いいことですね。', 'iikotodesune', 'audio/minna/bai48/iikotodesune.mp3', '', '', '', 'Hay nhỉ./ Được đấy nhỉ.'),
(48, 'おいそがしいですか', 'oisogashiidesuka', 'audio/minna/bai48/oisogashiidesuka.mp3', '', 'お忙しいですか。', 'MANG', 'Anh/chị có bận không? (được dùng khi nói với người trên)'),
(48, 'ひさしぶり', 'hisashiburi', 'audio/minna/bai48/hisashiburi.mp3', '', '久しぶり', 'CỬU', 'lâu'),
(48, 'えいぎょう', 'eigyou', 'audio/minna/bai48/eigyou.mp3', '', '営業', 'DOANH NGHIỆP', 'kinh doanh, bán hàng'),
(48, 'それまでに', 'soremadeni', 'audio/minna/bai48/soremadeni.mp3', '', '', '', 'trước thời điểm đó'),
(48, 'かまいません', 'kamaimasen', 'audio/minna/bai48/kamaimasen.mp3', '', '', '', 'Không sao./ Không có vấn đề gì.'),
(48, 'たのしみます', 'tanoshimimasu', 'audio/minna/bai48/tanoshimimasu.mp3', '', '楽しみます', 'LẠC/NHẠC', 'vui, vui thích'),
(48, 'もともと', 'motomoto', 'audio/minna/bai48/motomoto.wav', '', '', '', 'vốn dĩ'),
(48, '―せいき', '-seiki', 'audio/minna/bai48/seiki.wav', '', '―世紀', 'THẾ KỶ', 'thế kỷ -'),
(48, 'かわりをします', 'kawariwoshimasu', 'audio/minna/bai48/kawariwoshimasu.wav', '', '代わりをします', 'ĐẠI', 'thay thế'),
(48, 'スピード', 'supi-do', 'audio/minna/bai48/supido.wav', '', '', '', 'tốc độ'),
(48, 'きょうそうします', 'kyousoushimasu', 'audio/minna/bai48/kyousoushimasu.wav', '', '競走します', 'CẠNH TẨU', 'chạy đua, thi chạy'),
(48, 'サーカス', 'sa-kasu', 'audio/minna/bai48/sakasu.wav', '', '', '', 'xiếc'),
(48, 'げい', 'gei', 'audio/minna/bai48/gei.wav', '', '芸', 'NGHỆ', 'trò diễn, tiết mục, tài năng'),
(48, 'うつくしい', 'utsukushii', 'audio/minna/bai48/utsukushii.wav', '', '美しい', 'MỸ', 'đẹp'),
(48, 'すがた', 'sugata', 'audio/minna/bai48/sugata.wav', '', '姿', 'TƯ', 'dáng điệu, tư thế'),
(48, 'こころ', 'kokoro', 'audio/minna/bai48/kokoro.wav', '', '心', 'TÂM', 'trái tim, tấm lòng, cảm tình'),
(48, 'とらえます', 'toraemasu', 'audio/minna/bai48/toraemasu.wav', '', '', '', 'giành được'),
(48, '～にとって', '～nitotte', 'audio/minna/bai48/nitotte.wav', '', '', '', 'đối với ~');