-- Bài 22
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(22, '[シャツを～]きます', '[shatsuwo～]kimasu', 'audio/minna/bai22/kimasu.mp3', '', '[シャツを～]着ます', 'TRƯỚC', 'mặc [áo sơ mi, v.v.]'),
(22, '[くつを～] はきます', '[kutsuwo～] hakimasu', 'audio/minna/bai22/hakimasu.mp3', '', '[靴を～]', 'NGOA', 'đi, mặc [giầy, quần âu, v.v.]'),
(22, '[ぼうしを～]かぶります', '[boushiwo～]kaburimasu', 'audio/minna/bai22/kaburimasu.mp3', '', '[帽子を～]', 'MẠO TỬ', 'đội [mũ, v.v.]'),
(22, '[めがねを～]かけます', '[meganewo～]kakemasu', 'audio/minna/bai22/kakemasu.mp3', '', '[眼鏡を～]', 'NHÃN KÍNH', 'đeo [kính]'),
(22, 'うまれます', 'umaremasu', 'audio/minna/bai22/umaremasu.mp3', '', '生まれます', 'SINH', 'sinh ra'),
(22, 'コート', 'koｰto', 'audio/minna/bai22/k_kooto.mp3', '', '', '', 'áo khoác'),
(22, 'スーツ', 'suｰtsu', 'audio/minna/bai22/k_suutsu.mp3', '', '', '', 'com-lê'),
(22, 'セーター', 'seｰtaｰ', 'audio/minna/bai22/k_seetaa.mp3', '', '', '', 'áo len'),
(22, 'ぼうし', 'boushi', 'audio/minna/bai22/boushi.mp3', '', '帽子', 'MẠO TỬ', 'mũ'),
(22, 'めがね', 'megane', 'audio/minna/bai22/megane.mp3', '', '眼鏡', 'NHÃN KÍNH', 'kính'),
(22, 'よく', 'yoku', 'audio/minna/bai22/yoku.mp3', '', '', '', 'tốt, rõ (chỉ mức độ)'),
(22, 'おめでとう　ございます。', 'omedetou gozaimasu｡', 'audio/minna/bai22/omedetougozaimasu.mp3', '', '', '', 'Chúc mừng.'),
(22, 'こちら', 'kochira', 'audio/minna/bai22/kochira.mp3', '', '', '', 'phía này, đằng này, chỗ này, đây'),
(22, 'やちん', 'yachin', 'audio/minna/bai22/yachin.mp3', '', '家賃', 'GIA NHẪM', 'tiền thuê nhà'),
(22, 'うーん。', 'uｰn｡', 'audio/minna/bai22/uun.mp3', '', '', '', 'ừ~./ Để tôi xem./ Thế nào nhỉ.'),
(22, 'ダイニングキチン', 'dainingukichin', 'audio/minna/bai22/k_dainingukichin.mp3', '', '', '', 'bếp kèm phòng ăn'),
(22, 'わしつ', 'washitsu', 'audio/minna/bai22/washitsu.wav', '', '和室', 'HÒA THẤT', 'phòng kiểu Nhật'),
(22, 'おしいれ', 'oshiire', 'audio/minna/bai22/oshiire.mp3', '', '押入れ', 'ÁP NHẬP', 'Chổ để chăn gối trong một căn phòng kiểu Nhật'),
(22, 'ふとん', 'futon', 'audio/minna/bai22/futon.mp3', '', '布団', 'BỐ ĐOÀN', 'chăn, đệm'),
(22, 'アパート', 'apaｰto', 'audio/minna/bai22/k_apaato.mp3', '', '', '', 'nhà chung cư'),
(22, 'パリ', 'pari', 'audio/minna/bai22/k_pari.wav', '', '', '', 'Pari'),
(22, 'ばんりのちょうじょう', 'banrinochoujou', 'audio/minna/bai22/banrinochoujou.wav', '', '万里の長城', 'VẠN LÝ TRƯỜNG THÀNH', 'Vạn Lý Trường Thành'),
(22, 'よかかいはつセンター', 'yokakaihatsudentaｰ', 'audio/minna/bai22/yokakaihatsusenta.wav', '', '余暇開発センター', 'DƯ HẠ KHAI PHÁT', 'Trung tâm phát triển hoạt động giải trí cho người dân'),
(22, 'レジャーはくしょ', 'rejaｰhakusho', 'audio/minna/bai22/rejahakusho.wav', '', 'レジャー白書', 'BẠCH THƯ', 'sách trắng về sử dụng thời gian rảnh rỗi');