-- Bài 39
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(39, '[しつもんに～]こたえます', '［shitsumonni～］kotaemasu', 'audio/minna/bai39/kotaemasu.mp3', '', '[質問に～]答えます', 'CHẤT VẤN ĐÁP', 'trả lời [câu hỏi]'),
(39, '[ビルが～]たおれます', '［biruga～］taoremasu', 'audio/minna/bai39/taoremasu.mp3', '', '[ビルが～]倒れます', 'ĐẢO', 'đổ [nhà cao tầng ~]'),
(39, '[うちが～]やけます', '［uchiga～］yakemasu', 'audio/minna/bai39/yakemasu.mp3', '', '[うちが～]焼けます', 'THIÊU', 'cháy [nhà ~]'),
(39, '[パンが～]やけます', '［panga～］yakemasu', 'audio/minna/bai39/yakemasu.mp3', '', '[パンが～]焼けます', 'THIÊU', 'được nướng [bánh mì ~]'),
(39, '[にくが～]やけます', '［nikuga～］yakemasu', 'audio/minna/bai39/yakemasu.mp3', '', '[肉が～]焼けます', 'NHỤC THIÊU', 'được nướng [thịt ~]'),
(39, '[みちを～]とおります', '［michiwo～］toorimasu', 'audio/minna/bai39/toorimasu.mp3', '', '[道を～]通ります', 'ĐẠO THÔNG', 'đi qua (đường)'),
(39, 'しにます', 'shinimasu', 'audio/minna/bai39/shinimasu.mp3', '', '死にます', 'TỬ', 'chết'),
(39, 'びっくりします', 'bikkurishimasu', 'audio/minna/bai39/bikkurishimasu.mp3', '', '', '', 'ngạc nhiên, giật mình'),
(39, 'がっかりします', 'gakkarishimasu', 'audio/minna/bai39/gakkariashimasu.mp3', '', '', '', 'thất vọng'),
(39, 'あんしんします', 'anshinshimasu', 'audio/minna/bai39/anshinshimasu.mp3', '', '安心します', 'AN TÂM', 'yên tâm'),
(39, 'ちこくします', 'chikokushimasu', 'audio/minna/bai39/chikokushimasu.mp3', '', '遅刻します', 'TRÌ KHẮC', 'đến chậm, đến muộn'),
(39, 'そうたいします', 'soutaishimasu', 'audio/minna/bai39/soutaishimasu.mp3', '', '早退します', 'TẢO THOÁI', 'về sớm, ra sớm (việc làm hay trường học)'),
(39, 'けんかします', 'kenkashimasu', 'audio/minna/bai39/kenkashimasu.mp3', '', '', '', 'cãi nhau'),
(39, 'りこんします', 'rikonshimasu', 'audio/minna/bai39/rikonshimasu.mp3', '', '離婚します', 'LY HÔN', 'ly dị, ly hôn'),
(39, 'ふくざつ[な]', 'fukuzatsu［na］', 'audio/minna/bai39/fukuzatsu.mp3', '', '複雑[な]', 'PHỨC TẠP', 'phức tạp'),
(39, 'じゃま[な]', 'jama［na］', 'audio/minna/bai39/jama.mp3', '', '邪魔[な]', 'TÀ MA', 'cản trở, chiếm diện tích'),
(39, 'きたない', 'kitanai', 'audio/minna/bai39/kitanai.mp3', '', '汚い', 'Ô', 'bẩn'),
(39, 'うれしい', 'ureshii', 'audio/minna/bai39/ureshii.mp3', '', '', '', 'vui, mừng'),
(39, 'かなしい', 'kanashii', 'audio/minna/bai39/kanashii.mp3', '', '悲しい', 'BI', 'buồn, đau thương'),
(39, 'はずかしい', 'hazukashii', 'audio/minna/bai39/hazukashii.mp3', '', '恥ずかしい', 'SỈ', 'xấu hổ, thẹn, hổ thẹn'),
(39, 'じしん', 'jishin', 'audio/minna/bai39/jishin.mp3', '', '地震', 'ĐỊA CHẤN', 'động đất'),
(39, 'たいふう', 'taifuu', 'audio/minna/bai39/taifuu.mp3', '', '台風', 'ĐÀI PHONG', 'bão'),
(39, 'かじ', 'kaji', 'audio/minna/bai39/kaji.mp3', '', '火事', 'HỎA SỰ', 'hỏa hoạn'),
(39, 'じこ', 'jiko', 'audio/minna/bai39/jiko.mp3', '', '事故', 'SỰ CỐ', 'tai nạn, sự cố'),
(39, '[お]みあい', '［o］miai', 'audio/minna/bai39/omiai.mp3', '', '[お]見合い', 'KIẾN HỢP', 'Nam nữ làm quen qua giới thiệu, làm mối'),
(39, 'でんわだい', 'denwadai', 'audio/minna/bai39/denwadai.mp3', '', '電話代', 'ĐIỆN THOẠI ĐẠI', 'tiền điện thoại, phí điện thoại'),
(39, '～だい', '～dai', 'audio/minna/bai39/dai.mp3', '', '～代', 'ĐẠI', 'tiền ~, phí ~'),
(39, 'フロント', 'furonto', 'audio/minna/bai39/k_furonto.mp3', '', '', '', 'bộ phận tiếp tân, bộ phận thường trực'),
(39, '―ごうしつ', '-goushitsu', 'audio/minna/bai39/goushitsu.mp3', '', '―号室', 'HIỆU THẤT', 'phòng số -'),
(39, 'あせ', 'ase', 'audio/minna/bai39/ase.mp3', '', '汗', 'HÃN', 'mồ hôi (～をかきます：ra mồ hôi)'),
(39, 'タオル', 'taoru', 'audio/minna/bai39/k_taoru.mp3', '', '', '', 'khăn lau, khăn tắm'),
(39, 'せっけん', 'sekken', 'audio/minna/bai39/sekken.mp3', '', '', '', 'xà phòng'),
(39, 'おおぜい', 'oozei', 'audio/minna/bai39/oozei.mp3', '', '大勢', 'ĐẠI THẾ', 'nhiều người'),
(39, 'おつかれさまでした。', 'otsukaresamadeshita', 'audio/minna/bai39/otsukaresamadeshita.mp3', '', 'お疲れ様でした。', 'BÌ DẠNG', 'Chắc anh chị đã mệt vì làm việc. (câu chào dùng để nói với người đã làm xong một việc gì đó)'),
(39, 'うかがいます。', 'ukagaimasu', 'audio/minna/bai39/ukagaimasu.mp3', '', '伺います。', 'TỨ', 'Tôi đến thăm. (cách nói khiêm nhường của いきます)'),
(39, 'とちゅうで', 'tochuude', 'audio/minna/bai39/tochuude.mp3', '', '途中で', 'ĐỒ TRUNG', 'giữa đường, dọc đường, giữa chừng'),
(39, 'トラック', 'torakku', 'audio/minna/bai39/k_torakku.mp3', '', '', '', 'xe tải'),
(39, 'ぶつかります', 'butsukarimasu', 'audio/minna/bai39/butsukarimasu.mp3', '', '', '', 'đâm, va chạm'),
(39, 'ならびます', 'narabimasu', 'audio/minna/bai39/narabimasu.mp3', '', '並びます', 'TỊNH', 'xếp hàng'),
(39, 'おとな', 'otona', 'audio/minna/bai39/otona.wav', '', '大人', 'ĐẠI NHÂN', 'người lớn'),
(39, 'ようふく', 'youfuku', 'audio/minna/bai39/youfuku.wav', '', '洋服', 'DƯƠNG PHỤC', 'quần áo kiểu Tây Âu'),
(39, 'せいようかします', 'seiyoukashimasu', 'audio/minna/bai39/seiyoukashimasu.wav', '', '西洋化します', 'TÂY DƯƠNG HÓA', 'Tây Âu hóa'),
(39, 'あいます', 'aimasu', 'audio/minna/bai39/aimasu.wav', '', '合います', 'HỢP', 'vừa, hợp'),
(39, 'いまでは', 'imadeha', 'audio/minna/bai39/imadeha.wav', '', '今では', 'KIM', 'bây giờ (thì)'),
(39, 'せいじんしき', 'seijinshiki', 'audio/minna/bai39/seijinshiki.wav', '', '成人式', 'THÀNH NHÂN THỨC', 'Lễ trưởng thành, Lễ thành Nhân'),
(39, 'ふしぎ「な」', 'fushigi「na」', 'audio/minna/bai39/fushigi.wav', '', '不思議[な]', 'BẤT TƯ NGHỊ', 'bí ẩn, kỳ thú, khó hiểu');