-- Bài 46
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(46, 'やきます', 'yakimasu', 'audio/minna/bai46/yakimasu.mp3', '', '焼きます', 'THIÊU', 'nướng, rán'),
(46, 'わたします', 'watashimasu', 'audio/minna/bai46/watashimasu.mp3', '', '渡します', 'ĐỘ', 'đưa cho, giao cho'),
(46, 'かえってきます', 'kaettekimasu', 'audio/minna/bai46/kaettekimasu.mp3', '', '帰って来ます', 'QUY LAI', 'về, trở lại'),
(46, '[バスが～]でます', '［basuga～］demasu', 'audio/minna/bai46/demasu.mp3', '', '[バスが～]出ます', 'XUẤT', 'xuất phát, chạy [xe buýt ~]'),
(46, 'るす', 'rusu', 'audio/minna/bai46/rusu.mp3', '', '留守', 'LƯU THỦ', 'đi vắng'),
(46, 'たくはいびん', 'takuhaibin', 'audio/minna/bai46/takuhaibin.mp3', '', '宅配便', 'TRẠCH PHỐI TIỆN', 'dịch vụ chuyển đồ đến nhà'),
(46, 'げんいん', 'genin', 'audio/minna/bai46/genin.mp3', '', '原因', 'NGUYÊN NHÂN', 'nguyên nhân'),
(46, 'ちゅうしゃ', 'chuusha', 'audio/minna/bai46/chuusya.mp3', '', '注射', 'CHÚ XẠ', 'tiêm'),
(46, 'しょくよく', 'shokuyoku', 'audio/minna/bai46/syokuyoku.mp3', '', '食欲', 'THỰC DỤC', 'cảm giác muốn ăn, cảm giác ngon miệng'),
(46, 'パンフレット', 'panfuretto', 'audio/minna/bai46/k_panfuretto.mp3', '', '', '', 'tờ rơi, tờ quảng cáo'),
(46, 'ステレオ', 'sutereo', 'audio/minna/bai46/k_sutereo.mp3', '', '', '', 'stereo'),
(46, 'こちら', 'kochira', 'audio/minna/bai46/kochira.mp3', '', '', '', 'đây, đằng này'),
(46, '～のところ', '～notokoro', 'audio/minna/bai46/notokoro.mp3', '', '～の所', 'SỞ', 'quanh ~, xung quanh ~'),
(46, 'ちょうど', 'choudo', 'audio/minna/bai46/choudo.mp3', '', '', '', 'vừa đúng'),
(46, 'たったいま', 'tattaima', 'audio/minna/bai46/tattaima.mp3', '', 'たった今', 'KIM', 'vừa mới rồi'),
(46, 'いまいいでしょうか。', 'imaiideshouka', 'audio/minna/bai46/imaiidesyouka.mp3', '', '今いいでしょうか。', 'KIM', 'Bây giờ tôi làm phiền anh có được không ạ?'),
(46, 'ガスサービスセンター', 'gasusa-bisusenta-', 'audio/minna/bai46/k_gasusaabisusentaa.mp3', '', '', '', 'trung tâm dịch vụ ga'),
(46, 'ガスレンジ', 'gasurenji', 'audio/minna/bai46/gasurenji.mp3', '', '', '', 'bếp ga'),
(46, 'ぐあい', 'guai', 'audio/minna/bai46/guai.mp3', '', '具合', 'CỤ HỢP', 'trạng thái, tình hình'),
(46, 'どちらさまでしょうか', 'dochirasamadeshouka', 'audio/minna/bai46/dochirasamadesyouka.mp3', '', 'どちら様でしょうか。', 'DẠNG', 'Ai đấy ạ?'),
(46, 'むかいます', 'mukaimasu', 'audio/minna/bai46/mukaimasu.mp3', '', '向かいます', 'HƯỚNG', 'hướng đến, trên đ��ờng đến'),
(46, 'おまたせしました', 'omataseshimashita', 'audio/minna/bai46/omataseshimashita.mp3', '', 'お待たせしました', 'ĐÃI', 'Xin lỗi vì để anh/ Chị phải đợi'),
(46, 'ちしき', 'chishiki', 'audio/minna/bai46/chishiki.wav', '', '知識', 'TRI THỨC', 'tri thức, kiến thức'),
(46, 'ほうこ', 'houko', 'audio/minna/bai46/houko.wav', '', '宝庫', 'BẢO KHỐ', 'kho báu'),
(46, 'てに　はいります「じょうほう」', 'teni　hairimasu「jouhou」', 'audio/minna/bai46/tenihairimasu.wav', '', '手に入ります[情報が～]', 'THỦ NHẬP  TÌNH BÁO', 'lấy được, thu thập được [Thông tin]'),
(46, 'システム', 'shisutemu', 'audio/minna/bai46/shisutemu.wav', '', '', '', 'hệ thống'),
(46, 'たとえば', 'tatoeba', 'audio/minna/bai46/tatoeba.wav', '', '例えば', 'LỆ', 'ví dụ, chẳng hạn'),
(46, 'キーワード', 'ki-wa-do', 'audio/minna/bai46/kiwado.wav', '', '', '', 'từ khóa'),
(46, 'いちぶぶん', 'ichibubun', 'audio/minna/bai46/ichibubun.wav', '', '一部分', 'NHẤT BỘ PHẬN', 'một bộ phận'),
(46, 'にゅうりょくします', 'nyuuryokushimasu', 'audio/minna/bai46/nyuryokushimasu.wav', '', '入力します', 'NHẬP LỰC', 'nhập'),
(46, 'びょう', 'byou', 'audio/minna/bai46/byo.wav', '', '秒', 'MIẾU', 'giây'),
(46, 'でます「ほんが～」', 'demasu「honga～」', 'audio/minna/bai46/demasu.mp3', '', 'でます[本が～]', 'BẢN', 'được xuất bản [quyển sách ~]');