-- Bài 27
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(27, 'かいます', 'kaimasu', 'audio/minna/bai27/kaimasu.mp3', '', '飼います', 'TỰ', 'nuôi (động vật)'),
(27, 'たてます', 'tatemasu', 'audio/minna/bai27/tatemasu.mp3', '', '建てます', 'KIẾN', 'xây, xây dựng'),
(27, '[みちを～]はしります', '［michiwo～］hashirimasu', 'audio/minna/bai27/hashirimasu.mp3', '', '[道を～]走ります', 'ĐẠO TẨU', 'chạy [trên đường]'),
(27, '[やすみを～]とります', '［yasumiwo～］torimasu', 'audio/minna/bai27/torimasu.mp3', '', '[休みを～]取ります', 'HƯU THỦ', 'xin [nghỉ]'),
(27, '[やまが～] みえます', '［yamaga～］　miemasu', 'audio/minna/bai27/miemasu.mp3', '', '[山が～]見えます', 'SƠN/SAN KIẾN', 'nhìn thấy, có thể nhìn thấy [núi]'),
(27, '[おとが～]きこえます', '［otoga～］kikoemasu', 'audio/minna/bai27/kikoemasu.mp3', '', '[音が～]聞こえます', 'ÂM VĂN', 'nghe thấy, có thể nghe thấy [âm thanh]'),
(27, '[くうこうが～]できます', '［kuukouga～］dekimasu', 'audio/minna/bai27/dekimasu.mp3', '', '[空港が～]', 'KHÔNG CẢNG', 'được xây dựng lên, hoàn thành [sân bay]'),
(27, '[きょうしつを～]ひらきます', '［kyoushitsuwo～］hirakimasu', 'audio/minna/bai27/hirakimasu.mp3', '', '[教室を～]開きます', 'GIÁO THẤT KHAI', 'mở [lớp học]'),
(27, 'ペット', 'petto', 'audio/minna/bai27/k_petto.mp3', '', '', '', 'động vật cảnh (pet)'),
(27, 'とり', 'tori', 'audio/minna/bai27/tori.mp3', '', '鳥', 'ĐIẾU', 'chim'),
(27, 'こえ', 'koe', 'audio/minna/bai27/koe.mp3', '', '声', 'THANH', 'tiếng nói, giọng nói'),
(27, 'なみ', 'nami', 'audio/minna/bai27/nami.mp3', '', '波', 'BA', 'sóng'),
(27, 'はなび', 'hanabi', 'audio/minna/bai27/hanabi.mp3', '', '花火', 'HOA HỎA', 'pháo hoa'),
(27, 'けしき', 'keshiki', 'audio/minna/bai27/keshiki.mp3', '', '景色', 'CẢNH SẮC', 'phong cảnh'),
(27, 'ひるま', 'hiruma', 'audio/minna/bai27/hiruma.mp3', '', '昼間', 'TRÚ GIAN', 'thời gian ban ngày'),
(27, 'むかし', 'mukashi', 'audio/minna/bai27/mukashi.mp3', '', '昔', 'TÍCH', 'ngày xưa, trước đây'),
(27, 'どうぐ', 'dougu', 'audio/minna/bai27/dougu.mp3', '', '道具', 'ĐẠO CỤ', 'dụng cụ, công cụ'),
(27, 'じどうはんばいき', 'jidouhanbaiki', 'audio/minna/bai27/jidouhanbaiki.mp3', '', '自動販売機', 'TỰ ĐỘNG PHIẾN MẠI CƠ', 'máy bán tự động'),
(27, 'つうしんはんばい', 'tsuushinhanbai', 'audio/minna/bai27/tsushinhanbai.mp3', '', '通信販売', 'THÔNG TÍN PHIẾN MẠI', 'thương mại viễn thông (mua bán hàng qua các phương tiện truyền thông)'),
(27, 'クリーニング', 'kuri-ningu', 'audio/minna/bai27/k_kuriiningu.mp3', '', '', '', 'giặt ủi'),
(27, 'マンション', 'manshon', 'audio/minna/bai27/k_mansyon.mp3', '', '', '', 'nhà chung cư'),
(27, 'だいどころ', 'daidokoro', 'audio/minna/bai27/daidokoro.mp3', '', '台所', 'ĐÀI SỞ', 'bếp'),
(27, '～きょうしつ', '～kyoushitsu', 'audio/minna/bai27/kyoushitsu.mp3', '', '～教室', 'GIÁO THẤT', 'lớp học ~'),
(27, 'パーティールーム', 'pa-ti-ru-mu', 'audio/minna/bai27/k_paatexiiruumu.mp3', '', '', '', 'phòng tiệc'),
(27, '～ご', '～go', 'audio/minna/bai27/go.mp3', '', '～後', 'HẬU', '~ sau (khoảng thời gian)'),
(27, '～しか', '～shika', 'audio/minna/bai27/shika.mp3', '', '', '', 'chỉ ~ (dùng với thể phủ định)'),
(27, 'ほかの', 'hokano', 'audio/minna/bai27/hokano.mp3', '', '', '', 'khác'),
(27, 'はっきり', 'hakkiri', 'audio/minna/bai27/hakkiri.mp3', '', '', '', 'rõ, rõ ràng'),
(27, 'ほとんど', 'hotondo', 'audio/minna/bai27/hotondo.mp3', '', '', '', 'hầu hết, hầu như'),
(27, 'かんさいくうこう', 'kansaikuukou', 'audio/minna/bai27/kansaikuukou.mp3', '', '関西空港', 'QUAN TÂY KHÔNG CẢNG', 'sân bay (quốc tế) Kansai'),
(27, 'あきはばら', 'akihabara', 'audio/minna/bai27/akihabara.mp3', '', '秋葉原', 'THU DIỆP NGUYÊN', 'tên một khu phố bán đồ điện tử nổi tiếng ở Tokyo'),
(27, 'いず', 'izu', 'audio/minna/bai27/izu.mp3', '', '伊豆', 'Y ĐẬU', 'một bán đảo thuộc tỉnh Shizuoka'),
(27, 'にちようだいく', 'nichiyoudaiku', 'audio/minna/bai27/nichiyoudaiku.wav', '', '日曜大工', 'NHẬT DIỆU ĐẠI CÔNG', 'làm thợ mộc chủ nhật'),
(27, 'ほんだな', 'hondana', 'audio/minna/bai27/hondana.mp3', '', '本棚', 'BỔN BẰNG', 'giá sách'),
(27, 'ゆめ', 'yume', 'audio/minna/bai27/yume.mp3', '', '夢', 'MỘNG', 'giấc mơ, ước mơ (~　をします：mơ, mơ ước)'),
(27, 'いつか', 'itsuka', 'audio/minna/bai27/itsuka.mp3', '', '', '', 'một ngày nào đó, một lúc nào đó'),
(27, 'いえ', 'ie', 'audio/minna/bai27/ie.mp3', '', '家', 'GIA', 'nhà'),
(27, 'すばらしい', 'subarashii', 'audio/minna/bai27/subarashi.mp3', '', '', '', 'tuyệt vời'),
(27, 'こどもたち', 'kodomotachi', 'audio/minna/bai27/kodomotachi.wav', '', '子どもたち', 'TỬ/TÝ', 'trẻ em, trẻ con, con cái'),
(27, 'だいすき「な」', 'daisuki「na」', 'audio/minna/bai27/daisuki.wav', '', '大好き[な]', 'ĐẠI HẢO', 'rất thích'),
(27, 'まんが', 'manga', 'audio/minna/bai27/manga.wav', '', '漫画', 'MẠN HỌA', 'truyện tranh'),
(27, 'しゅじんこう', 'shujinkou', 'audio/minna/bai27/shujinkou.wav', '', '主人公', 'CHỦ NHÂN CÔNG', 'nhân vật chính'),
(27, 'かたち', 'katachi', 'audio/minna/bai27/katachi.wav', '', '形', 'HÌNH', 'hình, dạng'),
(27, 'ロボット', 'robotto', 'audio/minna/bai27/robotto.wav', '', '', '', 'người máy, Rô-bốt'),
(27, 'ふしぎ「な」', 'fushigi「na」', 'audio/minna/bai27/fushigi.wav', '', '不思議[な]', 'BẤT TƯ NGHỊ', 'bí ẩn, kỳ thú'),
(27, 'ポケット', 'poketto', 'audio/minna/bai27/poketto.wav', '', '', '', 'túi áo, túi quần (Pocket)'),
(27, 'たとえば', 'tatoeba', 'audio/minna/bai27/tatoeba.wav', '', '例えば', 'LỆ', 'ví dụ (như)'),
(27, 'つけます', 'tsukemasu', 'audio/minna/bai27/tsukemasu.wav', '', '付けます', 'PHÓ', 'lắp, ghép thêm'),
(27, 'じゆうに', 'jiyuuni', 'audio/minna/bai27/jiyuuni.wav', '', '自由に', 'TỰ DO', 'tự do, tùy thích'),
(27, 'そら', 'sora', 'audio/minna/bai27/sora.wav', '', '空', 'KHÔNG', 'bầu trời'),
(27, 'とびます', 'tobimasu', 'audio/minna/bai27/tobimasu.wav', '', '飛びます', 'PHI', 'bay'),
(27, 'じぶん', 'jibun', 'audio/minna/bai27/jibun.wav', '', '自分', 'TỰ PHÂN', 'bản thân, mình'),
(27, 'しょうらい', 'shourai', 'audio/minna/bai27/shorai.wav', '', '将来', 'TƯƠNG LAI', 'tương lai'),
(27, 'ドラえもん', 'doraemon', 'audio/minna/bai27/doraemon.wav', '', '', '', 'tên một nhân vật trong phim hoạt hình (Doremon)');