-- Bài 15
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(15, 'たちます', 'tachimasu', '/audio/minna/bai15/tachimasu.mp3', 'verb', '立ちます', 'LẬP', 'đứng'),
(15, 'すわります', 'suwarimasu', '/audio/minna/bai15/suwarimasu.mp3', 'verb', '座ります', 'TỌA', 'ngồi'),
(15, 'つかいます', 'tsukaimasu', '/audio/minna/bai15/tsukaimasu.mp3', 'verb', '使います', 'SỬ, SỨ', 'dùng, sử dụng'),
(15, 'おきます', 'okimasu', '/audio/minna/bai15/okimasu.mp3', 'verb', '置きます', 'TRÍ', 'dậy, thức dậy'),
(15, 'つくります', 'tsukurimasu', '/audio/minna/bai15/tukurimasu.mp3', 'verb', '作ります, 造ります', 'TÁC TẠO', 'làm, chế tạo, sản xuất'),
(15, 'うります', 'urimasu', '/audio/minna/bai15/urimasu.mp3', 'verb', '売ります', 'MẠI', 'bán'),
(15, 'しります', 'shirimasu', '/audio/minna/bai15/shirimasu.mp3', 'verb', '知ります', 'TRI', 'biết'),
(15, 'すみます', 'sumimasu', '/audio/minna/bai15/sumimasu.mp3', 'verb', '住みます', 'TRÚ, TRỤ', 'sống, ở'),
(15, 'けんきゅうします', 'kenkyuushimasu', '/audio/minna/bai15/kenkyuushimasu.mp3', 'verb', '研究します', 'NGHIÊN CỬU', 'nghiên cứu'),
(15, 'しって　います', 'shitte imasu', '/audio/minna/bai15/shitteimasu.mp3', 'verb', '知って　います', 'TRI', 'biết'),
(15, '[おおさかに～]すんで　います', '[oosakani～]sunde imasu', '/audio/minna/bai15/sundeimasu.mp3', 'verb', '[大阪に～]住んで　います', 'ĐẠI PHẢN TRÚ/TRỤ', 'sống [ở Osaka]'),
(15, 'しりょう', 'shiryou', '/audio/minna/bai15/shiryou.mp3', 'noun', '資料', 'TƯ LIỆU', 'tài liệu, tư liệu'),
(15, 'カタログ', 'katarogu', '/audio/minna/bai15/k_katarogu.mp3', 'noun', NULL, NULL, 'ca-ta-lô'),
(15, 'じこくひょう', 'jikokuhyou', '/audio/minna/bai15/jikokuhyou.mp3', 'noun', '時刻表', 'THỜI KHẮC BIỂU', 'bảng giờ tàu chạy'),
(15, 'ふく', 'fuku', '/audio/minna/bai15/fuku.mp3', 'noun', '服', 'PHỤC', 'quần áo'),
(15, 'せいひん', 'seihin', '/audio/minna/bai15/seihin.mp3', 'noun', '製品', 'CHẾ PHẨM', 'sản phẩm'),
(15, 'ソフト', 'sofuto', '/audio/minna/bai15/k_sofuto.mp3', 'noun', NULL, NULL, 'phần mềm'),
(15, 'せんもん', 'senmon', '/audio/minna/bai15/senmon.mp3', 'noun', '専門', 'CHUYÊN MÔN', 'chuyên môn'),
(15, 'はいしゃ', 'haisha', '/audio/minna/bai15/haisya.mp3', 'noun', '歯医者', 'XỈ Y GIẢ', 'nha sĩ'),
(15, 'とこや', 'tokoya', '/audio/minna/bai15/tokoya.mp3', 'noun', '床屋', 'SÀNG ỐC', 'hiệu cắt tóc'),
(15, 'プレイガイド', 'pureigaido', '/audio/minna/bai15/k_pureigaido.mp3', 'noun', NULL, NULL, 'quầy bán vé (trong nhà hát)'),
(15, 'どくしん', 'dokushin', '/audio/minna/bai15/dokushin.mp3', 'noun', '独身', 'ĐỘC THÂN', 'độc thân'),
(15, 'とくに', 'tokuni', '/audio/minna/bai15/tokuni.mp3', 'adverb', '特に', 'ĐẶC', 'đặc biệt'),
(15, 'おもいだします', 'omoidashimasu', '/audio/minna/bai15/omoidashimasu.mp3', 'verb', '思い出します', 'TƯ XUẤT', 'nhớ lại, hồi tưởng'),
(15, 'ごかぞく', 'gokazoku', '/audio/minna/bai15/gokazoku.mp3', 'noun', 'ご家族', 'GIA TỘC', 'gia đình (dùng cho người khác)'),
(15, 'いらっしゃいます', 'irasshaimasu', '/audio/minna/bai15/irassyaimasu.mp3', 'verb', NULL, NULL, 'thể kính trọng của "います"'),
(15, 'こうこう', 'koukou', '/audio/minna/bai15/koukou.mp3', 'noun', '高校', 'CAO HIỆU', 'trường trung học phổ thông'),
(15, 'にっぽんばし', 'nipponbashi', '/audio/minna/bai15/nipponbashi.wav', 'noun', '日本橋', 'NHẬT BẢN KIỀU', 'tên một khu phố buôn bán ở Osaka'); 