-- Bài 11
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(11, '[こどもが～] います', '[kodomoga～] imasu', '/audio/minna/bai11/Minna_bai11_1.mp3', 'verb', '[子供が～]', 'TỬ CUNG', 'có [con]'),
(11, '[にほんに～] います', '[nihonni～] imasu', '/audio/minna/bai11/nihonniimasu.wav', 'verb', '[日本に～]', 'NHẬT BẢN', 'ở [Nhật]'),
(11, 'かかります', 'kakarimasu', '/audio/minna/bai11/Minna_bai11_3.mp3', 'verb', NULL, NULL, 'mất, tốn (thời gian, tiền bạc)'),
(11, '[かいしゃを～] やすみます', '[kaishawo～] yasumimasu', '/audio/minna/bai11/Minna_bai11_4.mp3', 'verb', '[会社を～]休みます', 'HỘI XÃ HƯU', 'nghỉ [làm việc]'),
(11, 'ひとつ', 'hitotsu', '/audio/minna/bai11/Minna_bai11_5.mp3', 'counter', '１つ', NULL, 'một cái (dùng để đếm đồ vật)'),
(11, 'ふたつ', 'futatsu', '/audio/minna/bai11/Minna_bai11_6.mp3', 'counter', '２つ', NULL, 'hai cái'),
(11, 'みっつ', 'mittsu', '/audio/minna/bai11/Minna_bai11_7.mp3', 'counter', '３つ', NULL, 'ba cái'),
(11, 'よっつ', 'yottsu', '/audio/minna/bai11/Minna_bai11_8.mp3', 'counter', '４つ', NULL, 'bốn cái'),
(11, 'いつつ', 'itsutsu', '/audio/minna/bai11/Minna_bai11_9.mp3', 'counter', '５つ', NULL, 'năm cái'),
(11, 'むっつ', 'muttsu', '/audio/minna/bai11/Minna_bai11_10.mp3', 'counter', '６つ', NULL, 'sáu cái'),
(11, 'ななつ', 'nanatsu', '/audio/minna/bai11/Minna_bai11_11.mp3', 'counter', '７つ', NULL, 'bảy cái'),
(11, 'やっつ', 'yattsu', '/audio/minna/bai11/Minna_bai11_12.mp3', 'counter', '８つ', NULL, 'tám cái'),
(11, 'ここのつ', 'kokonotsu', '/audio/minna/bai11/Minna_bai11_13.mp3', 'counter', '９つ', NULL, 'chín cái'),
(11, 'とお', 'too', '/audio/minna/bai11/Minna_bai11_14.mp3', 'counter', '10', NULL, 'mười cái'),
(11, 'いくつ', 'ikutsu', '/audio/minna/bai11/Minna_bai11_15.mp3', 'question', NULL, NULL, 'mấy cái, bao nhiêu cái'),
(11, 'ひとり', 'hitori', '/audio/minna/bai11/Minna_bai11_16.mp3', 'counter', '１人', 'NHÂN', 'một người'),
(11, 'ふたり', 'futari', '/audio/minna/bai11/Minna_bai11_17.mp3', 'counter', '２人', 'NHÂN', 'hai người'),
(11, '―にん', '～nin', '/audio/minna/bai11/Minna_bai11_18.mp3', 'counter', '－人', 'NHÂN', '- người'),
(11, '―だい', '～dai', '/audio/minna/bai11/Minna_bai11_19.mp3', 'counter', '－台', 'ĐÀI', '- cái (dùng để đếm máy móc, xe cộ v.v.)'),
(11, '―まい', '～mai', '/audio/minna/bai11/Minna_bai11_20.mp3', 'counter', '－枚', 'MAI', '- tờ, tấm'),
(11, '―かい', '～kai', '/audio/minna/bai11/Minna_bai11_21.mp3', 'counter', '―回', 'HỒI', '- lần'),
(11, 'りんご', 'ringo', '/audio/minna/bai11/Minna_bai11_22.mp3', 'noun', NULL, NULL, 'táo'),
(11, 'みかん', 'mikan', '/audio/minna/bai11/Minna_bai11_23.mp3', 'noun', NULL, NULL, 'quýt'),
(11, 'サンドイッチ', 'sandoicchi', '/audio/minna/bai11/Minna_bai11_25.mp3', 'noun', NULL, NULL, 'bánh San Uých'),
(11, 'カレー[ライス]', 'kareｰ[raisu]', '/audio/minna/bai11/Minna_bai11_26.mp3', 'noun', NULL, NULL, 'món [cơm] ca-ri'),
(11, 'アイスクリーム', 'aisukuriｰmu', '/audio/minna/bai11/Minna_bai11_27.mp3', 'noun', NULL, NULL, 'kem'),
(11, 'きって', 'kitte', '/audio/minna/bai11/Minna_bai11_28.mp3', 'noun', '切手', 'THIẾT THỦ', 'tem'),
(11, 'はがき', 'hagaki', '/audio/minna/bai11/Minna_bai11_29.mp3', 'noun', NULL, NULL, 'bưu thiếp'),
(11, 'ふうとう', 'fuutou', '/audio/minna/bai11/Minna_bai11_30.mp3', 'noun', '封筒', 'PHONG ĐỒNG', 'phong bì'),
(11, 'そくたつ', 'sokutatsu', '/audio/minna/bai11/Minna_bai11_31.mp3', 'noun', '速達', 'TỐC ĐẠT', '(bưu phẩm) gửi nhanh'),
(11, 'かきとめ', 'kakitome', '/audio/minna/bai11/Minna_bai11_32.mp3', 'noun', '書留', 'THƯ LƯU', '(bưu phẩm) gửi bảo đảm'),
(11, 'エアメール', 'eameｰru', '/audio/minna/bai11/Minna_bai11_33.mp3', 'noun', NULL, NULL, '(Air Mail) thư chuyển bằng đường hàng khô'),
(11, 'こうくうびん', 'koukuubin', '/audio/minna/bai11/Minna_bai11_34.mp3', 'noun', '航空便', 'HÀNG KHÔNG TIỆN', 'gửi bằng đường hàng không'),
(11, 'ふなびん', 'funabin', '/audio/minna/bai11/Minna_bai11_35.mp3', 'noun', '船便', 'THUYỀN TIỆN', 'gửi bằng đường biển'),
(11, 'りょうしん', 'ryoushin', '/audio/minna/bai11/Minna_bai11_36.mp3', 'noun', '両親', 'LƯỠNG THÂN', 'bố mẹ'),
(11, 'きょうだい', 'kyoudai', '/audio/minna/bai11/Minna_bai11_37.mp3', 'noun', '兄弟', 'HUYNH ĐỆ', 'anh chị em'),
(11, 'あに', 'ani', '/audio/minna/bai11/Minna_bai11_38.mp3', 'noun', '兄', 'HUYNH', 'anh trai'),
(11, 'おにいさん', 'oniisan', '/audio/minna/bai11/Minna_bai11_39.mp3', 'noun', 'お兄さん', 'HUYNH', 'anh trai (dùng cho người khác)'),
(11, 'あね', 'ane', '/audio/minna/bai11/Minna_bai11_40.mp3', 'noun', '姉', 'TỶ', 'chị gái'),
(11, 'おねえさん', 'oneesan', '/audio/minna/bai11/Minna_bai11_41.mp3', 'noun', 'お姉さん', 'TỶ', 'chị gái (dùng cho người khác)'),
(11, 'おとうと', 'otouto', '/audio/minna/bai11/Minna_bai11_42.mp3', 'noun', '弟', 'ĐỆ', 'em trai'),
(11, 'おとうとさん', 'otoutosan', '/audio/minna/bai11/Minna_bai11_43.mp3', 'noun', '弟さん', 'ĐỆ', 'em trai (dùng cho người khác)'),
(11, 'いもうと', 'imouto', '/audio/minna/bai11/Minna_bai11_44.mp3', 'noun', '妹', 'MUỘI', 'em gái'),
(11, 'いもうとさん', 'imoutosan', '/audio/minna/bai11/Minna_bai11_45.mp3', 'noun', '妹さん', 'MUỘI', 'em gái (dùng cho người khác)'),
(11, 'がいこく', 'gaikoku', '/audio/minna/bai11/Minna_bai11_46.mp3', 'noun', '外国', 'NGOẠI QUỐC', 'nước ngoài'),
(11, '―じかん', '～jikan', '/audio/minna/bai11/Minna_bai11_47.mp3', 'counter', '―時間', 'THỜI GIAN', '- tiếng'),
(11, '―しゅうかん', '～shuukan', '/audio/minna/bai11/Minna_bai11_48.mp3', 'counter', '―週間', 'CHU GIAN', '- tuần'),
(11, '―かげつ', '～kagetsu', '/audio/minna/bai11/Minna_bai11_49.mp3', 'counter', '－か月', 'NGUYỆT', '- tháng'),
(11, '―ねん', '～nen', '/audio/minna/bai11/Minna_bai11_50.mp3', 'counter', '―年', 'NIÊN', '- năm'),
(11, '～ぐらい', '～gurai', '/audio/minna/bai11/Minna_bai11_51.mp3', 'particle', NULL, NULL, 'khoảng ~'),
(11, 'どのくらい', 'donokurai', '/audio/minna/bai11/Minna_bai11_52.mp3', 'question', NULL, NULL, 'bao lâu'),
(11, 'ぜんぶで', 'zenbude', '/audio/minna/bai11/Minna_bai11_53.mp3', 'adverb', '全部で', 'TOÀN BỘ', 'tổng cộng'),
(11, 'みんな', 'minna', '/audio/minna/bai11/Minna_bai11_54.mp3', 'adverb', NULL, NULL, 'tất cả'),
(11, '～だけ', '～dake', '/audio/minna/bai11/Minna_bai11_55.mp3', 'particle', NULL, NULL, 'chỉ ~'),
(11, 'いらっしゃいませ。', 'irasshaimase｡', '/audio/minna/bai11/Minna_bai11_56.mp3', 'phrase', NULL, NULL, 'Xin mời vào./ xin chào quý khách.'),
(11, 'いい[お]てんきですね。', 'ii[o]tenkidesune｡', '/audio/minna/bai11/Minna_bai11_57.mp3', 'phrase', 'いい[お]天気ですね。', 'THIÊN KHÍ', 'Trời đẹp nhỉ.'),
(11, 'おでかけですか。', 'odekakedesuka｡', '/audio/minna/bai11/Minna_bai11_58.mp3', 'phrase', 'お出かけですか。', 'XUẤT', 'Anh/ chị đi ra ngoài đấy à?'),
(11, 'ちょっと～まで。', 'chotto～made｡', '/audio/minna/bai11/Minna_bai11_59.mp3', 'phrase', NULL, NULL, 'Tôi đi ~ một chút.'),
(11, 'いっていらっしゃい。', 'itteirasshai｡', '/audio/minna/bai11/Minna_bai11_60.mp3', 'phrase', '行っていらっしゃい。', 'HÀNH', 'Anh/chị đi nhé.'),
(11, 'いってまいります', 'ittemairimasu', '/audio/minna/bai11/Minna_bai11_61.mp3', 'phrase', '行ってまいります。', 'HÀNH', 'Tôi đi đây. (nguyên nghĩa: tôi đi rồi sẽ về.)'),
(11, 'それから', 'sorekara', '/audio/minna/bai11/Minna_bai11_62.mp3', 'conjunction', NULL, NULL, 'sau đó, tiếp theo'),
(11, 'オーストラリア', 'oｰsutoraria', '/audio/minna/bai11/oosutoraria.wav', 'noun', NULL, NULL, 'Úc'); 