-- Bài 30
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(30, 'はります', 'harimasu', 'audio/minna/bai30/harimasu.mp3', '', '', '', 'dán, dán lên'),
(30, 'かけます', 'kakemasu', 'audio/minna/bai30/kakemasu.mp3', '', '掛けます', 'QUẢI', 'treo'),
(30, 'かざります', 'kazarimasu', 'audio/minna/bai30/kazarimasu.mp3', '', '飾ります', 'SỨC', 'trang trí'),
(30, 'ならべます', 'narabemasu', 'audio/minna/bai30/narabemasu.mp3', '', '並べます', 'TỊNH', 'xếp thành hàng'),
(30, 'うえます', 'uemasu', 'audio/minna/bai30/uemasu.mp3', '', '植えます', 'THỰC', 'trồng (cây)'),
(30, 'もどします', 'modoshimasu', 'audio/minna/bai30/modoshimasu.mp3', '', '戻します', 'LỆ', 'đưa về, trả về, để lại vị trí ban đầu'),
(30, 'まとめます', 'matomemasu', 'audio/minna/bai30/matomemasu.mp3', '', '', '', 'nhóm lại, tóm tắt'),
(30, 'かたづけます', 'katadukemasu', 'audio/minna/bai30/katadukemasu.mp3', '', '片づけます', 'PHIẾN', 'dọn dẹp, sắp xếp'),
(30, 'しまいます', 'shimaimasu', 'audio/minna/bai30/shimaimasu.mp3', '', '', '', 'cất vào, để vào'),
(30, 'きめます', 'kimemasu', 'audio/minna/bai30/kimemasu.mp3', '', '決めます', 'QUYẾT', 'quyết định'),
(30, 'しらせます', 'shirasemasu', 'audio/minna/bai30/shirasemasu.mp3', '', '知らせます', 'TRI', 'thông báo, báo'),
(30, 'そうだんします', 'soudanshimasu', 'audio/minna/bai30/soudanshimasu.mp3', '', '相談します', 'TƯƠNG ĐÀM', 'trao đổi, bàn bạc, tư vấn'),
(30, 'よしゅうします', 'yoshuushimasu', 'audio/minna/bai30/yosyuushimasu.mp3', '', '予習します', 'DỰ TẬP', 'chuẩn bị bài mới'),
(30, 'ふくしゅうします', 'fukushuushimasu', 'audio/minna/bai30/fukusyuushimasu.mp3', '', '復習します', 'PHỤC TẬP', 'ôn bài cũ'),
(30, 'そのままにします', 'sonomamanishimasu', 'audio/minna/bai30/sonomamanishimasu.mp3', '', '', '', 'để nguyên như thế'),
(30, 'おこさん', 'okosan', 'audio/minna/bai30/okosan.mp3', '', 'お子さん', 'TỬ', 'con (dùng đối với người khác)'),
(30, 'じゅぎょう', 'jugyou', 'audio/minna/bai30/jugyou.mp3', '', '授業', 'THỤ NGHIỆP', 'giờ học'),
(30, 'こうぎ', 'kougi', 'audio/minna/bai30/kougi.mp3', '', '講義', 'GIẢNG NGHĨA', 'bài giảng'),
(30, 'ミーティング', 'mi-tingu', 'audio/minna/bai30/k_miitexingu.mp3', '', '', '', 'cuộc họp'),
(30, 'よてい', 'yotei', 'audio/minna/bai30/yotei.mp3', '', '予定', 'DỰ ĐỊNH', 'kế hoạch, dự định'),
(30, 'おしらせ', 'oshirase', 'audio/minna/bai30/oshirase.mp3', '', 'お知らせ', 'TRI', 'bản thông báo'),
(30, 'あんないしょ', 'annaisho', 'audio/minna/bai30/annaisyo.mp3', '', '案内書', 'ÁN NỘI THƯ', 'sách/tài liệu hướng dẫn'),
(30, 'カレンダー', 'karenda-', 'audio/minna/bai30/k_karendaa.mp3', '', '', '', 'lịch, tờ lịch'),
(30, 'ポスター', 'posuta-', 'audio/minna/bai30/k_posutaa.mp3', '', '', '', 'tờ pa-nô, áp phích, tờ quảng cáo'),
(30, 'ごみばこ', 'gomibako', 'audio/minna/bai30/gomibako.mp3', '', 'ごみ箱', 'TƯƠNG', 'thùng rác'),
(30, 'にんぎょう', 'ningyou', 'audio/minna/bai30/ningyou.mp3', '', '人形', 'NHÂN HÌNH', 'con búp bê, con rối'),
(30, 'かびん', 'kabin', 'audio/minna/bai30/kabin.mp3', '', '花瓶', 'HOA BÌNH', 'lọ hoa'),
(30, 'かがみ', 'kagami', 'audio/minna/bai30/kagami.mp3', '', '鏡', 'KÍNH', 'cái gương'),
(30, 'ひきだし', 'hikidashi', 'audio/minna/bai30/hikidashi.mp3', '', '引き出し', 'DẪN XUẤT', 'ngăn kéo'),
(30, 'げんかん', 'genkan', 'audio/minna/bai30/genkan.mp3', '', '玄関', 'HUYỀN QUAN', 'cửa vào'),
(30, 'ろうか', 'rouka', 'audio/minna/bai30/rouka.mp3', '', '廊下', 'LANG HẠ', 'hành lang'),
(30, 'かべ', 'kabe', 'audio/minna/bai30/kabe.mp3', '', '壁', 'BÍCH', 'bức tường'),
(30, 'いけ', 'ike', 'audio/minna/bai30/ike.mp3', '', '池', 'TRÌ', 'cái ao'),
(30, 'こうばん', 'kouban', 'audio/minna/bai30/kouban.mp3', '', '交番', 'GIAO PHIÊN', 'trạm/bốt cảnh sát'),
(30, 'もとのところ', 'motonotokoro', 'audio/minna/bai30/motonotokoro.mp3', '', '元の所', 'NGUYÊN SỞ', 'địa điểm ban đầu, địa điểm gốc'),
(30, 'まわり', 'mawari', 'audio/minna/bai30/mawari.mp3', '', '周り', 'CHU', 'xung quanh'),
(30, 'まんなか', 'mannaka', 'audio/minna/bai30/mannaka.mp3', '', '真ん中', 'CHÂN TRUNG', 'giữa, trung tâm'),
(30, 'すみ', 'sumi', 'audio/minna/bai30/sumi.mp3', '', '隅', 'NGUNG', 'góc'),
(30, 'まだ', 'mada', 'audio/minna/bai30/mada.mp3', '', '', '', 'chưa'),
(30, '～ほど', '～hodo', 'audio/minna/bai30/hodo.mp3', '', '', '', 'khoảng ~, chừng ~'),
(30, 'よていひょう', 'yoteihyou', 'audio/minna/bai30/yoteihyou.mp3', '', '予定表', 'DỰ ĐỊNH BIỂU', 'lịch, thời khóa biểu'),
(30, 'ごくろうさま', 'gokurousama', 'audio/minna/bai30/gokurousama.mp3', '', 'ご苦労さま。', 'KHỔ LAO', 'Anh/chị đã làm việc vất vả./cám ơn anh/chị. (câu nói dùng để bày tỏ sự cám ơn hoặc thông cảm với sự vất vả khi ai đó làm xong một việc gì)'),
(30, 'きぼう', 'kibou', 'audio/minna/bai30/kibou.mp3', '', '希望', 'HY VỌNG', 'hi vọng, nguyện vọng'),
(30, 'なにかごきぼうがありますか', 'nanikagokibougaarimasuka', 'audio/minna/bai30/nanikagokibougaarimasuka.mp3', '', 'なにかご希望がありますか。', 'HY VỌNG', 'Anh/chị có nguyện vọng gì không?/ anh/chị có yêu cầu gì không?'),
(30, 'ミュージカル', 'myu-jikaru', 'audio/minna/bai30/k_myuujikaru.mp3', '', '', '', 'ca kịch'),
(30, 'それはいいですね。', 'sorehaiidesune', 'audio/minna/bai30/sorehaiidesune.mp3', '', '', '', 'Điều đó được đấy nhỉ./ Hay quá nhỉ'),
(30, 'ブロードウェイ', 'buro-douxei', 'audio/minna/bai30/burodowie.wav', '', '', '', 'Broadway'),
(30, 'まるい', 'marui', 'audio/minna/bai30/marui.wav', '', '丸い', 'HOÀN', 'tròn'),
(30, 'つき', 'tsuki', 'audio/minna/bai30/tsuki.wav', '', '月', 'NGUYỆT', 'mặt trăng, trăng'),
(30, 'ある～', 'aru～', 'audio/minna/bai30/aru.wav', '', '', '', 'có ~, một ~'),
(30, 'ちきゅう', 'chikyuu', 'audio/minna/bai30/chikyuu.wav', '', '地球', 'ĐỊA CẦU', 'trái đất'),
(30, 'うれしい', 'ureshii', 'audio/minna/bai30/ureshii.wav', '', '', '', 'vui'),
(30, 'いや「な」', 'iya「na」', 'audio/minna/bai30/iya.wav', '', '嫌[な]', 'HIỀM', 'chán, ghét, không chấp nhận được'),
(30, 'すると', 'suruto', 'audio/minna/bai30/suruto.wav', '', '', '', 'sau đó, tiếp đó, rồi, khi ~ như vậy thì'),
(30, 'めが　さめます', 'mega　samemasu', 'audio/minna/bai30/megasamemasu.wav', '', '目が覚めます', 'MỤC GIÁC', 'tỉnh giấc, mở mắt');