-- Bài 49
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(49, '[かいしゃに～]つとめます', '［kaishani～］tsutomemasu', 'audio/minna/bai49/tsutomemasu.mp3', '', '[会社に～]勤めます', 'HỘI XÃ CẦN', 'làm việc ở [công ty]'),
(49, 'やすみます', 'yasumimasu', 'audio/minna/bai49/yasumimasu.mp3', '', '休みます', 'HƯU', 'nghỉ'),
(49, '[いすに～]かけます', '［isuni～］kakemasu', 'audio/minna/bai49/kakemasu.mp3', '', '[いすに～]掛けます', 'QUẢI', 'ngồi [ghế]'),
(49, 'すごします', 'sugoshimasu', 'audio/minna/bai49/sugoshimasu.mp3', '', '過ごします', 'QUÁ', 'tiêu thời gian, trải qua'),
(49, '[ぎんこうに～]よります', '［ginkouni～］yorimasu', 'audio/minna/bai49/yorimasu.mp3', '', '[銀行に～]寄ります', 'NGÂN HÀNG KÝ', 'ghé qua [ngân hàng]'),
(49, 'いらっしゃいます', 'irasshaimasu', 'audio/minna/bai49/irassyaimasu.mp3', '', '', '', 'ở, có, đi, đến （tôn kính ngữ của います、いきます và きます）'),
(49, 'めしあがります', 'meshiagarimasu', 'audio/minna/bai49/meshiagarimasu.mp3', '', '召し上がります', 'TRIỆU THƯỢNG', 'ăn, uống (tôn kính ngữ của たべます và のみます)'),
(49, 'おっしゃいます', 'osshaimasu', 'audio/minna/bai49/ossyaimasu.mp3', '', '', '', 'nói (tôn kính ngữ của いいます)'),
(49, 'なさいます', 'nasaimasu', 'audio/minna/bai49/nasaimasu.mp3', '', '', '', 'làm (tôn kính ngữ của します)'),
(49, 'ごらんになります', 'goranninarimasu', 'audio/minna/bai49/goranninarimasu.mp3', '', 'ご覧になります', 'LÃM', 'xem, nhìn (tôn kính ngữ của みます)'),
(49, 'ごぞんじです', 'gozonjidesu', 'audio/minna/bai49/gozonjidesu.mp3', '', 'ご存じです', 'TỒN', 'biết (tôn kính ngữ của しっています)'),
(49, 'あいさつ', 'aisatsu', 'audio/minna/bai49/aisatsu.mp3', '', '', '', 'chào hỏi (～をします：chào hỏi)'),
(49, 'はいざら', 'haizara', 'audio/minna/bai49/haizara.mp3', '', '灰皿', 'HÔI MÃNH', 'cái gạt tàn'),
(49, 'りょかん', 'ryokan', 'audio/minna/bai49/ryokan.mp3', '', '旅館', 'LỮ QUÁN', 'khách sạn kiểu Nhật'),
(49, 'かいじょう', 'kaijou', 'audio/minna/bai49/kaijou.mp3', '', '会場', 'HỘI TRƯỜNG', 'hội trường, địa điểm tổ chức'),
(49, 'バスてい', 'basutei', 'audio/minna/bai49/k_basutei.mp3', '', 'バス停', 'ĐÌNH', 'bến xe buýt, điểm lên xuống xe buýt'),
(49, 'ぼうえき', 'boueki', 'audio/minna/bai49/boueki.mp3', '', '貿易', 'MẬU DỊCH', 'thương mại quốc tế, mậu dịch'),
(49, '～さま', '～sama', 'audio/minna/bai49/sama.mp3', '', '～様', 'DẠNG', 'ngài ~, ông ~, bà ~ (tôn kính ngữ của ～さん)'),
(49, 'かえりに', 'kaerini', 'audio/minna/bai49/kaerini.mp3', '', '帰りに', 'QUY', 'trên đường về'),
(49, 'たまに', 'tamani', 'audio/minna/bai49/tamani.mp3', '', '', '', 'thỉnh thoảng (tần suất nhỏ hơn ときどき)'),
(49, 'ちっとも', 'chittomo', 'audio/minna/bai49/chittomo.mp3', '', '', '', 'chẳng ~ tí nào, không hề'),
(49, 'えんりょなく', 'enryonaku', 'audio/minna/bai49/enryonaku.mp3', '', '遠慮なく', 'VIỄN LỰ', 'không giữ ý, không làm khách, đừng ngại ngùng'),
(49, '―ねん―くみ', '-nen-kumi', 'audio/minna/bai49/nenkumi.mp3', '', '―年―組', 'NIÊN TỔ', 'lớp -, năm thứ -'),
(49, 'では', 'deha', 'audio/minna/bai49/deha.mp3', '', '', '', 'thế thì, vậy thì (thể lịch sự củaじゃ)'),
(49, '「ねつ」 だします', '「netsu」　dashimasu', 'audio/minna/bai49/dashimasu.mp3', '', '[熱を～]出します', 'XUẤT NHIỆT', 'bị [sốt]'),
(49, 'よろしくおつたえください', 'yoroshikuotsutaekudasai', 'audio/minna/bai49/yoroshikuotsutaekudasai.mp3', '', 'よろしくお伝えください。', 'TRUYỀN', 'Cho tôi gởi lời hỏi thăm./ hãy nhắn lại với ~.'),
(49, 'しつれいいたします', 'shitsureiitashimasu', 'audio/minna/bai49/shitsureiitashimasu.mp3', '', '失礼いたします。', 'THẤT LỄ', 'Xin phép anh/chị (khiêm nhường ngữ của しつれいします)'),
(49, 'ひまわりしょうがっこう', 'himawarishougakkou', 'audio/minna/bai49/himawarishogakkou.wav', '', 'ひまわり小学校', 'TIỂU HỌC HIỆU', 'tên một trường tiểu học (giả tưởng)'),
(49, 'こうし', 'koushi', 'audio/minna/bai49/koushi.wav', '', '講師', 'GIẢNG SƯ', 'giảng viên, giáo viên'),
(49, 'おおくの～', 'ookuno～', 'audio/minna/bai49/ookuno.wav', '', '多くの～', 'ĐA', 'nhiều ~'),
(49, 'さくひん', 'sakuhin', 'audio/minna/bai49/sakuhin.wav', '', '作品', 'TÁC PHẨM', 'tác phẩm'),
(49, 'じゅしょうします', 'jushoushimasu', 'audio/minna/bai49/jushoushimasu.wav', '', '受賞します', 'THỤ THƯỞNG', 'nhận giải thưởng, được giải thưởng'),
(49, 'せかいてきに', 'sekaitekini', 'audio/minna/bai49/sekaitekini.wav', '', '世界的に', 'THẾ GIỚI', 'tầm cỡ thế giới, mang tính thế giới'),
(49, 'さっか', 'sakka', 'audio/minna/bai49/sakka.wav', '', '作家', 'TÁC GIA', 'nhà văn'),
(49, '～でいらっしゃいます', '～deirasshaimasu', 'audio/minna/bai49/deirassaimasu.wav', '', '', '', 'là ~(tôn kính ngữ của です)'),
(49, 'ちょうなん', 'chounan', 'audio/minna/bai49/chounan.wav', '', '長男', 'TRƯỞNG NAM', 'trưởng nam'),
(49, 'しょうがい', 'shougai', 'audio/minna/bai49/shougai.wav', '', '障害', 'CHƯỚNG HẠI', 'khuyết tật, tàn tật'),
(49, 'おもちです', 'omochidesu', 'audio/minna/bai49/omochidesu.wav', '', 'お持ちです', 'TRÌ', 'có (cách nói tôn kính ngữ của もっています)'),
(49, 'さっきょく', 'sakkyoku', 'audio/minna/bai49/sakkyoku.wav', '', '作曲', 'TÁC KHÚC', 'sáng tác nhạc'),
(49, 'かつどう', 'katsudou', 'audio/minna/bai49/katsudou.wav', '', '活動', 'HOẠT ĐỘNG', 'hoạt động'),
(49, 'それでは', 'soredeha', 'audio/minna/bai49/soredeha.wav', '', '', '', 'bây giờ thì, đến đây'),
(49, 'おおえけんざぶろう', 'ooekenzaburou', 'audio/minna/bai49/ooekenzaburou.wav', '', '大江健三郎', 'ĐẠI GIANG KIỆN TAM LANG', 'một nhà văn người Nhật (1935-)'),
(49, 'とうきょうだいがく', 'toukyoudaigaku', 'audio/minna/bai49/toukyoudaigaku.wav', '', '東京大学', 'ĐÔNG KINH ĐẠI HỌC', 'đại học Tokyo'),
(49, 'ノーベルぶんがくしょう', 'no-berubungakushou', 'audio/minna/bai49/noberubungakushou.wav', '', 'ノーベル文学賞', 'VĂN HỌC THƯỞNG', 'giải thưởng Nobel văn học');