-- Bài 23
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(23, '[せんせいに～]ききます', '[senseini～]kikimasu', 'audio/minna/bai23/kikimasu.mp3', '', '[先生に～]聞きます', 'TIÊN SINH VĂN', 'hỏi [giáo viên]'),
(23, 'まわします', 'mawashimasu', 'audio/minna/bai23/mawashimasu.mp3', '', '回します', 'HỒI', 'vặn (núm)'),
(23, 'ひきます', 'hikimasu', 'audio/minna/bai23/hikimasu.mp3', '', '引きます', 'DẪN', 'chơi (nhạc cụ)'),
(23, 'かえます', 'kaemasu', 'audio/minna/bai23/kaemasu.mp3', '', '変えます', 'BIẾN', 'đổi'),
(23, '[ドアに～]さわります', '[doani～]sawarimasu', 'audio/minna/bai23/sawarimasu.mp3', '', '触ります', 'XÚC', 'sờ, chạm vào [cửa]'),
(23, '[おつりが～]でます', '[otsuriga～]demasu', 'audio/minna/bai23/demasu.mp3', '', '[お釣りが～]出ます', 'ĐIẾU XUẤT', 'ra, đi ra [tiền thừa ~]'),
(23, '[とけいが～] うごきます', '[tokeiga～] ugokimasu', 'audio/minna/bai23/ugokimasu.mp3', '', '[時計が～]動きます', 'THỜI KẾ ĐỘNG', 'chuyển động, chạy [đồng hồ ~]'),
(23, '[みちを～]あるきます', '[michiwo～]arukimasu', 'audio/minna/bai23/arukimasu.mp3', '', '[道を～]歩きます', 'ĐẠO BỘ', 'đi bộ [trên đường]'),
(23, '[はしを～]わたります', '[hashiwo～]watarimasu', 'audio/minna/bai23/watarimasu.mp3', '', '[橋を～]渡ります', 'KIỀU ĐỘ', 'qua, đi qua [cầu]'),
(23, '[くるまに～]きを　つけます', '[kurumani～]kiwo tsukemasu', 'audio/minna/bai23/kiwotsukemasu.mp3', '', '[車に～]気をつけます', 'XA KHÍ', 'chú ý, cẩn thận [với ô-tô]'),
(23, 'ひっこしします', 'hikkoshishimasu', 'audio/minna/bai23/hikkoshishimasu.mp3', '', '引っ越しします', 'DẪN VIỆT', 'chuyển nhà'),
(23, 'でんきや', 'denkiya', 'audio/minna/bai23/denkiya.mp3', '', '電気屋', 'ĐIỆN KHÍ ỐC', 'cửa hàng đồ điện'),
(23, '～や', '～ya', 'audio/minna/bai23/ya.mp3', '', '～屋', 'ỐC', 'cửa hàng ~'),
(23, 'サイズ', 'saizu', 'audio/minna/bai23/k_saizu.mp3', '', '', '', 'cỡ, kích thước'),
(23, 'おと', 'oto', 'audio/minna/bai23/oto.mp3', '', '音', 'ÂM', 'âm thanh'),
(23, 'きかい', 'kikai', 'audio/minna/bai23/kikai.mp3', '', '機械', 'CƠ GIỚI', 'máy, máy móc'),
(23, 'つまみ', 'tsumami', 'audio/minna/bai23/tsumami.mp3', '', '', '', 'núm vặn'),
(23, 'こしょう', 'koshou', 'audio/minna/bai23/kosyou.mp3', '', '故障', 'CỐ CHƯỚNG', 'hỏng (~します：bị hỏng)'),
(23, 'みち', 'michi', 'audio/minna/bai23/michi.mp3', '', '道', 'ĐẠO', 'đường'),
(23, 'こうさてん', 'kousaten', 'audio/minna/bai23/kousaten.mp3', '', '交差点', 'GIAO SAI ĐIỂM', 'ngã tư'),
(23, 'しんごう', 'shingou', 'audio/minna/bai23/shingou.mp3', '', '信号', 'TÍN HIỆU', 'đèn tín hiệu'),
(23, 'かど', 'kado', 'audio/minna/bai23/kado.mp3', '', '角', 'GIÁC', 'góc'),
(23, 'はし', 'hashi', 'audio/minna/bai23/hashi.mp3', '', '橋', 'KIỀU', 'đũa'),
(23, 'ちゅうしゃじょう', 'chuushajou', 'audio/minna/bai23/chuusyajou.mp3', '', '駐車場', 'TRÚ XA TRƯỜNG', 'bãi đỗ xe'),
(23, '―め', '～me', 'audio/minna/bai23/me.mp3', '', '―目', 'MỤC', 'thứ - , số - (biểu thị thứ tự)'),
(23, '[お]しょうがつ', '[o]shougatsu', 'audio/minna/bai23/osyougatsu.mp3', '', '[お]正月', 'CHÍNH NGUYỆT', 'Tết (Dương lịch)'),
(23, 'ごちそうさま[でした]。', 'gochisousama[deshita]｡', 'audio/minna/bai23/gochisousamadeshita.mp3', '', '', '', 'Xin cám ơn anh/chị đã đãi tôi bữa cơm.'),
(23, 'たてもの', 'tatemono', 'audio/minna/bai23/tatemono.mp3', '', '建物', 'KIẾN VẬT', 'tòa nhà'),
(23, 'がいこくじんとうろくしょう', 'gaikokujintourokushou', 'audio/minna/bai23/gaikokujintourokusyou.mp3', '', '外国人登録証', 'NGOẠI QUỐC NHÂN', 'thẻ đăng ký người nước ngoài,'),
(23, 'しょうとくたいし', 'shoutokutaishi', 'audio/minna/bai23/syoutokutaishi.wav', '', '聖徳太子', 'THÁNH ĐỨC THÁI TỬ', 'Thái tử Shotoku (574 – 622)'),
(23, 'ほうりゅうじ', 'houryuuji', 'audio/minna/bai23/horyuji.wav', '', '法隆寺', 'PHÁP LONG TỰ', 'Chùa Horyu-ji'),
(23, 'げんきちゃ', 'genkicha', 'audio/minna/bai23/genkicha.wav', '', '元気茶', 'NGUYÊN KHÍ TRÀ', 'tên một loại trà (giả tưởng)'),
(23, 'ほんだえき', 'hondaeki', 'audio/minna/bai23/hondaeki.wav', '', '本田駅', 'BẢN ĐIỀN DỊCH', 'tên một nhà ga (giả tưởng)'),
(23, 'としょかんまえ', 'toshokanmae', 'audio/minna/bai23/toshokanmae.wav', '', '図書館前', 'ĐỒ THƯ QUÁN TIỀN', 'tên một bến xe buýt (giả tưởng');