-- Bài 9
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(9, 'わかります', 'wakarimasu', '/audio/minna/bai09/wakarimasu.mp3', 'verb', NULL, NULL, 'hiểu, nắm được'),
(9, 'あります', 'arimasu', '/audio/minna/bai09/arimasu.mp3', 'verb', NULL, NULL, 'có (sở hữu)'),
(9, 'すき[な]', 'suki[na]', '/audio/minna/bai09/suki.mp3', 'adj-na', '好き[な]', 'HIẾU/HẢO', 'thích'),
(9, 'きらい[な]', 'kirai[na]', '/audio/minna/bai09/kirai.mp3', 'adj-na', '嫌い[な]', 'HIỀM', 'ghét, không thích'),
(9, 'じょうず[な]', 'jouzu[na]', '/audio/minna/bai09/jouzu.mp3', 'adj-na', '上手[な]', 'THƯỢNG THỦ', 'giỏi, khéo'),
(9, 'へた[な]', 'heta[na]', '/audio/minna/bai09/heta.mp3', 'adj-na', '下手[な]', 'HẠ THỦ', 'kém'),
(9, 'りょうり', 'ryouri', '/audio/minna/bai09/ryouri.mp3', 'noun', '料理', 'LIỆU LÝ', 'món ăn, việc nấu ăn'),
(9, 'のみもの', 'nomimono', '/audio/minna/bai09/nomimono.mp3', 'noun', '飲み物', 'ẨM VẬT', 'đồ uống'),
(9, 'スポーツ', 'supoｰtsu', '/audio/minna/bai09/k_supootsu.mp3', 'noun', NULL, NULL, 'thể thao (～をします：chơi thể thao)'),
(9, 'やきゅう', 'yakyuu', '/audio/minna/bai09/yakyuu.mp3', 'noun', '野球', 'DÃ CẦU', 'bóng chày (～をします：chơi bóng chày)'),
(9, 'ダンス', 'dansu', '/audio/minna/bai09/k_dansu.mp3', 'noun', NULL, NULL, 'nhảy, khiêu vũ(～をします：nhảy, khiêu vũ)'),
(9, 'おんがく', 'ongaku', '/audio/minna/bai09/ongaku.mp3', 'noun', '音楽', 'ÂM NHẠC/LẠC', 'âm nhạc'),
(9, 'うた', 'uta', '/audio/minna/bai09/uta.mp3', 'noun', '歌', 'CA', 'bài hát'),
(9, 'クラシック', 'kurashikku', '/audio/minna/bai09/k_kurashikku.mp3', 'noun', NULL, NULL, 'nhạc cổ điển'),
(9, 'ジャズ', 'jazu', '/audio/minna/bai09/k_jazu.mp3', 'noun', NULL, NULL, 'nhạc jazz'),
(9, 'コンサート', 'konsaｰto', '/audio/minna/bai09/k_konsaato.mp3', 'noun', NULL, NULL, 'buổi hòa nhạc'),
(9, 'カラオケ', 'karaoke', '/audio/minna/bai09/k_karaoke.mp3', 'noun', NULL, NULL, 'karaoke'),
(9, 'かぶき', 'kabuki', '/audio/minna/bai09/kabuki.mp3', 'noun', '歌舞伎', 'CA VŨ KỸ', 'Kabuki (một loại ca kịch truyền thống của Nhật)'),
(9, 'え', 'e', '/audio/minna/bai09/e.mp3', 'noun', '絵', 'HỘI', 'tranh, hội họa'),
(9, 'じ', 'ji', '/audio/minna/bai09/ji.mp3', 'noun', '字', 'TỰ', 'chữ'),
(9, 'かんじ', 'kanji', '/audio/minna/bai09/kanji.mp3', 'noun', '漢字', 'HÁN TỰ', 'chữ hán'),
(9, 'ひらがな', 'hiragana', '/audio/minna/bai09/hiragana.mp3', 'noun', NULL, NULL, 'chữ Hiragana'),
(9, 'かたかな', 'katakana', '/audio/minna/bai09/katakana.mp3', 'noun', NULL, NULL, 'Chữ Katakana'),
(9, 'ローマじ', 'roｰmaji', '/audio/minna/bai09/k_romaji.mp3', 'noun', 'ローマ字', 'TỰ', 'chữ La Mã'),
(9, 'こまかいおかね', 'komakaiokane', '/audio/minna/bai09/komakaiokane.mp3', 'noun', '細かいお金', 'TẾ KIM', 'tiền lẻ'),
(9, 'チケット', 'chiketto', '/audio/minna/bai09/k_chiketto.mp3', 'noun', NULL, NULL, 'vé (xem hòa nhạc, xem phim)'),
(9, 'じかん', 'jikan', '/audio/minna/bai09/jikan.mp3', 'noun', '時間', 'THÌ/THỜI GIAN', 'thời gian'),
(9, 'ようじ', 'youji', '/audio/minna/bai09/youji.mp3', 'noun', '用事', 'DỤNG SỰ', 'việc bận, công chuyện'),
(9, 'やくそく', 'yakusoku', '/audio/minna/bai09/yakusoku.mp3', 'noun', '約束', 'ƯỚC THÚC', 'cuộc hẹn, lời hứa'),
(9, 'ごしゅじん', 'goshujin', '/audio/minna/bai09/gosyujin.mp3', 'noun', 'ご主人', 'CHỦ NHÂN', 'chồng (dùng khi nói về chồng người khác)'),
(9, 'おっと/しゅじん', 'otto/shujin', '/audio/minna/bai09/otto(syujin).mp3', 'noun', '夫 /主人', 'PHU CHỦ NHÂN', 'chồng (dùng khi nói về chồng mình)'),
(9, 'おくさん', 'okusan', '/audio/minna/bai09/okusan.mp3', 'noun', '奥さん', 'ÁO', 'vợ (dùng khi nói về vợ người khác)'),
(9, 'つま/かない', 'tsuma/kanai', '/audio/minna/bai09/tsuma(kanai).mp3', 'noun', '妻/家内', 'THÊ GIA NỘI', 'vợ (dùng khi nói về vợ mình)'),
(9, 'こども', 'kodomo', '/audio/minna/bai09/kodomo.mp3', 'noun', '子ども', 'TỬ', 'con cái'),
(9, 'よく', 'yoku', '/audio/minna/bai09/yoku.mp3', 'adverb', NULL, NULL, 'tốt, rõ (chỉ mức độ)'),
(9, 'だいたい', 'daitai', '/audio/minna/bai09/daitai.mp3', 'adverb', NULL, NULL, 'đại khái, đại thể'),
(9, 'たくさん', 'takusan', '/audio/minna/bai09/takusan.mp3', 'adverb', NULL, NULL, 'nhiều'),
(9, 'すこし', 'sukoshi', '/audio/minna/bai09/sukoshi.mp3', 'adverb', '少し', 'THIẾU, THIỂU', 'ít, một ít'),
(9, 'ぜんぜん', 'zenzen', '/audio/minna/bai09/zenzen.mp3', 'adverb', '全然', 'TOÀN NHIÊN', 'hoàn toàn ~ không'),
(9, 'はやく', 'hayaku', '/audio/minna/bai09/hayaku.mp3', 'adverb', '早く, 速く', 'TẢO、TỐC', 'sớm, nhanh'),
(9, '～から', '～kara', '/audio/minna/bai09/kara.mp3', 'particle', NULL, NULL, '~ từ'),
(9, 'どうして', 'doushite', '/audio/minna/bai09/doushite.mp3', 'adverb', NULL, NULL, 'tại sao'),
(9, 'ざんねんです[ね]。', 'zannendesu[ne]｡', '/audio/minna/bai09/zannendesune.mp3', 'phrase', '残念です[ね]。', 'TÀN NIỆM', 'Thật đáng tiếc nhỉ./ buồn nhỉ.'),
(9, 'すみません。', 'sumimasen｡', '/audio/minna/bai09/sumimasen.mp3', 'phrase', NULL, NULL, 'Xin lỗi.'),
(9, 'もしもし', 'moshimoshi', '/audio/minna/bai09/moshimoshi.mp3', 'phrase', NULL, NULL, 'a-lô'),
(9, 'ああ', 'aa', '/audio/minna/bai09/aa.mp3', 'phrase', NULL, NULL, 'a (cách nói khi đã gặp được đúng người trên điện thoại)'),
(9, 'いっしょにいかがですか。', 'isshoniikagadesuka｡', '/audio/minna/bai09/isshoniikagadesuka.mp3', 'phrase', NULL, NULL, 'Anh/chị cùng ~ (làm cái gì đó) với chúng tôi được không?'),
(9, '[～は]ちょっと…。', '[～ha]chotto～｡', '/audio/minna/bai09/chotto.mp3', 'phrase', NULL, NULL, '[~ thì] có lẽ không được rồi.'),
(9, 'だめですか。', 'damedesuka｡', '/audio/minna/bai09/damedesuka.mp3', 'phrase', NULL, NULL, 'Không được à?'),
(9, 'またこんどおねがいします', 'matakondoonegaishimasu', '/audio/minna/bai09/matakondoonegaishimasu.mp3', 'phrase', 'また今度お願いします', 'KIM ĐỘ NGUYỆN', 'Hẹn Anh/Chị lần sau vậy.'),
(9, 'おざわせいじ', 'ozawaseiji', '/audio/minna/bai09/ozawaseiji.wav', 'noun', '小沢征爾', 'TIỂU TRẠCH CHINH NHĨ', 'Ozawa Seiji (1935 ~ )'); 