INSERT INTO vocabulary (word, romaji, audio, type, kanji, kanji_reading, meaning, lesson) VALUES
('おきます', 'okimasu', '/audio/minna/bai04/okimasu.mp3', 'verb', '起きます', 'KHỞI', 'dậy, thức dậy', 4),
('ねます', 'nemasu', '/audio/minna/bai04/nemasu.mp3', 'verb', '寝ます', 'TẨM', 'ngủ, đi ngủ', 4),
('はたらきます', 'hatarakimasu', '/audio/minna/bai04/hatarakimasu.mp3', 'verb', '働きます', 'ĐỘNG', 'làm việc', 4),
('やすみます', 'yasumimasu', '/audio/minna/bai04/yasumimasu.mp3', 'verb', '休みます', 'HƯU', 'nghỉ, nghỉ ngơi', 4),
('べんきょうします', 'benkyoushimasu', '/audio/minna/bai04/benkyoushimasu.mp3', 'verb', '勉強します', 'MIỄN CƯỜNG', 'học', 4),
('おわります', 'owarimasu', '/audio/minna/bai04/owarimasu.mp3', 'verb', '終わります', 'CHUNG', 'hết, kết thúc, xong', 4),
('デパート', 'depaato', '/audio/minna/bai04/k_depaato.mp3', 'noun', NULL, NULL, 'bách hóa', 4),
('ぎんこう', 'ginkou', '/audio/minna/bai04/ginkou.mp3', 'noun', '銀行', 'NGÂN HÀNH', 'ngân hàng', 4),
('ゆうびんきょく', 'yuubinkyoku', '/audio/minna/bai04/yuubinkyoku.mp3', 'noun', '郵便局', 'BƯU TIỆN CỤC', 'bưu điện', 4),
('としょかん', 'toshokan', '/audio/minna/bai04/tosyokan.mp3', 'noun', '図書館', 'ĐỒ THƯ QUÁN', 'thư viện', 4),
('びじゅつかん', 'bijutsukan', '/audio/minna/bai04/bijutsukan.mp3', 'noun', '美術館', 'MỸ THUẬT QUÁN', 'bảo tàng mỹ thuật', 4),
('いま', 'ima', '/audio/minna/bai04/ima.mp3', 'adverb', '今', 'KIM', 'bây giờ', 4),
('―じ', '～ji', '/audio/minna/bai04/ji.mp3', 'suffix', '－時', 'THỜI', '-giờ', 4),
('―ふん（－ぷん）', '～fun(-pun)', '/audio/minna/bai04/fun(pun).mp3', 'suffix', '―分', 'PHÂN', '- phút', 4),
('はん', 'han', '/audio/minna/bai04/han.mp3', 'suffix', '半', 'BÁN', 'rưỡi, nửa', 4),
('なんじ', 'nanji', '/audio/minna/bai04/nanji.mp3', 'pronoun', '何時', 'HÀ THỜI', 'mấy giờ', 4),
('なんぷん', 'nanpun', '/audio/minna/bai04/nanpun.mp3', 'pronoun', '何分', 'HÀ PHÂN', 'mấy phút', 4),
('ごぜん', 'gozen', '/audio/minna/bai04/gozen.mp3', 'noun', '午前', 'NGỌ TIỀN', 'sáng, trước 12 giờ trưa', 4),
('ごご', 'gogo', '/audio/minna/bai04/gogo.mp3', 'noun', '午後', 'NGỌ HẬU', 'chiều, sau 12 giờ trưa', 4),
('あさ', 'asa', '/audio/minna/bai04/asa.mp3', 'noun', '朝', 'TRIỀU', 'buổi sáng, sáng', 4),
('ひる', 'hiru', '/audio/minna/bai04/hiru.mp3', 'noun', '昼', 'TRÚ', 'buổi trưa, trưa', 4),
('ばん（よる）', 'ban(yoru)', '/audio/minna/bai04/yoru.mp3', 'noun', '晩(夜)', 'VÃN(DẠ)', 'buổi tối, tối', 4),
('おととい', 'ototoi', '/audio/minna/bai04/ototoi.mp3', 'noun', NULL, NULL, 'hôm kia', 4),
('きのう', 'kinou', '/audio/minna/bai04/kinou.mp3', 'noun', NULL, NULL, 'hôm qua', 4),
('きょう', 'kyou', '/audio/minna/bai04/kyou.mp3', 'noun', NULL, NULL, 'hôm nay', 4),
('あした', 'ashita', '/audio/minna/bai04/ashita.mp3', 'noun', NULL, NULL, 'ngày mai', 4),
('あさって', 'asatte', '/audio/minna/bai04/asatte.mp3', 'noun', NULL, NULL, 'ngày kia', 4),
('けさ', 'kesa', '/audio/minna/bai04/kesa.mp3', 'noun', NULL, NULL, 'sáng nay', 4),
('こんばん', 'konban', '/audio/minna/bai04/konban.mp3', 'noun', '今晩', 'KIM VÃN', 'tối nay', 4),
('やすみ', 'yasumi', '/audio/minna/bai04/yasumi.mp3', 'noun', '休み', 'HƯU', 'nghỉ, nghỉ phép, ngày nghỉ', 4),
('ひるやすみ', 'hiruyasumi', '/audio/minna/bai04/hiruyasumi.mp3', 'noun', '昼休み', 'TRÚ HƯU', 'nghỉ trưa', 4),
('まいあさ', 'maiasa', '/audio/minna/bai04/maiasa.mp3', 'adverb', '毎朝', 'MỖI TRIỀU', 'hàng sáng, mỗi sáng', 4),
('まいばん', 'maiban', '/audio/minna/bai04/maiban.mp3', 'adverb', '毎晩', 'MỖI VÃN', 'hàng tối, mỗi tối', 4),
('まいにち', 'mainichi', '/audio/minna/bai04/mainichi.mp3', 'adverb', '毎日', 'MỖI NHẬT', 'hàng ngày, mỗi ngày', 4),
('げつようび', 'getsuyoubi', '/audio/minna/bai04/getsuyoubi.mp3', 'noun', '月曜日', 'NGUYỆT DIỆU NHẬT', 'thứ hai', 4),
('かようび', 'kayoubi', '/audio/minna/bai04/kayoubi.mp3', 'noun', '火曜日', 'HỎA DIỆU NHẬT', 'thứ ba', 4),
('すいようび', 'suiyoubi', '/audio/minna/bai04/suiyoubi.mp3', 'noun', '水曜日', 'THỦY DIỆU NHẬT', 'thứ tư', 4),
('もくようび', 'mokuyoubi', '/audio/minna/bai04/mokuyoubi.mp3', 'noun', '木曜日', 'MỘC DIỆU NHẬT', 'thứ năm', 4),
('きんようび', 'kinyoubi', '/audio/minna/bai04/kinyoubi.mp3', 'noun', '金曜日', 'KIM DIỆU NHẬT', 'thứ sáu', 4),
('どようび', 'doyoubi', '/audio/minna/bai04/doyoubi.mp3', 'noun', '土曜日', 'THỔ DIỆU NHẬT', 'thứ bảy', 4),
('にちようび', 'nichiyoubi', '/audio/minna/bai04/nichiyoubi.mp3', 'noun', '日曜日', 'NHẬT DIỆU NHẬT', 'chủ nhật', 4),
('なんようび', 'nanyoubi', '/audio/minna/bai04/nanyoubi.mp3', 'pronoun', '何曜日', 'HÀ DIỆU NHẬT', 'thứ mấy', 4),
('ばんごう', 'bangou', '/audio/minna/bai04/bangou.mp3', 'noun', '番号', 'PHIÊN HIỆU', 'số (số điện thoại, số phòng)', 4),
('なんばん', 'nanban', '/audio/minna/bai04/nanban.mp3', 'pronoun', '何番', 'HÀ PHIÊN', 'số bao nhiêu, số mấy', 4),
('～から', '～kara', '/audio/minna/bai04/kara.mp3', 'particle', NULL, NULL, '~ từ', 4),
('～まで', '～made', '/audio/minna/bai04/made.mp3', 'particle', NULL, NULL, '~ đến', 4),
('～と', '～to', '/audio/minna/bai04/to.mp3', 'particle', NULL, NULL, '~ và (dùng để nối hai danh từ)', 4),
('そちら', 'sochira', '/audio/minna/bai04/sochira.mp3', 'pronoun', NULL, NULL, 'phía đó, đằng đó, chỗ đó, đó', 4),
('たいへんですね', 'taihendesune', '/audio/minna/bai04/taihendesune.mp3', 'phrase', '大変ですね', 'ĐẠI BIẾN', 'Anh/chị vất vả quá.', 4),
('えーと', 'eeto', '/audio/minna/bai04/eeto.mp3', 'interjection', NULL, NULL, 'ừ, à', 4),
('104', '104', '/audio/minna/bai04/104.wav', 'number', NULL, NULL, 'Số điện thoại của dịch vụ hướng dẫn số điện thoại', 4),
('おねがいします', 'onegaishimasu', '/audio/minna/bai04/onegaishimasu.mp3', 'phrase', 'お願いします', 'NGUYỆN', 'Nhờ anh/chị. Phiền anh/chị. Xin vui lòng giúp đỡ', 4),
('かしこまりました', 'kashikomarimashita', '/audio/minna/bai04/kashikomarimashita.mp3', 'phrase', NULL, NULL, 'Tôi hiểu rồi ạ./ vâng, được rồi ạ.', 4),
('おといあわせのばんごう', 'otoiawasenobangou', '/audio/minna/bai04/otoiawasenobangou.mp3', 'phrase', 'お問い合わせの番号', 'VẤN HỢP PHIÊN HIỆU', 'Số điện thoại mà ông/ bà muốn hỏi', 4),
('[どうも]ありがとうございました。', '[doumo]arigatougozaimashita', '/audio/minna/bai04/doumoarigatougozaimashita.wav', 'phrase', NULL, NULL, 'Xin cám ơn ông/bà', 4),
('ニューヨーク', 'nyuuyooku', '/audio/minna/bai04/nyuyoku.wav', 'noun', NULL, NULL, 'New York', 4),
('ペキン', 'pekin', '/audio/minna/bai04/pekin.wav', 'noun', NULL, NULL, 'Bắc Kinh', 4),
('ロンドン', 'rondon', '/audio/minna/bai04/rondon.wav', 'noun', NULL, NULL, 'Luân Đôn', 4),
('バンコク', 'bankoku', '/audio/minna/bai04/bankoku.wav', 'noun', NULL, NULL, 'Băng Cốc', 4),
('ロサンゼルス', 'rosanzerusu', '/audio/minna/bai04/rosanzerusu.wav', 'noun', NULL, NULL, 'Los Angeles', 4),
('やまとびじゅつかん', 'yamatobijutsukan', '/audio/minna/bai04/yamatobijutsukan.wav', 'noun', 'やまと美術館', 'MỸ THUẬT QUÁN', 'tên một bảo tàng Mỹ thuật (giả tưởng)', 4),
('おおさかデパート', 'oosakadepaato', '/audio/minna/bai04/osakadepato.wav', 'noun', '大阪デパート', 'ĐẠI PHẢN', 'tên một bách hóa (giả tưởng)', 4),
('みどりとしょかん', 'midoritoshokan', '/audio/minna/bai04/midoritoshokan.wav', 'noun', 'みどり図書館', 'ĐỒ THƯ QUÁN', 'tên một thư viện (giả tưởng)', 4),
('アップルぎんこう', 'appuruginkou', '/audio/minna/bai04/appuruginko.wav', 'noun', 'アップル銀行', 'NGÂN HÀNH', 'tên một ngân hàng (giả tưởng)', 4);
