-- Bài 8
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(8, 'ハンサム[な]', 'hansamu[na]', '/audio/minna/bai08/k_hansamu.mp3', 'adj-na', NULL, NULL, 'đẹp trai'),
(8, 'きれい[な]', 'kirei[na]', '/audio/minna/bai08/kirei.mp3', 'adj-na', NULL, NULL, 'đẹp, sạch'),
(8, 'しずか[な]', 'shizuka[na]', '/audio/minna/bai08/shizuka.mp3', 'adj-na', '静か[な]', 'TĨNH', 'yên tĩnh'),
(8, 'にぎやか[な]', 'nigiyaka[na]', '/audio/minna/bai08/nigiyaka.mp3', 'adj-na', NULL, NULL, 'náo nhiệt'),
(8, 'ゆうめい[な]', 'yuumei[na]', '/audio/minna/bai08/yuumei.mp3', 'adj-na', '有名[な]', 'HỮU DANH', 'nổi tiếng'),
(8, 'しんせつ[な]', 'shinsetsu[na]', '/audio/minna/bai08/shinsetsu.mp3', 'adj-na', '親切[な]', 'THÂN THIẾT', 'tốt bụng, thân thiện'),
(8, 'げんき[な]', 'genki[na]', '/audio/minna/bai08/genki.mp3', 'adj-na', '元気[な]', 'NGUYÊN KHÍ', 'khỏe'),
(8, 'ひま[な]', 'hima[na]', '/audio/minna/bai08/hima.mp3', 'adj-na', '暇[な]', 'HẠ', 'rảnh rỗi'),
(8, 'べんり[な]', 'benri[na]', '/audio/minna/bai08/benri.mp3', 'adj-na', '便利[な]', 'TIỆN LỢI', 'tiện lợi'),
(8, 'すてき[な]', 'suteki[na]', '/audio/minna/bai08/suteki.mp3', 'adj-na', NULL, NULL, 'đẹp, hay'),
(8, 'おおきい', 'ookii', '/audio/minna/bai08/ookii.mp3', 'adj-i', '大きい', 'ĐẠI', 'lớn, to'),
(8, 'ちいさい', 'chiisai', '/audio/minna/bai08/chiisai.mp3', 'adj-i', '小さい', 'TIỂU', 'bé, nhỏ'),
(8, 'あたらしい', 'atarashii', '/audio/minna/bai08/atarashii.mp3', 'adj-i', '新しい', 'TÂN', 'mới'),
(8, 'ふるい', 'furui', '/audio/minna/bai08/furui.mp3', 'adj-i', '古い', 'CỔ', 'cũ'),
(8, 'いい（よい）', 'ii(yoi)', '/audio/minna/bai08/ii.mp3', 'adj-i', NULL, NULL, 'tốt'),
(8, 'わるい', 'warui', '/audio/minna/bai08/warui.mp3', 'adj-i', '悪い', 'ÁC', 'xấu'),
(8, 'あつい', 'atsui', '/audio/minna/bai08/atsui.mp3', 'adj-i', '暑い, 熱い', 'THỬ, NHIỆT', 'nóng'),
(8, 'さむい', 'samui', '/audio/minna/bai08/samui.mp3', 'adj-i', '寒い', 'HÀN', 'lạnh, rét (dùng cho thời tiết)'),
(8, 'つめたい', 'tsumetai', '/audio/minna/bai08/tsumetai.mp3', 'adj-i', '冷たい', 'LÃNH', 'lạnh, buốt (dùng cho cảm giác)'),
(8, 'むずかしい', 'muzukashii', '/audio/minna/bai08/muzukashii.mp3', 'adj-i', '難しい', 'NAN', 'khó'),
(8, 'やさしい', 'yasashii', '/audio/minna/bai08/yasashii.mp3', 'adj-i', '易しい', 'DỊ', 'dễ'),
(8, 'たかい', 'takai', '/audio/minna/bai08/takai.mp3', 'adj-i', '高い', 'CAO', 'đắt, cao'),
(8, 'やすい', 'yasui', '/audio/minna/bai08/yasui.mp3', 'adj-i', '安い', 'AN', 'rẻ'),
(8, 'ひくい', 'hikui', '/audio/minna/bai08/hikui.mp3', 'adj-i', '低い', 'ĐÊ', 'thấp'),
(8, 'おもしろい', 'omoshiroi', '/audio/minna/bai08/omoshiroi.mp3', 'adj-i', NULL, NULL, 'thú vị, hay'),
(8, 'おいしい', 'oishii', '/audio/minna/bai08/oishii.mp3', 'adj-i', NULL, NULL, 'ngon'),
(8, 'いそがしい', 'isogashii', '/audio/minna/bai08/isogashii.mp3', 'adj-i', '忙しい', 'MANG', 'bận'),
(8, 'たのしい', 'tanoshii', '/audio/minna/bai08/tanoshii.mp3', 'adj-i', '楽しい', 'LẠC, NHẠC', 'vui'),
(8, 'しろい', 'shiroi', '/audio/minna/bai08/shiroi.mp3', 'adj-i', '白い', 'BẠCH', 'trắng'),
(8, 'くろい', 'kuroi', '/audio/minna/bai08/kuroi.mp3', 'adj-i', '黒い', 'HẮC', 'đen'),
(8, 'あかい', 'akai', '/audio/minna/bai08/akai.mp3', 'adj-i', '赤い', 'XÍCH', 'đỏ'),
(8, 'あおい', 'aoi', '/audio/minna/bai08/aoi.mp3', 'adj-i', '青い', 'THANH', 'xanh da trời'),
(8, 'さくら', 'sakura', '/audio/minna/bai08/sakura.mp3', 'noun', '桜', 'ANH', 'anh đào (hoa, cây)'),
(8, 'やま', 'yama', '/audio/minna/bai08/yama.mp3', 'noun', '山', 'SƠN, SAN', 'núi'),
(8, 'まち', 'machi', '/audio/minna/bai08/machi.mp3', 'noun', '町', 'ĐINH', 'thị trấn, thị xã, thành phố'),
(8, 'たべもの', 'tabemono', '/audio/minna/bai08/tabemono.mp3', 'noun', '食べ物', 'THỰC VẬT', 'đồ ăn'),
(8, 'くるま', 'kuruma', '/audio/minna/bai08/kuruma.mp3', 'noun', '車', 'XA', 'xe ô tô'),
(8, 'ところ', 'tokoro', '/audio/minna/bai08/tokoro.mp3', 'noun', '所', 'SỞ', 'nơi, chỗ'),
(8, 'りょう', 'ryou', '/audio/minna/bai08/ryo.mp3', 'noun', '寮', 'LIÊU', 'kí túc xá'),
(8, 'べんきょう', 'benkyou', '/audio/minna/bai08/benkyou.mp3', 'noun', '勉強', 'MIỄN CƯỜNG', 'học'),
(8, 'せいかつ', 'seikatsu', '/audio/minna/bai08/seikatsu.mp3', 'noun', '生活', 'SINH HOẠT', 'cuộc sống, sinh hoạt'),
(8, '[お]しごと', '[o]shigoto', '/audio/minna/bai08/shigoto.mp3', 'noun', '[お]仕事', 'SĨ SỰ', 'công việc (～をします：làm việc)'),
(8, 'どう', 'dou', '/audio/minna/bai08/dou.mp3', 'adverb', NULL, NULL, 'thế nào'),
(8, 'どんな～', 'donna～', '/audio/minna/bai08/donna.mp3', 'adverb', NULL, NULL, '~ như thế nào'),
(8, 'どれ', 'dore', '/audio/minna/bai08/dore.mp3', 'pronoun', NULL, NULL, 'cái nào'),
(8, 'とても', 'totemo', '/audio/minna/bai08/totemo.mp3', 'adverb', NULL, NULL, 'rất, lắm'),
(8, 'あまり', 'amari', '/audio/minna/bai08/amari.mp3', 'adverb', NULL, NULL, 'không ~ lắm'),
(8, 'そして', 'soshite', '/audio/minna/bai08/soshite.mp3', 'conjunction', NULL, NULL, 'và, thêm nữa (dùng để nối 2 câu)'),
(8, '～が、～', '～ga､～', '/audio/minna/bai08/ga.mp3', 'conjunction', NULL, NULL, '~, nhưng ~'),
(8, 'おげんきですか。', 'ogenkidesuka｡', '/audio/minna/bai08/ogenkidesuka.mp3', 'phrase', 'お元気ですか。', 'NGUYÊN KHÍ', 'Anh/chị có khỏe không?'),
(8, 'そうですね。', 'soudesune｡', '/audio/minna/bai08/soudesune.mp3', 'phrase', NULL, NULL, 'Thế à. Như vậy nhỉ'),
(8, 'にほんのせいかつに なれましたか', 'nihonnoseikatsuni naremashitaka', '/audio/minna/bai08/nihonnoseikatsuninaremashitaka.mp3', 'phrase', NULL, NULL, 'Anh/Chị đã quen với cuộc sống ở Nhật chưa?'),
(8, '[～、]もういっぱいいかがですか。', '[～､]mouippaiikagadesuka｡', '/audio/minna/bai08/mouippaiikagadesuka.mp3', 'phrase', NULL, NULL, 'Anh/ chị dùng thêm một chén [~] nữa được không ạ?'),
(8, 'いいえ、けっこうです。', 'iie､kekkoudesu｡', '/audio/minna/bai08/iiekekkoudesu.mp3', 'phrase', NULL, NULL, 'Không, đủ rồi ạ.'),
(8, 'もう～です[ね]。', 'mou～desu[ne]｡', '/audio/minna/bai08/moudesune.wav', 'phrase', NULL, NULL, 'Đã ~ rồi nhỉ./ Đã ~ rồi, đúng không ạ?'),
(8, 'そろそろしつれいします。', 'sorosoroshitsureishimasu｡', '/audio/minna/bai08/sorosoroshitsureishimasu.mp3', 'phrase', NULL, NULL, 'Sắp đến lúc tôi phải xin phép rồi.'),
(8, 'また　いらっしゃってください。', 'mata irasshattekudasai｡', '/audio/minna/bai08/matairasshattekudasai.wav', 'phrase', NULL, NULL, 'Lần sau anh/ chị lại đến chơi nhé.'),
(8, 'ふじさん', 'fujisan', '/audio/minna/bai08/fujisan.wav', 'noun', '富士山', 'PHÚ SĨ SƠN/SAN', 'Núi Phú Sĩ (ngọn núi cao nhất Nhật Bản)'),
(8, 'びわこ', 'biwako', '/audio/minna/bai08/biwako.wav', 'noun', '琵琶湖', 'TỲ BÀ HỒ', 'Hồ Biwa'),
(8, 'シャンハイ', 'shanhai', '/audio/minna/bai08/shanhai.wav', 'noun', '上海', 'THƯỢNG HẢI', 'Thượng Hải'),
(8, 'しちにんのさむらい', 'shichininnosamurai', '/audio/minna/bai08/shichininnosamurai.wav', 'noun', '七人の侍', 'THẤT NHÂN THỊ', 'bảy chàng võ sĩ Samurai'),
(8, 'きんかくじ', 'kinkakuji', '/audio/minna/bai08/kinkakuji.wav', 'noun', '金閣寺', 'KIM CÁC TỰ', 'Chùa Kinkaku-ji (chùa vàng)'); 