-- Bài 45
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(45, 'あやまります', 'ayamarimasu', 'audio/minna/bai45/ayamarimasu.mp3', '', '謝ります', 'TẠ', 'xin lỗi, tạ lỗi'),
(45, '[じこに～] あいます', '［jikoni～］　aimasu', 'audio/minna/bai45/aimasu.mp3', '', '[事故に～]遭います', 'SỰ CỐ TAO', 'gặp [tai nạn]'),
(45, 'しんじます', 'shinjimasu', 'audio/minna/bai45/shinjimasu.mp3', '', '信じます', 'TÍN', 'tin, tin tưởng'),
(45, 'よういします', 'youishimasu', 'audio/minna/bai45/youishimasu.mp3', '', '用意します', 'DỤNG Ý', 'chuẩn bị'),
(45, 'キャンセルします', 'kyanserushimasu', 'audio/minna/bai45/k_kyanserushimasu.mp3', '', '', '', 'hủy bỏ, hủy'),
(45, 'うまくいきます', 'umakuikimasu', 'audio/minna/bai45/umakuikimasu.mp3', '', '', '', 'tốt, thuận lợi'),
(45, 'ほしょうしょ', 'hoshousho', 'audio/minna/bai45/hoshousyo.mp3', '', '保証書', 'BẢO CHỨNG THƯ', 'giấy bảo hành'),
(45, 'りょうしゅうしょ', 'ryoushuusho', 'audio/minna/bai45/ryousyuusyo.mp3', '', '領収書', 'LÃNH THÂU THƯ', 'hóa đơn'),
(45, 'おくりもの', 'okurimono', 'audio/minna/bai45/okurimono.mp3', '', '贈り物', 'TẶNG VẬT', 'quà tặng (～をします)'),
(45, 'まちがいでんわ', 'machigaidenwa', 'audio/minna/bai45/machigaidenwa.mp3', '', 'まちがい電話', 'ĐIỆN THOẠI', 'điện thoại nhầm'),
(45, 'キャンプ', 'kyanpu', 'audio/minna/bai45/k_kyanpu.mp3', '', '', '', 'trại'),
(45, 'かかり', 'kakari', 'audio/minna/bai45/kakari.mp3', '', '', '', 'nhân viên, người phụ trách'),
(45, 'ちゅうし', 'chuushi', 'audio/minna/bai45/chuushi.mp3', '', '中止', 'TRUNG CHỈ', 'dừng, đình chỉ'),
(45, 'てん', 'ten', 'audio/minna/bai45/ten.mp3', '', '点', 'ĐIỂM', 'điểm'),
(45, 'レバー', 'reba-', 'audio/minna/bai45/k_rebaa.mp3', '', '', '', 'tay bẻ, tay số, cần gạt'),
(45, '[－えん]さつ', '［－en］satsu', 'audio/minna/bai45/ensatsu.mp3', '', '[－円]札', 'VIÊN TRÁT', 'tờ tiền giấy [-yên]'),
(45, 'ちゃんと', 'chanto', 'audio/minna/bai45/chanto.mp3', '', '', '', 'đúng, hẳn hoi'),
(45, 'きゅうに', 'kyuuni', 'audio/minna/bai45/kyuni.mp3', '', '急に', 'CẤP', 'gấp'),
(45, 'たのしみにしています', 'tanoshiminishiteimasu', 'audio/minna/bai45/tanoshiminishiteimasu.mp3', '', '楽しみにしています', 'NHẠC/LẠC', 'mong đợi, lấy làm vui'),
(45, 'いじょうです。', 'ijoudesu', 'audio/minna/bai45/ijoudesu.mp3', '', '以上です。', '', 'Xin hết.'),
(45, 'かかりいん', 'kakariin', 'audio/minna/bai45/kakariin.mp3', '', '係員', 'HỆ VIÊN', 'nhân viên'),
(45, 'コース', 'ko-su', 'audio/minna/bai45/k_koosu.mp3', '', '', '', 'đường chạy (ma ra tông)'),
(45, 'スタート', 'suta-to', 'audio/minna/bai45/k_sutaato.mp3', '', '', '', 'xuất phát'),
(45, '―い', '-i', 'audio/minna/bai45/i.mp3', '', '－位', 'VỊ', 'thứ ―, vị trí thứ －, giải ―'),
(45, 'ゆうしょうします', 'yuushoushimasu', 'audio/minna/bai45/yuusyoushimasu.mp3', '', '優勝します', 'ƯU THẮNG', 'vô địch, đoạt giải nhất'),
(45, 'なやみ', 'nayami', 'audio/minna/bai45/nayami.wav', '', '悩み', 'NÃO', '(điều/sự) lo nghĩ, trăn trở, phiền muộn'),
(45, 'めざまし「どけい」', 'mezamashi「dokei」', 'audio/minna/bai45/mezamashi.wav', '', '目覚まし[時計]', 'MỤC GIÁC THỜI KẾ', 'đồng hồ báo thức'),
(45, 'ねむります', 'nemurimasu', 'audio/minna/bai45/nemurimasu.wav', '', '眠ります', 'MIÊN', 'ngủ'),
(45, 'めがさめます', 'megasamemasu', 'audio/minna/bai45/megasamemasu.wav', '', '目が覚めます', 'MỤC GIÁC', 'tỉnh giấc'),
(45, 'だいがくせい', 'daigakusei', 'audio/minna/bai45/daigakusei.wav', '', '大学生', 'ĐẠI HỌC SINH', 'sinh viên đại học'),
(45, 'かいとう', 'kaitou', 'audio/minna/bai45/kaitou.wav', '', '回答', 'HỒI ĐÁP', 'câu trả lời, lời giải'),
(45, 'なります', 'narimasu', 'audio/minna/bai45/narimasu.wav', '', '鳴ります', 'MINH', 'reo, kêu'),
(45, 'セットします', 'settoshimasu', 'audio/minna/bai45/settoshimasu.wav', '', '', '', 'cài, đặt'),
(45, 'それでも', 'soredemo', 'audio/minna/bai45/soredemo.wav', '', '', '', 'tuy thế, mặc dù thế');