-- Bài 34
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(34, '[はを～]みがきます', '［hawo～］migakimasu', 'audio/minna/bai34/migakimasu.mp3', '', '[歯を～]磨きます', 'XỈ MA', 'mài, đánh [răng]'),
(34, 'くみたてます', 'kumitatemasu', 'audio/minna/bai34/kumitatemasu.mp3', '', '組み立てます', 'TỔ LẬP', 'lắp, lắp ráp, lắp đặt'),
(34, 'おります', 'orimasu', 'audio/minna/bai34/orimasu.mp3', '', '折ります', 'TRIẾT', 'gấp, gập, bẻ gãy'),
(34, '[わすれものに～] きがつきます', '［wasuremononi～］　kigatsukimasu', 'audio/minna/bai34/kigatsukimasu.mp3', '', '[忘れ物に～]気がつきます', 'VONG VẬT KHÍ', 'nhận thấy, phát hiện [đồ bỏ quên]'),
(34, '[しょうゆを～] つけます', '［shouyuwo～］　tsukemasu', 'audio/minna/bai34/tsukemasu.mp3', '', '', '', 'chấm [xì-dầu]'),
(34, '[かぎが～]みつかります', '［kagiga～］mitsukarimasu', 'audio/minna/bai34/mitsukarimasu.mp3', '', '[かぎが～]見つかります', 'KIẾN', 'được tìm thấy [chìa khóa ~]'),
(34, '[ネクタイを～]します', '［nekutaiwo～］shimasu', 'audio/minna/bai34/shimasu.mp3', '', '', '', 'đeo, thắt [cà-vạt]'),
(34, 'しつもんします', 'shitsumonshimasu', 'audio/minna/bai34/shitsumonshimasu.mp3', '', '質問します', 'CHẤT VẤN', 'hỏi'),
(34, 'ほそい', 'hosoi', 'audio/minna/bai34/hosoi.mp3', '', '細い', 'TẾ', 'gầy, hẹp, thon'),
(34, 'ふとい', 'futoi', 'audio/minna/bai34/futoi.mp3', '', '太い', 'THÁI', 'béo, to'),
(34, 'ぼんおどり', 'bonodori', 'audio/minna/bai34/bonodori.mp3', '', '盆踊り', 'BỒN DŨNG', 'múa trong hội Bon'),
(34, 'スポーツクラブ', 'supo-tsukurabu', 'audio/minna/bai34/k_supootsukurabu.mp3', '', '', '', 'câu lạc bộ thể thao, câu lạc bộ thể hình'),
(34, 'かぐ', 'kagu', 'audio/minna/bai34/kagu.mp3', '', '家具', 'GIA CỤ', 'gia cụ, đồ dùng nội thất'),
(34, 'キー', 'ki-', 'audio/minna/bai34/ki-.wav', '', '', '', 'chìa khóa'),
(34, 'シートベルト', 'shi-toberuto', 'audio/minna/bai34/k_shiitoberuto.mp3', '', '', '', 'dây an toàn (ở ghế ngồi)'),
(34, 'せつめいしょ', 'setsumeisho', 'audio/minna/bai34/setsumeisyo.mp3', '', '説明書', 'THUYẾT MINH THƯ', 'quyển hướng dẫn'),
(34, 'ず', 'zu', 'audio/minna/bai34/zu.mp3', '', '図', 'ĐỒ', 'sơ đồ, hình vẽ'),
(34, 'せん', 'sen', 'audio/minna/bai34/sen.mp3', '', '線', 'TUYẾN', 'đường'),
(34, 'やじるし', 'yajirushi', 'audio/minna/bai34/yajirushi.mp3', '', '矢印', 'THỈ ẤN', 'dấu mũi tên'),
(34, 'くろ', 'kuro', 'audio/minna/bai34/kuro.mp3', '', '黒', 'HẮC', 'màu đen'),
(34, 'しろ', 'shiro', 'audio/minna/bai34/shiro.mp3', '', '���', 'BẠCH', 'màu trắng'),
(34, 'あか', 'aka', 'audio/minna/bai34/aka.mp3', '', '赤', 'XÍCH', 'màu đỏ'),
(34, 'あお', 'ao', 'audio/minna/bai34/ao.mp3', '', '青', 'THANH', 'màu xanh da trời'),
(34, 'こん', 'kon', 'audio/minna/bai34/kon.mp3', '', '紺', 'CÁM', 'màu xanh lam'),
(34, 'きいろ', 'kiiro', 'audio/minna/bai34/kiiro.mp3', '', '黄色', 'HOÀNG SẮC', 'màu vàng'),
(34, 'しょうゆ', 'shouyu', 'audio/minna/bai34/syouyu.mp3', '', '', '', 'xì dầu'),
(34, 'ソース', 'so-su', 'audio/minna/bai34/k_soosu.mp3', '', '', '', 'nước chấm, nước xốt'),
(34, '～か～', '～ka～', 'audio/minna/bai34/ka.mp3', '', '', '', '~hay ~'),
(34, 'ゆうべ', 'yuube', 'audio/minna/bai34/yuube.mp3', '', '', '', 'tối qua, đêm qua'),
(34, 'さっき', 'sakki', 'audio/minna/bai34/sakki.mp3', '', '', '', 'vừa rồi, vừa lúc nãy'),
(34, 'さどう', 'sadou', 'audio/minna/bai34/sadou.mp3', '', '茶道', 'TRÀ ĐẠO', 'trà đạo'),
(34, 'おちゃをたてます', 'ochawotatemasu', 'audio/minna/bai34/ochawotatemasu.mp3', '', 'お茶をたてます', 'TRÀ', 'pha trà, khuấy trà'),
(34, 'さきに', 'sakini', 'audio/minna/bai34/sakini.mp3', '', '先に', 'TIÊN', 'trước'),
(34, 'のせます', 'nosemasu', 'audio/minna/bai34/nosemasu.mp3', '', '載せます', 'TẢI', 'để lên, đặt lên'),
(34, 'これでいいですか。', 'koredeiidesuka', 'audio/minna/bai34/koredeiidesuka.mp3', '', '', '', 'Thế này có được không?/thế này đã được chưa?'),
(34, 'にがい', 'nigai', 'audio/minna/bai34/nigai.mp3', '', '苦い', 'KHỔ', 'đắng'),
(34, 'おやこどんぶり', 'oyakodonburi', 'audio/minna/bai34/oyakodonburi.wav', '', '親子どんぶり', 'THÂN TỬ', 'món oyako-don (món cơm bát tô có thịt trứng ở trên)'),
(34, 'ざいりょう', 'zairyou', 'audio/minna/bai34/zairyou.wav', '', '材料', 'TÀI LIỆU', 'nguyên liệu'),
(34, '―ぶん-', '-bun－', 'audio/minna/bai34/bun.wav', '', '―分', 'PHÂN', '-suất, – người'),
(34, 'とりにく', 'toriniku', 'audio/minna/bai34/toriniku.wav', '', '鳥肉', 'ĐIỂU NHỤC', 'thịt gà'),
(34, '―グラム', '-guramu', 'audio/minna/bai34/guramu.wav', '', '', '', '- gam'),
(34, '―こ-', '-ko－', 'audio/minna/bai34/ko.wav', '', '―個', 'CÁ', '-cái, -quả, - miếng (dùng để đếm vật nhỏ)'),
(34, 'たまねぎ', 'tamanegi', 'audio/minna/bai34/tamanegi.wav', '', '', '', 'hành củ'),
(34, 'よんぶんのいち', 'yonbunnoichi', 'audio/minna/bai34/yonbunnoichi.wav', '', '4分の１　（１/４）', 'PHÂN', 'một phần tư'),
(34, 'ちょうみりょう', 'choumiryou', 'audio/minna/bai34/choumiryou.wav', '', '調味料', 'ĐIỀU VỊ LIỆU', 'gia vị'),
(34, 'なべ', 'nabe', 'audio/minna/bai34/nabe.wav', '', '', '', 'cái chảo, cái nồi'),
(34, 'ひ', 'hi', 'audio/minna/bai34/hi.wav', '', '火', 'HỎA', 'lửa'),
(34, 'ひにかけます', 'hinikakemasu', 'audio/minna/bai34/hinikakemasu.wav', '', '火にかけます', 'HỎA', 'cho qua lửa, đun'),
(34, 'にます', 'nimasu', 'audio/minna/bai34/nimasu.wav', '', '煮ます', 'CHỬ', 'nấu'),
(34, 'にえます', 'niemasu', 'audio/minna/bai34/niemasu.wav', '', '煮えます', 'CHỬ', 'chín, được nấu'),
(34, 'どんぶり', 'donburi', 'audio/minna/bai34/donburi.wav', '', '', '', 'cái bát');