-- Bài 12
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(12, 'かんたん「な」', 'kantan｢na｣', '/audio/minna/bai12/kantan.mp3', 'adj-na', '簡単「な」', 'GIẢN ĐƠN', 'đơn giản, dễ'),
(12, 'ちかい', 'chikai', '/audio/minna/bai12/chikai.mp3', 'adj-i', '近い', 'CẬN', 'gần'),
(12, 'とおい', 'tooi', '/audio/minna/bai12/tooi.mp3', 'adj-i', '遠い', 'VIỄN', 'xa'),
(12, 'はやい', 'hayai', '/audio/minna/bai12/hayai.mp3', 'adj-i', '速い, 早い', 'TỐC、TẢO', 'nhanh, sớm'),
(12, 'おそい', 'osoi', '/audio/minna/bai12/osoi.mp3', 'adj-i', '遅い', 'TRÌ', 'chậm, muộn'),
(12, '[ひとが～] おおい', '[hitoga～] ooi', '/audio/minna/bai12/ooi.mp3', 'adj-i', '[人が～]多い', 'NHÂN ĐA', 'nhiều [người]'),
(12, '[ひとが～]すくない', '[hitoga～]sukunai', '/audio/minna/bai12/sukunai.mp3', 'adj-i', '[人が～]少ない', 'NHÂN, THIỂU/THIẾU', 'ít [người]'),
(12, 'あたたかい', 'atatakai', '/audio/minna/bai12/atatakai.mp3', 'adj-i', '温かい,暖かい', 'ÔN、NOÃN', 'ấm'),
(12, 'すずしい', 'suzushii', '/audio/minna/bai12/suzushii.mp3', 'adj-i', '涼しい', 'LƯƠNG', 'mát'),
(12, 'あまい', 'amai', '/audio/minna/bai12/amai.mp3', 'adj-i', '甘い', 'CAM', 'ngọt'),
(12, 'からい', 'karai', '/audio/minna/bai12/karai.mp3', 'adj-i', '辛い', 'TÂN', 'cay'),
(12, 'おもい', 'omoi', '/audio/minna/bai12/omoi.mp3', 'adj-i', '重い', 'TRỌNG', 'nặng'),
(12, 'かるい', 'karui', '/audio/minna/bai12/karui.mp3', 'adj-i', '軽い', 'KHINH', 'nhẹ'),
(12, '[コーヒーが～]いい', '[koｰhiｰga～]ii', '/audio/minna/bai12/ii.mp3', 'adj-i', NULL, NULL, 'thích, chọn, dùng [cafe]'),
(12, 'きせつ', 'kisetsu', '/audio/minna/bai12/kisetsu.mp3', 'noun', '季節', 'QUÝ TIẾT', 'mùa'),
(12, 'はる', 'haru', '/audio/minna/bai12/haru.mp3', 'noun', '春', 'XUÂN', 'mùa xuân'),
(12, 'なつ', 'natsu', '/audio/minna/bai12/natsu.mp3', 'noun', '夏', 'HẠ', 'mùa hè'),
(12, 'あき', 'aki', '/audio/minna/bai12/aki.mp3', 'noun', '秋', 'THU', 'mùa thu'),
(12, 'ふゆ', 'fuyu', '/audio/minna/bai12/fuyu.mp3', 'noun', '冬', 'ĐÔNG', 'mùa đông'),
(12, 'てんき', 'tenki', '/audio/minna/bai12/tenki.mp3', 'noun', '天気', 'THIÊN KHÍ', 'thời tiết'),
(12, 'あめ', 'ame', '/audio/minna/bai12/ame.mp3', 'noun', '雨', 'VŨ', 'mưa'),
(12, 'ゆき', 'yuki', '/audio/minna/bai12/yuki.mp3', 'noun', '雪', 'TUYẾT', 'tuyết'),
(12, 'くもり', 'kumori', '/audio/minna/bai12/kumori.mp3', 'noun', '曇り', 'ĐÀM', 'có mây'),
(12, 'ホテル', 'hoteru', '/audio/minna/bai12/k_hoteru.mp3', 'noun', NULL, NULL, 'khách sạn'),
(12, 'くうこう', 'kuukou', '/audio/minna/bai12/kuukou.mp3', 'noun', '空港', 'KHÔNG CẢNG', 'sân bay'),
(12, 'うみ', 'umi', '/audio/minna/bai12/umi.mp3', 'noun', '海', 'HẢI', 'biển, đại dương'),
(12, 'せかい', 'sekai', '/audio/minna/bai12/sekai.mp3', 'noun', '世界', 'THẾ GIỚI', 'thế giới'),
(12, 'パーティー', 'paｰtiｰ', '/audio/minna/bai12/k_paati.mp3', 'noun', NULL, NULL, 'tiệc (~をします：tổ chức tiệc)'),
(12, '「お」まつり', '｢o｣matsuri', '/audio/minna/bai12/omatsuri.mp3', 'noun', '「お」祭り', 'TẾ', 'lễ hội'),
(12, 'しけん', 'shiken', '/audio/minna/bai12/shiken.mp3', 'noun', '試験', 'THÍ NGHIỆM', 'kỳ thi, bài thi'),
(12, 'すきやき', 'sukiyaki', '/audio/minna/bai12/sukiyaki.mp3', 'noun', 'すき焼き', 'THIÊU', 'Sukiyaki (món thịt bò nấu rau)'),
(12, 'さしみ', 'sashimi', '/audio/minna/bai12/sashimi.mp3', 'noun', '刺身', 'THÍCH THÂN', 'Sashimi (món gỏi cá sống)'),
(12, '「お」すし', '｢o｣sushi', '/audio/minna/bai12/osushi.mp3', 'noun', NULL, NULL, 'Sushi'),
(12, 'てんぷら', 'tenpura', '/audio/minna/bai12/tenpura.mp3', 'noun', NULL, NULL, 'Tempura (món hải sản và rau chiên tẩm bột)'),
(12, 'いけばな', 'ikebana', '/audio/minna/bai12/ikebana.mp3', 'noun', '生け花', 'SINH HOA', 'Nghệ thuật cắm hoa (～をします：cắm hoa)'),
(12, 'もみじ', 'momiji', '/audio/minna/bai12/momiji.mp3', 'noun', '紅葉', 'HỒNG DIỆP', 'lá đỏ'),
(12, 'どちら', 'dochira', '/audio/minna/bai12/dochira.mp3', 'question', NULL, NULL, 'phía nào, đằng nào, chỗ nào, đâu'),
(12, 'どちらも', 'dochiramo', '/audio/minna/bai12/dochiramo.mp3', 'adverb', NULL, NULL, 'cả hai'),
(12, 'ずっと', 'zutto', '/audio/minna/bai12/zutto.mp3', 'adverb', NULL, NULL, '(hơn) hẳn'),
(12, 'はじめて', 'hajimete', '/audio/minna/bai12/hajimete.mp3', 'adverb', '初めて', 'SƠ', 'lần đầu tiên'),
(12, 'ただいま。', 'tadaima｡', '/audio/minna/bai12/tadaima.mp3', 'phrase', NULL, NULL, 'Tôi đã về đây. (dùng nói khi về đến nhà)'),
(12, 'おかえりなさい。', 'okaerinasai｡', '/audio/minna/bai12/okaerinasai.mp3', 'phrase', 'お帰りなさい。', 'QUY', 'Anh/Chị đã về đấy à.'),
(12, 'すごいですね。', 'sugoidesune｡', '/audio/minna/bai12/sugoidesune.mp3', 'phrase', NULL, NULL, 'Ghê quá nhỉ./ hay quá nhỉ.'),
(12, 'でも', 'demo', '/audio/minna/bai12/demo.mp3', 'conjunction', NULL, NULL, 'Nhưng'),
(12, 'つかれました。', 'tsukaremashita｡', '/audio/minna/bai12/tsukaremashita.wav', 'phrase', '疲れました。', 'BÌ', 'Tôi mệt rồi'),
(12, 'ぎおんまつり', 'gionmatsuri', '/audio/minna/bai12/gionmatsuri.wav', 'noun', '祗園祭', 'KỲ VIÊN TẾ', 'Lễ hội Gi-ôn (lễ hội nổi tiếng nhất ở Kyoto)'),
(12, 'ホンコン', 'honkon', '/audio/minna/bai12/honkon.wav', 'noun', '香港', 'HƯƠNG CẢNG', 'Hồng Kông'),
(12, 'シンガポール', 'shingapoｰru', '/audio/minna/bai12/shingaporu.wav', 'noun', NULL, NULL, 'Singapore'),
(12, 'まいにちや', 'mainichiya', '/audio/minna/bai12/mainichiya.wav', 'noun', '毎日屋', 'MỖI NHẬT ỐC', 'tên một siêu thị (giả tưởng)'),
(12, 'ＡＣＢストア', 'ACBsutoa', '/audio/minna/bai12/acbstore.wav', 'noun', NULL, NULL, 'tên một siêu thị (giả tưởng)'),
(12, 'ジャパン', 'japan', '/audio/minna/bai12/japan.wav', 'noun', NULL, NULL, 'tên một siêu thị (giả tưởng)'); 