-- Bài 20
INSERT INTO vocabulary (lesson, word, romaji, audio, type, kanji, kanji_reading, meaning) VALUES
(20, '[ビザが～]いります', '[bizaga～]irimasu', 'audio/minna/bai20/irimasu.mp3', '', '[ビザが～]要ります', 'YẾU', 'cần [thị thực (visa)]'),
(20, 'しらべます', 'shirabemasu', 'audio/minna/bai20/shirabemasu.mp3', '', '調べます', 'ĐIỀU', 'tìm hiểu, điều tra, xem'),
(20, 'なおします', 'naoshimasu', 'audio/minna/bai20/naoshimasu.mp3', '', '直します', 'TRỰC', 'sửa, chữa'),
(20, 'しゅうりします', 'shuurishimasu', 'audio/minna/bai20/shuurishimasu.mp3', '', '修理します', 'TU LÝ', 'sửa chữa, tu sửa'),
(20, 'でんわします', 'denwashimasu', 'audio/minna/bai20/denwashimasu.mp3', '', '電話します', 'ĐIỆN THOẠI', 'gọi điện thoại'),
(20, 'ぼく', 'boku', 'audio/minna/bai20/boku.mp3', '', '僕', 'BỘC', 'tớ'),
(20, 'きみ', 'kimi', 'audio/minna/bai20/kimi.mp3', '', '君', 'QUÂN', 'cậu, bạn'),
(20, '～くん', '～kun', 'audio/minna/bai20/kun.mp3', '', '～君', 'QUÂN', '(hậu tố thêm vào sau tên của em trai)'),
(20, 'うん', 'un', 'audio/minna/bai20/un.mp3', '', '', '', 'ừ (cách nói thân mật của 「はい」)'),
(20, 'ううん', 'uun', 'audio/minna/bai20/uun.mp3', '', '', '', 'không (cách nói thân mật của 「いいえ」)'),
(20, 'サラリーマン', 'sarariｰman', 'audio/minna/bai20/k_sarariiman.mp3', '', '', '', 'người làm việc cho các công ty'),
(20, 'ことば', 'kotoba', 'audio/minna/bai20/kotoba.mp3', '', '', '', 'từ, tiếng'),
(20, 'ぶっか', 'bukka', 'audio/minna/bai20/bukka.mp3', '', '物価', 'VẬT GIÁ', 'giá cả, mức giá, vật giá'),
(20, 'きもの', 'kimono', 'audio/minna/bai20/kimono.mp3', '', '着物', 'TRƯỚC VẬT', 'Kimono (trang phục truyền thống của Nhật Bản)'),
(20, 'ビザ', 'biza', 'audio/minna/bai20/k_biza.mp3', '', '', '', 'thị thực, Visa'),
(20, 'はじめ', 'hajime', 'audio/minna/bai20/hajime.mp3', '', '始め', 'THỦY', 'ban đầu, đầu tiên'),
(20, 'おわり', 'owari', 'audio/minna/bai20/owari.mp3', '', '終わり', 'CHUNG', 'kết thúc'),
(20, 'こっち', 'kotchi', 'audio/minna/bai20/kocchi.mp3', '', '', '', 'phía này, chỗ này (cách nói thân mật của 「こちら」)'),
(20, 'そっち', 'sotchi', 'audio/minna/bai20/socchi.mp3', '', '', '', 'phía đó, chỗ đó (cách nói thân mật của 「そちら」)'),
(20, 'あっち', 'atchi', 'audio/minna/bai20/acchi.mp3', '', '', '', 'phía kia, chỗ kia (cách nói thân mật của 「あちら」)'),
(20, 'どっち', 'dotchi', 'audio/minna/bai20/docchi.mp3', '', '', '', 'cái nào, phía nào, đâu (cách nói thân mật của 「どちら」)'),
(20, 'このあいだ', 'konoaida', 'audio/minna/bai20/konoaida.mp3', '', 'この間', 'GIAN', 'vừa rồi, hôm nọ'),
(20, 'みんなで', 'minnade', 'audio/minna/bai20/minnade.mp3', '', '', '', 'mọi người cùng'),
(20, '～けど', '～kedo', 'audio/minna/bai20/kedo.mp3', '', '', '', 'nhưng (cách nói thân mật của 「が」)'),
(20, 'くにへかえるの？', 'kunihekaeruno?', 'audio/minna/bai20/kunihekaeruno.mp3', '', '国へ帰るの？', 'QUỐC QUY', 'Anh/chị có về nước không?'),
(20, 'どうするの？', 'dousuruno?', 'audio/minna/bai20/dousuruno.mp3', '', '', '', 'Anh/ chị tính sao? Anh/chị sẽ làm gì?'),
(20, 'どうしようかな。', 'doushiyoukana｡', 'audio/minna/bai20/doushiyoukana.mp3', '', '', '', 'Tính sao đây nhỉ?/để tôi xem.'),
(20, 'よかったら', 'yokattara', 'audio/minna/bai20/yokattara.mp3', '', '', '', 'Nếu anh/chị thích thì'),
(20, 'いろいろ', 'iroiro', 'audio/minna/bai20/iroiro.mp3', '', '', '', 'nhiều thứ');