INSERT INTO vocabulary (word, romaji, audio, type, kanji, kanji_reading, meaning, lesson) VALUES
('ここ', 'koko', '/audio/minna/bai03/koko.mp3', NULL, NULL, NULL, 'chỗ này, đây', 3),
('そこ', 'soko', '/audio/minna/bai03/soko.mp3', NULL, NULL, NULL, 'chỗ đó, đó', 3),
('あそこ', 'asoko', '/audio/minna/bai03/asoko.mp3', NULL, NULL, NULL, 'chỗ kia, kia', 3),
('どこ', 'doko', '/audio/minna/bai03/doko.mp3', NULL, NULL, NULL, 'chỗ nào, đâu', 3),
('こちら', 'kochira', '/audio/minna/bai03/kochira.mp3', NULL, NULL, NULL, 'phía này, đằng này, chỗ này, đây', 3),
('そちら', 'sochira', '/audio/minna/bai03/sochira.mp3', NULL, NULL, NULL, 'phía đó, đằng đó, chỗ đó, đó', 3),
('あちら', 'achira', '/audio/minna/bai03/achira.mp3', NULL, NULL, NULL, 'phía kia, đằng kia, chỗ kia, kia', 3),
('どちら', 'dochira', '/audio/minna/bai03/dochira.mp3', NULL, NULL, NULL, 'phía nào, đằng nào, chỗ nào, đâu', 3),
('きょうしつ', 'kyoushitsu', '/audio/minna/bai03/kyoushitsu.mp3', NULL, '教室', 'GIÁO THẤT', 'lớp học, phòng học', 3),
('しょくどう', 'shokudou', '/audio/minna/bai03/syokudou.mp3', NULL, '食堂', 'THỰC ĐƯỜNG', 'nhà ăn', 3),
('じむしょ', 'jimusho', '/audio/minna/bai03/jimusyo.mp3', NULL, '事務所', 'SỰ VỤ SỞ', 'văn phòng', 3),
('かいぎしつ', 'kaigishitsu', '/audio/minna/bai03/kaigishitsu.mp3', NULL, '会議室', 'HỘI NGHỊ THẤT', 'phòng họp', 3),
('うけつけ', 'uketsuke', '/audio/minna/bai03/uketsuke.mp3', NULL, '受付', 'THỤ PHÓ', 'bộ phận tiếp tân, phòng thường trực', 3),
('ロビー', 'robiｰ', '/audio/minna/bai03/k-robii.mp3', NULL, NULL, NULL, 'hành lang, đại sảnh', 3),
('へや', 'heya', '/audio/minna/bai03/heya.mp3', NULL, '部屋', 'BỘ ỐC', 'căn phòng', 3),
('トイレ（おてあらい）', 'toire(otearai)', '/audio/minna/bai03/k_toiree(otearai).mp3', NULL, '（お手洗い）', 'THỦ TẨY', 'nhà vệ sinh, phòng vệ sinh, toa-lét', 3),
('かいだん', 'kaidan', '/audio/minna/bai03/kaidan.mp3', NULL, '階段', 'GIAI ĐOẠN', 'cầu thang', 3),
('エレベーター', 'erebeｰtaｰ', '/audio/minna/bai03/k_erebe-taa.mp3', NULL, NULL, NULL, 'thang máy', 3),
('エスカレーター', 'esukareｰtaｰ', '/audio/minna/bai03/k_esukareetaa.mp3', NULL, NULL, NULL, 'thang cuốn', 3),
('[お]くに', '[o]kuni', '/audio/minna/bai03/okuni.mp3', NULL, '[お]国', 'QUỐC', 'đất nước (của anh/chị)', 3),
('かいしゃ', 'kaisha', '/audio/minna/bai03/kaisya.mp3', NULL, '会社', 'HỘI XÃ', 'công ty', 3),
('うち', 'uchi', '/audio/minna/bai03/uchi.mp3', NULL, NULL, NULL, 'nhà', 3),
('でんわ', 'denwa', '/audio/minna/bai03/denwa.mp3', NULL, '電話', 'ĐIỆN THOẠI', 'máy điện thoại, điện thoại', 3),
('くつ', 'kutsu', '/audio/minna/bai03/kutsu.mp3', NULL, '靴', 'NGOA', 'giầy', 3),
('ネクタイ', 'nekutai', '/audio/minna/bai03/k-nekutai.mp3', NULL, NULL, NULL, 'cà vạt', 3),
('ワイン', 'wain', '/audio/minna/bai03/k-wain.mp3', NULL, NULL, NULL, 'rượu vang', 3),
('たばこ', 'tabako', '/audio/minna/bai03/tabako.mp3', NULL, NULL, NULL, 'thuốc lá', 3),
('うりば', 'uriba', '/audio/minna/bai03/uriba.mp3', NULL, '売り場', 'MẠI TRƯỜNG', 'quầy bán (trong một cửa hàng bách hóa)', 3),
('ちか', 'chika', '/audio/minna/bai03/chika.mp3', NULL, '地下', 'ĐỊA HẠ', 'tầng hầm, dưới mặt đất', 3),
('―かい（－がい）', '～kai(-gai)', '/audio/minna/bai03/kai(gai).mp3', NULL, '－階', 'GIAI', 'tầng thứ -', 3),
('なんがい', 'nangai', '/audio/minna/bai03/nangai.mp3', NULL, '何階', 'HÀ GIAI', 'tầng mấy', 3),
('―えん', '～en', '/audio/minna/bai03/en.mp3', NULL, '―円', 'VIÊN', '-yên', 3),
('いくら', 'ikura', '/audio/minna/bai03/ikura.mp3', NULL, NULL, NULL, 'bao nhiêu tiền', 3),
('ひゃく', 'hyaku', '/audio/minna/bai03/hyaku.mp3', NULL, '百', 'BÁCH', 'trăm', 3),
('せん', 'sen', '/audio/minna/bai03/sen.mp3', NULL, '千', 'THIÊN', 'nghìn', 3),
('まん', 'man', '/audio/minna/bai03/man.mp3', NULL, '万', 'VẠN', 'mười nghìn, vạn', 3),
('すみません', 'sumimasen', '/audio/minna/bai03/sumimasen.mp3', NULL, NULL, NULL, 'Xin lỗi', 3),
('～でございます', '～degozaimasu', '/audio/minna/bai03/degozaimasu.mp3', NULL, NULL, NULL, '(cách nói lịch sự của 「です」)', 3),
('みせてください', 'misetekudasai', '/audio/minna/bai03/misetekudasai.mp3', NULL, '[～を]見せてください', 'KIẾN', 'cho tôi xem [~]', 3),
('じゃ', 'ja', '/audio/minna/bai03/ja.mp3', NULL, NULL, NULL, 'thế thì, vậy thì', 3),
('[～を]ください', '[～wo]kudasai', '/audio/minna/bai03/kudasai.mp3', NULL, NULL, NULL, 'cho tôi [~]', 3),
('しんおおさか', 'shinoosaka', '/audio/minna/bai03/shinosaka.mp3', NULL, '新大阪', 'TÂN ĐẠI PHẢN', 'tên một nhà ga ở Osaka', 3),
('イタリア', 'itaria', '/audio/minna/bai03/itaria.wav', NULL, NULL, NULL, 'Ý', 3),
('スイス', 'suisu', '/audio/minna/bai03/suisu.wav', NULL, NULL, NULL, 'Thụy Sĩ', 3),
('ＭＴ/ヨーネン/アキックス', 'MT/yoｰnen/akikkusu', '/audio/minna/bai03/mt.wav', NULL, NULL, NULL, 'tên các công ty giả tưởng', 3);